import {clienteBasico} from '../../supabase/functions/_shared/relacionamento-comercial.mjs';
import {consultarClientes} from '../../supabase/functions/_shared/consulta-clientes.mjs';
import {apurarCarteiraHistorica} from '../../supabase/functions/_shared/carteira-historica.mjs';
import {apurarComercial,resolverEscopo,pertence,validarAcao,validarMeta,metaDoPeriodo} from '../../supabase/functions/_shared/comercial.mjs';
const hoje=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}),mes=hoje.slice(0,7),ano=Number(hoje.slice(0,4));
const vendedores=[{id:'101',nome:'Ana Exemplo'},{id:'102',nome:'Beatriz Exemplo'}];
const produtos=[{id:'p1',nome:'Fachada em ACM',categoria:'Fachadas',descricao:'Acabamento para fachadas comerciais',unidade:'m²'},{id:'p2',nome:'Adesivo impresso',categoria:'Adesivos',descricao:'Comunicação visual interna e externa',unidade:'m²'},{id:'p3',nome:'Placa de sinalização',categoria:'Sinalização',descricao:'Identificação de ambientes',unidade:'un'}];
const clientes=[{id:'c1',nome:'Café Horizonte · exemplo',responsavel:'Ana Exemplo',telefone:'Contato de demonstração',email:'contato@example.com',contatos:[]},{id:'c2',nome:'Clínica Aurora · exemplo',responsavel:'Ana Exemplo',contatos:[]},{id:'c3',nome:'Loja Estação · exemplo',razaoSocial:'Estação Comércio · demonstração',documento:'00000000000000',responsavel:'Beatriz Exemplo',contatos:[]}];
const ordens=Array.from({length:15},(_,i)=>{const d=new Date(`${hoje}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-i*6);const p=produtos[i%3];return {id:'os'+i,numero:String(9100+i),clienteId:clientes[i%3].id,cliente:clientes[i%3].nome,vendedor:clientes[i%3].responsavel,tipo:'Normal',data:d.toISOString().slice(0,10),valor:1800+i*355.53,valorBruto:1900+i*355.53,desconto:100,sinalPago:i===0?650:i===1?0:null,itens:[{produto:p.nome,produtoId:p.id,categoria:p.categoria,unidade:p.unidade,quantidade:10+i,valorTotal:1900+i*355.53}]};});
const orcamentos=Array.from({length:6},(_,i)=>({id:'orc'+i,numero:String(7200+i),clienteId:clientes[i%3].id,cliente:clientes[i%3].nome,vendedorNome:clientes[i%3].responsavel,vendedorId:clientes[i%3].responsavel,situacao:i===5?'ganho':'aberto',dataCadastro:mes+'-01',dataEnvio:mes+'-01',valor:5800+i*1350,valorBruto:5900+i*1350,desconto:100,validade:10,trabalho:produtos[i%3].nome}));
clientes.push({id:'c-antigo',nome:'Ateliê Raízes · exemplo',responsavel:'Beatriz Exemplo',documento:'Cadastro de demonstração',contatos:[]});
ordens.push({id:'os-antiga',numero:'1100',clienteId:'c-antigo',cliente:'Ateliê Raízes · exemplo',vendedor:'Ana Exemplo',vendedorErpId:'101',tipo:'Normal',data:`${ano-2}-04-10`,valor:4250.90,valorConfirmado:true,itens:[]});
const mesAnterior=new Date(Date.UTC(ano,Number(mes.slice(5))-1,0,12)).toISOString().slice(0,10);
orcamentos.push({id:'orc-antiga',numero:'6800',clienteId:'c-antigo',cliente:'Ateliê Raízes · exemplo',vendedorNome:'Ana Exemplo',vendedorErpId:'101',situacao:'aberto',dataCadastro:mesAnterior,valor:8200,validade:2,trabalho:'Renovação da fachada'});
orcamentos.push({id:'orc-conferir',numero:'6801',clienteId:'c1',cliente:clientes[0].nome,vendedorNome:'Ana Exemplo',situacao:'conferir',statusErp:'NOVO_STATUS',dataCadastro:mes+'-01',valor:900,trabalho:'Sinalização em revisão'});
let config={diasSemResposta:7,diasVencimento:3,diasReativacao:90,vinculos:{},equipes:[{id:'com1',nome:'Comercial Impresilk',vendedores:['101','102']}],calendario:{configurado:true,diasSemana:[1,2,3,4,5],feriados:[]}};
const acoes=[{id:'a1',clienteId:'c1',cliente:clientes[0].nome,orcamentoId:'orc0',vendedorId:'101',data:hoje,descricao:'Confirmar medidas da fachada',valor:5800,status:'pendente',versao:1,atualizadoEm:new Date().toISOString(),atualizadoPor:'Ana Exemplo',nota:'Cliente pediu uma alternativa de acabamento.'},{id:'a2',clienteId:'c2',cliente:clientes[1].nome,orcamentoId:'orc1',vendedorId:'101',data:mes+'-01',descricao:'Retomar aprovação da sinalização',valor:7150,status:'pendente',versao:1,atualizadoEm:mes+'-01T12:00:00Z',atualizadoPor:'Ana Exemplo'}];
acoes.push({id:'acao-antiga',clienteId:'c-antigo',cliente:'Ateliê Raízes · exemplo',orcamentoId:'orc-antiga',vendedorId:'101',data:mesAnterior,descricao:'Retomar orçamento do mês anterior',status:'pendente',versao:1,atualizadoEm:mesAnterior+'T12:00:00Z',atualizadoPor:'Ana Exemplo'});
acoes.push({id:'pos-exemplo',tipoAcao:'pos_venda',clienteId:'c1',cliente:clientes[0].nome,vendedorId:'101',ordemId:'os0',ordemNumero:'9100',objetivo:'Conferir a satisfação com a nova fachada',descricao:'Confirmar acabamento e legibilidade com o cliente',data:hoje,status:'pendente',fase:'aguardando_cliente',canal:'ligacao',prioridade:'normal',versao:1,atualizadoEm:new Date().toISOString(),atualizadoPor:'Ana Exemplo'}, {id:'prospec-exemplo',tipoAcao:'prospeccao',clienteId:'c3',cliente:clientes[2].nome,clienteDocumento:clientes[2].documento,vendedorId:'102',objetivo:'Conquistar a comunicação visual da nova unidade',descricao:'Agendar apresentação de referências de sinalização',estrategia:'Entender a abertura prevista e envolver quem aprova a identidade visual.',data:hoje,status:'pendente',fase:'planejada',canal:'visita',prioridade:'alta',versao:1,atualizadoEm:new Date().toISOString(),atualizadoPor:'Beatriz Exemplo'});
const metas=[];
export function respostaComercial(b){try{
 if(b.action==='consultarClientes')return Response.json(consultarClientes({valor:{completo:true,clientes:Object.fromEntries(clientes.map(c=>[c.id,c]))},atualizado_em:new Date().toISOString()},b));
 const escopo=resolverEscopo({sub:'demo',master:true}, {vendedores},config,b.filtro);
 const os=ordens.filter(o=>pertence(o,escopo)),orcs=orcamentos.filter(o=>pertence(o,escopo));
 const carteira=apurarCarteiraHistorica({ordens,clientes,orcamentos:orcs,escopo,catalogo:{vendedores},fontes:{historico_status:{valor:{ok:true,desde:'2020-01-01',ate:hoje}}},hoje}),cs=carteira.clientes;
 if(b.action==='contextoRelacionamento'){
  const c=clientes.find(c=>String(c.id)===String(b.clienteId))||cs.find(c=>String(c.id)===String(b.clienteId));
  if(!c)return Response.json({erro:'Cliente não localizado.'},{status:404});
  return Response.json({cliente:clienteBasico(c),autorizado:cs.some(x=>x.id===c.id),orcamentos:orcs.filter(o=>o.clienteId===c.id),vendas:os.filter(o=>o.clienteId===c.id).map(o=>({...o,trabalho:(o.itens||[]).map(i=>i.produto).join(' · ')})),acoes:acoes.filter(a=>a.clienteId===c.id&&(!escopo.ids||escopo.ids.includes(a.vendedorId))),coberturaHistorica:carteira.coberturaHistorica});
 }
 if(b.action==='salvarAcao'){const anterior=acoes.find(a=>a.id===b.acao.id);if((anterior?.versao??null)!==(b.versao??null))return Response.json({erro:'A atividade mudou. Atualize antes de salvar.'},{status:409});const a=validarAcao({...anterior,...b.acao},escopo,{vendedores,clientes:cs,orcamentos:orcs,vendasCliente:os.filter(o=>String(o.clienteId)===String(b.acao.clienteId)),clientesConsulta:clientes.map(clienteBasico),cadastroCompleto:true},'Conta de demonstração',new Date().toISOString());const nova={...a,versao:(anterior?.versao||0)+1,historico:[...(anterior?.historico||[]),{em:new Date().toISOString(),autor:'Conta de demonstração',descricao:a.descricao,anterior:anterior?Object.fromEntries(Object.entries(anterior).filter(([k])=>k!=='historico')):null}]};if(anterior)acoes[acoes.indexOf(anterior)]=nova;else acoes.push(nova);return Response.json({acao:nova});}
 if(b.action==='salvarMeta'){const m=validarMeta(b.meta,{vendedores},'Conta de demonstração',new Date().toISOString());const i=metas.findIndex(x=>x.id===m.id);if(i>=0)metas[i]=m;else metas.push(m);return Response.json({meta:m});}
 if(b.action==='configurar'){config={...b.config,atualizadoEm:new Date().toISOString()};return Response.json({ok:true});}
 const base={ordens:os,orcamentos:orcs,clientes:cs,acoes:acoes.filter(a=>!escopo.ids||escopo.ids.includes(a.vendedorId)),config,meta:metaDoPeriodo(metas,escopo,{vendedores},b.filtro),coberturaHistorica:carteira.coberturaHistorica,cobertura:{desde:'2020-01-01',ate:hoje},coberturaOrcamentos:{desde:mes.slice(0,4)+'-01-01',ate:hoje}};
 return Response.json({base,metas:metas.filter(m=>!escopo.ids||escopo.ids.includes(m.vendedorId)),relatorio:apurarComercial(base,b.filtro,hoje),financeiro:{temPagos:true,desdeDados:'2025-01-01',consultadas:os.map(o=>o.numero),abertos:[{id:'titulo-exemplo',os:'9100',valor:1150,pago:650}],pagos:[],permutaDaOS:{}},escopo,catalogo:{produtos,vendedores},config,fontes:{orcamentos:{atualizadoEm:new Date().toISOString()},ordens:{atualizadoEm:new Date().toISOString()}},avisos:['Demonstração com dados fictícios; nada é gravado no servidor.'],atualizadoEm:new Date().toISOString()});
 }catch(e){return Response.json({erro:e.message},{status:e.status||400});}}

export function funilComercialDemo(){return {atualizadoEm:new Date().toISOString(),escopo:'ATIVO',grupos:[{id:'1',nome:'Comercial · demonstração',fases:[{id:'1',nome:'Primeiro contato'},{id:'2',nome:'Negociação'},{id:'3',nome:'Visita técnica'}]}],cards:[{id:'1',clienteId:clientes[0].id,cliente:clientes[0].nome,titulo:'Fachada e comunicação visual',grupoId:'1',faseId:'2',fase:'Negociação',responsavel:'Ana Exemplo',responsavelId:'101',valor:12500,origem:'Indicação',status:'EM_ABERTO',ultimaInteracao:hoje}]};}
