import {apurarComercial,resolverEscopo,pertence,validarAcao,validarMeta,metaDoPeriodo} from '../../supabase/functions/_shared/comercial.mjs';
const hoje=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}),mes=hoje.slice(0,7),ano=Number(hoje.slice(0,4));
const vendedores=[{id:'101',nome:'Ana Exemplo'},{id:'102',nome:'Beatriz Exemplo'}];
const produtos=[{id:'p1',nome:'Fachada em ACM',categoria:'Fachadas',descricao:'Acabamento para fachadas comerciais',unidade:'m²'},{id:'p2',nome:'Adesivo impresso',categoria:'Adesivos',descricao:'Comunicação visual interna e externa',unidade:'m²'},{id:'p3',nome:'Placa de sinalização',categoria:'Sinalização',descricao:'Identificação de ambientes',unidade:'un'}];
const clientes=[{id:'c1',nome:'Café Horizonte · exemplo',responsavel:'Ana Exemplo',telefone:'Contato de demonstração',email:'contato@example.com',contatos:[]},{id:'c2',nome:'Clínica Aurora · exemplo',responsavel:'Ana Exemplo',contatos:[]},{id:'c3',nome:'Loja Estação · exemplo',responsavel:'Beatriz Exemplo',contatos:[]}];
const ordens=Array.from({length:15},(_,i)=>{const d=new Date(`${hoje}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-i*6);const p=produtos[i%3];return {id:'os'+i,numero:String(9100+i),clienteId:clientes[i%3].id,cliente:clientes[i%3].nome,vendedor:clientes[i%3].responsavel,tipo:'Normal',data:d.toISOString().slice(0,10),valor:1800+i*355.53,valorBruto:1900+i*355.53,desconto:100,itens:[{produto:p.nome,produtoId:p.id,categoria:p.categoria,unidade:p.unidade,quantidade:10+i,valorTotal:1900+i*355.53}]};});
const orcamentos=Array.from({length:6},(_,i)=>({id:'orc'+i,numero:String(7200+i),clienteId:clientes[i%3].id,cliente:clientes[i%3].nome,vendedorNome:clientes[i%3].responsavel,vendedorId:clientes[i%3].responsavel,situacao:i===5?'ganho':'aberto',dataCadastro:mes+'-01',dataEnvio:mes+'-01',valor:5800+i*1350,valorBruto:5900+i*1350,desconto:100,validade:10,trabalho:produtos[i%3].nome}));
let config={diasSemResposta:7,diasVencimento:3,diasReativacao:90,vinculos:{},equipes:[{id:'com1',nome:'Comercial Impresilk',vendedores:['101','102']}],calendario:{configurado:true,diasSemana:[1,2,3,4,5],feriados:[]}};
const acoes=[{id:'a1',clienteId:'c1',cliente:clientes[0].nome,orcamentoId:'orc0',vendedorId:'101',data:hoje,descricao:'Confirmar medidas da fachada',valor:5800,status:'pendente',versao:1,atualizadoEm:new Date().toISOString(),atualizadoPor:'Ana Exemplo',nota:'Cliente pediu uma alternativa de acabamento.'},{id:'a2',clienteId:'c2',cliente:clientes[1].nome,orcamentoId:'orc1',vendedorId:'101',data:mes+'-01',descricao:'Retomar aprovação da sinalização',valor:7150,status:'pendente',versao:1,atualizadoEm:mes+'-01T12:00:00Z',atualizadoPor:'Ana Exemplo'}];
const metas=[];
export function respostaComercial(b){try{
 const escopo=resolverEscopo({sub:'demo',master:true}, {vendedores},config,b.filtro);
 const cs=clientes.filter(c=>pertence(c,escopo,'responsavel')).map(c=>({...c,naCarteira:true})),os=ordens.filter(o=>pertence(o,escopo)),orcs=orcamentos.filter(o=>pertence(o,escopo));
 if(b.action==='salvarAcao'){const anterior=acoes.find(a=>a.id===b.acao.id);if((anterior?.versao??null)!==(b.versao??null))return Response.json({erro:'A atividade mudou. Atualize antes de salvar.'},{status:409});const a=validarAcao(b.acao,escopo,{vendedores,clientes:cs,orcamentos:orcs},'Conta de demonstração',new Date().toISOString());const nova={...a,versao:(anterior?.versao||0)+1};if(anterior)acoes[acoes.indexOf(anterior)]=nova;else acoes.push(nova);return Response.json({acao:nova});}
 if(b.action==='salvarMeta'){const m=validarMeta(b.meta,{vendedores},'Conta de demonstração',new Date().toISOString());const i=metas.findIndex(x=>x.id===m.id);if(i>=0)metas[i]=m;else metas.push(m);return Response.json({meta:m});}
 if(b.action==='configurar'){config={...b.config,atualizadoEm:new Date().toISOString()};return Response.json({ok:true});}
 const base={ordens:os,orcamentos:orcs,clientes:cs,acoes:acoes.filter(a=>!escopo.ids||escopo.ids.includes(a.vendedorId)),config,meta:metaDoPeriodo(metas,escopo,{vendedores},b.filtro),cobertura:{desde:`${ano-1}-01-01`,ate:hoje},coberturaOrcamentos:{desde:mes.slice(0,4)+'-01-01',ate:hoje}};
 return Response.json({base,metas:metas.filter(m=>!escopo.ids||escopo.ids.includes(m.vendedorId)),relatorio:apurarComercial(base,b.filtro,hoje),escopo,catalogo:{produtos,vendedores},config,fontes:{orcamentos:{atualizadoEm:new Date().toISOString()},ordens:{atualizadoEm:new Date().toISOString()}},avisos:['Demonstração com dados fictícios; nada é gravado no servidor.'],atualizadoEm:new Date().toISOString()});
 }catch(e){return Response.json({erro:e.message},{status:e.status||400});}}
