import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {transform} from 'esbuild';
async function carregar(nome){const {code}=await transform(await readFile(new URL(`../supabase/functions/_shared/${nome}.ts`,import.meta.url),'utf8'),{loader:'ts',format:'esm'});return import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));}
const {capturarArquivos,prepararArquivos,resumo,base64}=await carregar('arquivos-backup');
const {trocarSenhaConsistente}=await carregar('troca-senha');
const bucket=()=>{const objetos=new Map();return{objetos,list:async(_,op)=>({data:[...objetos.keys()].slice(op.offset,op.offset+op.limit).map(name=>({id:name,name}))}),download:async caminho=>objetos.has(caminho)?{data:new Blob([objetos.get(caminho)])}:{error:{statusCode:404}},upload:async(caminho,bytes)=>{objetos.set(caminho,bytes);return{};},remove:async caminhos=>{caminhos.forEach(c=>objetos.delete(c));return{};}};};
test('backup e recuperação conferem os bytes de mais de uma página de arquivos',async()=>{const origem=bucket();for(let n=0;n<105;n++)origem.objetos.set(`foto-${n}`,new TextEncoder().encode('imagem fictícia '+n));const copia=await capturarArquivos(origem);assert.equal(copia.length,105);const destino=bucket();const recuperado=await prepararArquivos(destino,copia);assert.equal(recuperado.quantidade,105);assert.deepEqual(destino.objetos,origem.objetos);await recuperado.desfazer();assert.equal(destino.objetos.size,0);});
test('arquivo corrompido não escreve nada; arquivo diferente existente não é substituído',async()=>{const destino=bucket(),bytes=new Uint8Array([1,2]);const a={caminho:'foto',bytes:2,sha256:await resumo(bytes),base64:base64(bytes)};await assert.rejects(prepararArquivos(destino,[{...a,sha256:'errado'}]));assert.equal(destino.objetos.size,0);destino.objetos.set('foto',new Uint8Array([3]));await assert.rejects(prepararArquivos(destino,[a]),/diferente/);assert.deepEqual([...destino.objetos.get('foto')],[3]);});
test('falha ao salvar legado repõe a senha anterior no Auth',async()=>{let senha='anterior';await assert.rejects(trocarSenhaConsistente({aplicarAuth:async()=>{senha='nova';},salvarLegado:async()=>{throw Error('banco');},reporAuth:async()=>{senha='anterior';}}),/anterior foi mantida/);assert.equal(senha,'anterior');});
test('falha na compensação informa explicitamente qual senha ficou ativa',async()=>{await assert.rejects(trocarSenhaConsistente({aplicarAuth:async()=>{},salvarLegado:async()=>{throw Error();},reporAuth:async()=>{throw Error();}}),/nova senha está ativa/);});
test('falha no Auth não grava nenhum hash legado',async()=>{let gravou=false;await assert.rejects(trocarSenhaConsistente({aplicarAuth:async()=>{throw Error();},salvarLegado:async()=>{gravou=true;}}));assert.equal(gravou,false);});
test('troca concluída aplica as etapas e não executa compensação',async()=>{const etapas=[];await trocarSenhaConsistente({aplicarAuth:async()=>etapas.push('auth'),salvarLegado:async()=>etapas.push('legado'),reporAuth:async()=>etapas.push('compensar')});assert.deepEqual(etapas,['auth','legado']);});
