import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{buildSync}=createRequire(require.resolve('vite'))('esbuild');
const source=readFileSync(new URL('../supabase/functions/painel-comercial/index.ts',import.meta.url),'utf8').replace(/^import.*createClient.*\n/m,'const createClient=globalThis.createClient;\n').replace(/^import.*verificarJwt.*\n/m,'const {verificarJwt,crachaRevogado}=globalThis;\n');
const code=buildSync({stdin:{contents:source,loader:'ts',resolveDir:fileURLToPath(new URL('../supabase/functions/painel-comercial/',import.meta.url))},bundle:true,write:false,format:'iife',platform:'node'}).outputFiles[0].text;
const hoje=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}),filtro={de:hoje.slice(0,7)+'-01',ate:hoje};
function setup(){let handler,session={sub:'ana',nome:'Ana',vend:'Ana Silva',perms:['orcamentos']},revoked=false,fail=false;const cache=[
 {chave:'comercial_catalogo',valor:{completo:true,vendedores:[{id:'1',nome:'Ana Silva'},{id:'2',nome:'Bia Costa'}],produtos:[]}},
 {chave:'orcamentos',valor:[{id:'p1',numero:'1',clienteId:'c1',cliente:'Loja A',vendedorNome:'Ana Silva',valor:100,situacao:'aberto',dataCadastro:hoje},{id:'p2',clienteId:'c2',cliente:'Loja B',vendedorNome:'Bia Costa',valor:200,situacao:'aberto',dataCadastro:hoje}]},
 {chave:'crm_clientes',valor:{completo:true,clientes:{c1:{id:'c1',nome:'Loja A',responsavel:'Ana Silva'},c2:{id:'c2',nome:'Loja B',responsavel:'Bia Costa'}}}},
 {chave:'status',valor:{ultimaCompleta:hoje+'T12:00:00Z'}},{chave:'historico_status',valor:{ok:true,desde:'2020-01-01',ate:hoje}},{chave:'ordens',valor:[]}
 ].map(x=>({...x,atualizado_em:hoje+'T12:00:00Z'}));
 const cfg={vinculos:{ana:'1',bia:'2'},equipes:[],diasSemResposta:7,diasVencimento:3,diasReativacao:90};
 const ordens=[{id:'1',cliente:'Loja A',data:hoje,valor:100,vendedor:'Ana Silva',comercial:{tipo:'Normal',clienteId:'c1'}},{id:'2',cliente:'Loja B',data:hoje,valor:200,vendedor:'Bia Costa',comercial:{tipo:'Normal',clienteId:'c2'}}];
 const acoes=[{colecao:'comercial_acoes',id:'b',registro:{id:'b',vendedorId:'2',clienteId:'c2',cliente:'Loja B',data:hoje,descricao:'Segredo da Bia',status:'pendente',versao:1}}];let writes=0;
 const db={painel_cache:cache,painel_registros:[{colecao:'comercial_config',id:'regras',registro:cfg},...acoes],painel_ordens:ordens,painel_comercial_acoes:acoes};
 const sb={from(table){let rows=db[table]||[];const q={select(){return q},eq(k,v){rows=rows.filter(x=>x[k]===v);return q},in(k,vs){rows=rows.filter(x=>vs.includes(k==='registro->>vendedorId'?x.registro.vendedorId:x[k]));return q},gte(k,v){rows=rows.filter(x=>x[k]>=v);return q},lte(k,v){rows=rows.filter(x=>x[k]<=v);return q},order(){return q},range(a,b){return Promise.resolve(fail?{error:{}}:{data:structuredClone(rows.slice(a,b+1))})},maybeSingle(){return Promise.resolve(fail?{error:{}}:{data:structuredClone(rows[0]||null)})},then(fn){return Promise.resolve(fail?{error:{}}:{data:structuredClone(rows)}).then(fn)}};return q},async rpc(n,p){writes++;if(n==='painel_comercial_salvar_acao'){const old=acoes.find(a=>a.id===p.p_id);if(old && p.p_autorizados&&!p.p_autorizados.includes(old.registro.vendedorId))return {error:{}};if((old?.registro.versao??null)!==(p.p_versao??null))return {error:{}};const x={colecao:'comercial_acoes',id:p.p_id,registro:{...p.p_registro,versao:(old?.registro.versao||0)+1}};if(old){acoes[acoes.indexOf(old)]=x;db.painel_registros[db.painel_registros.indexOf(old)]=x;}else {acoes.push(x);db.painel_registros.push(x);}return {data:x.registro};}return {data:{}};}};
 vm.runInNewContext(code,{createClient:()=>sb,verificarJwt:async()=>session,crachaRevogado:async()=>revoked,Deno:{env:{get:()=> 'test'},serve:fn=>handler=fn},Response,Request,crypto,console});
 return {db,cache,ordens,acoes,get writes(){return writes},session:s=>session=s,revoke:()=>revoked=true,fail:()=>fail=true,async call(body={},auth=true){const r=await handler(new Request('http://local',{method:'POST',headers:auth?{authorization:'Bearer test'}:{},body:JSON.stringify({action:'painel',filtro,...body})}));return {status:r.status,...await r.json()}}};}
test('servidor exige sessão, revogação, módulo e vínculo oficial',async()=>{const t=setup();assert.equal((await t.call({},false)).status,401);t.session({sub:'x',perms:['agenda']});assert.equal((await t.call()).status,403);t.session({sub:'x',perms:['orcamentos']});assert.equal((await t.call()).codigo,'VINCULO_PENDENTE');t.revoke();assert.equal((await t.call()).status,401);});
test('resposta inteira só contém registros da vendedora; config privada não sai dentro de base',async()=>{const t=setup(),r=await t.call();assert.equal(r.status,200);assert.equal(r.relatorio.valor,10000);assert.equal(r.relatorio.pedidos,1);assert.equal(r.base.ordens.length,1);assert.equal(r.base.clientes.length,1);assert.equal(r.base.acoes.length,0);assert.equal(r.base.config.vinculos,undefined);assert.equal(r.config.vinculos,undefined);assert.equal(JSON.stringify(r).includes('Loja B'),false);assert.equal(JSON.stringify(r).includes('Segredo da Bia'),false);});
test('manipular filtros de outra vendedora ou equipe é bloqueado',async()=>{const t=setup();assert.equal((await t.call({filtro:{...filtro,vendedor:'2'}})).status,403);assert.equal((await t.call({filtro:{...filtro,equipe:'x'}})).status,403);});
test('gestor consolida e filtra; carteira segue o filtro',async()=>{const t=setup();t.session({sub:'gestor',master:true});assert.equal((await t.call()).relatorio.valor,30000);const r=await t.call({filtro:{...filtro,vendedor:'2'}});assert.equal(r.relatorio.valor,20000);assert.equal(r.base.clientes.length,1);assert.equal(r.base.clientes[0].id,'c2');});
test('ciclo de ação persistida: criar, concluir, reagendar e conflito preserva versão',async()=>{const t=setup(),acao={id:'a',clienteId:'c1',orcamentoId:'p1',vendedorId:'1',descricao:'Confirmar medidas',data:hoje};let r=await t.call({action:'salvarAcao',acao});assert.equal(r.status,200);assert.equal(r.acao.versao,1);assert.equal((await t.call()).relatorio.hojeA.length,1);r=await t.call({action:'salvarAcao',acao:{...acao,status:'concluida'},versao:1});assert.equal(r.status,200);assert.equal((await t.call()).relatorio.hojeA.length,0);r=await t.call({action:'salvarAcao',acao,versao:1});assert.equal(r.status,409);assert.equal(t.acoes.find(x=>x.id==='a').registro.status,'concluida');});
test('não permite sobrescrever ação alheia nem atribuir a outra pessoa nem vínculo de cliente forjado',async()=>{const t=setup(),a={id:'a',clienteId:'c1',orcamentoId:'p1',vendedorId:'1',descricao:'x',data:hoje};for(const acao of [{...a,id:'b'},{...a,vendedorId:'2'},{...a,clienteId:'c2'},{...a,orcamentoId:'p2'}])assert.equal((await t.call({action:'salvarAcao',acao})).status,403);assert.equal(t.writes,0);assert.equal((await t.call({action:'configurar',config:{}})).status,403);});
test('paginação não perde vendas depois de 500 registros; falha não vira zero',async()=>{const t=setup();t.ordens.splice(0,t.ordens.length,...Array.from({length:1001},(_,i)=>({id:String(i),data:hoje,valor:1,vendedor:'Ana Silva',comercial:{tipo:'Normal',clienteId:'c1'}})));const r=await t.call();assert.equal(r.status,200);assert.equal(r.relatorio.pedidos,1001);assert.equal(r.relatorio.valor,100100);t.fail();assert.equal((await t.call()).status,503);});
test('cache recente enriquece tipo e cliente sem duplicar a O.S. histórica',async()=>{const t=setup();t.ordens[0].comercial=null;t.cache.find(c=>c.chave==='ordens').valor=[{id:'1',data:hoje,valor:100,tipo:'Normal',clienteId:'c1',vendedor:'Ana Silva'}];const r=await t.call();assert.equal(r.relatorio.pedidos,1);assert.equal(r.relatorio.incompletas,0);assert.equal(r.relatorio.clientes[0].centavos,10000);});
test('retornos existentes da mesa entram no painel sem ressuscitar negociação encerrada',async()=>{const t=setup();t.db.painel_registros.push({colecao:'ov_orc',id:'p1',registro:{proximoToque:hoje,nota:'Retorno antigo'}});let r=await t.call();assert.equal(r.relatorio.hojeA.length,1);assert.equal(r.relatorio.hojeA[0].origem,'mesa');t.db.painel_registros.at(-1).registro.situacao='perdido';r=await t.call();assert.equal(r.relatorio.hojeA.length,0);assert.equal(r.relatorio.abertas.length,0);assert.equal(r.relatorio.propostas[0].situacaoErp,'aberto');});
test('metas só podem ser cadastradas pela direção e consultas respeitam a vendedora',async()=>{
 const t=setup();assert.equal((await t.call({action:'salvarMeta',meta:{vendedorId:'1',mes:hoje.slice(0,7),valor:1000}})).status,403);
 assert.equal(t.writes,0);
 t.db.painel_registros.push({colecao:'comercial_metas',id:'meta1',registro:{vendedorId:'1',mes:hoje.slice(0,7),valor:1000}},{colecao:'comercial_metas',id:'meta2',registro:{vendedorId:'2',mes:hoje.slice(0,7),valor:2000}});
 const r=await t.call();assert.equal(r.metas.length,1);assert.equal(r.metas[0].vendedorId,'1');
 t.session({sub:'diretor',nome:'Direção',master:true});assert.equal((await t.call({action:'salvarMeta',meta:{vendedorId:'1',mes:hoje.slice(0,7),valor:1000}})).status,200);
 assert.equal((await t.call({action:'salvarMeta',meta:{vendedorId:'inventada',mes:hoje.slice(0,7),valor:1000}})).status,400);
});
