import {test} from 'node:test';
import assert from 'node:assert/strict';
import {criarSincronizacao,diferencaConfig} from '../src/lib/config-sincronizacao.js';
const inicial={parametros:{caixa:100,dias:30},vendedores:['A']};
test('envia somente os campos alterados, preservando o restante',()=>{assert.deepEqual(diferencaConfig(inicial,{...inicial,parametros:{caixa:200,dias:30}}),{parametros:{caixa:200}});});
test('não permite alteração antes de confirmar a leitura',()=>{const c=criarSincronizacao({salvar:async()=>{},aoMudar:()=>{}});assert.throws(()=>c.alterar(()=>inicial),/carreg/);});
test('retentativa guarda a edição e só declara salva após confirmação',async()=>{let falhar=true;const estados=[];const c=criarSincronizacao({salvar:async patch=>{if(falhar)throw Error('sem rede');return{valor:{...inicial,parametros:{...inicial.parametros,...patch.parametros}}};},aoMudar:s=>estados.push(s)});c.carregar(inicial);c.alterar(v=>({...v,parametros:{...v.parametros,caixa:200}}));await c.salvar();assert.equal(c.estado().status,'erro');assert.equal(c.estado().config.parametros.caixa,200);falhar=false;await c.salvar();assert.equal(c.estado().status,'salvo');assert.equal(estados.at(-1).config.parametros.caixa,200);});
test('resposta da sessão anterior não altera a sessão nova',async()=>{let concluir;const c=criarSincronizacao({salvar:()=>new Promise(r=>concluir=r),aoMudar:()=>{}});c.carregar(inicial);c.alterar(v=>({...v,vendedores:['B']}));const p=c.salvar();c.limpar();c.carregar({parametros:{caixa:900}});concluir({valor:{vendedores:['B']}});await p;assert.equal(c.estado().config.parametros.caixa,900);});
test('edição feita durante envio é mantida e enviada depois',async()=>{let concluir;let n=0;const banco=structuredClone(inicial);const c=criarSincronizacao({salvar:async patch=>{if(++n===1)await new Promise(r=>concluir=r);banco.parametros={...banco.parametros,...patch.parametros};return{valor:structuredClone(banco)};},aoMudar:()=>{}});c.carregar(inicial);c.alterar(v=>({...v,parametros:{...v.parametros,caixa:200}}));const p=c.salvar();c.alterar(v=>({...v,parametros:{...v.parametros,dias:40}}));concluir();await p;assert.equal(c.estado().config.parametros.dias,40);await c.salvar();assert.deepEqual(banco.parametros,{caixa:200,dias:40});});
