import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{buildSync}=createRequire(require.resolve('vite'))('esbuild');
const source=readFileSync(new URL('../supabase/functions/painel-processos/index.ts',import.meta.url),'utf8').replace(/^import.*createClient.*\n/m,'const createClient=globalThis.createClient;\n').replace(/^import.*verificarJwt.*\n/m,'const {verificarJwt,crachaRevogado}=globalThis;\n');
const code=buildSync({stdin:{contents:source,loader:'ts',resolveDir:fileURLToPath(new URL('../supabase/functions/painel-processos/',import.meta.url))},bundle:true,write:false,format:'iife',platform:'node'}).outputFiles[0].text;
function setup(){let handler,session={sub:'ana',nome:'Ana',perms:['demandas']},revoked=false,conflict=false;const rows=new Map(),files=new Map(),queries=[];
 const rh={colaboradores:[{id:'rh-1',nome:'Ana RH',statusId:'ativo'},{id:'rh-2',nome:'Bia RH',statusId:'ativo'}],status:[{id:'ativo',contaComoAtivo:'true'}],areas:[],cargos:[]};
 const contas=[{id:'a1',usuario:'ana',colaborador_id:'rh-1'},{id:'a2',usuario:'bia',colaborador_id:'rh-2'},{id:'a3',usuario:'fora',colaborador_id:'rh-3'}];
 const papeis=[{conta_id:'a2',sistema:'painel',login:'bia-legado'}];
 const sb={from(tabela){const filtros=[];let limite=null;const obter=()=>{let data=tabela==='registros'?rh[filtros.find(([k])=>k==='colecao')?.[1]]||[]:tabela==='acesso_conta'?contas:tabela==='acesso_papel'?papeis:[...rows].map(([id,registro])=>({id,registro,colecao:'processos_empresa'}));for(const[k,v]of filtros){if(tabela==='registros')continue;data=data.filter(x=>Array.isArray(v)?v.includes(x[k]):x[k]===v);}if(limite)data=data.slice(limite[0],limite[1]+1);return {data};};const q={select(colunas){queries.push({tabela,colunas});return q;},eq(k,v){filtros.push([k,v]);return q;},in(k,v){filtros.push([k,v]);return q;},order(){return q;},range(a,b){limite=[a,b];return q;},maybeSingle(){return Promise.resolve({data:obter().data[0]||null});},then(ok,bad){return Promise.resolve(obter()).then(ok,bad);}};return q;},async rpc(n,p){if(conflict||JSON.stringify(rows.get(p.p_id)||null)!==JSON.stringify(p.p_anterior))return {error:{code:'40001'}};rows.set(p.p_id,p.p_registro);return {};},storage:{from(){return {async upload(k,v){files.set(k,v);return {};},async remove(ks){ks.forEach(k=>files.delete(k));return {};},async createSignedUrl(k){return {data:{signedUrl:'https://private.example/'+k}};}};}}};
 vm.runInNewContext(code,{createClient:()=>sb,verificarJwt:async()=>session,crachaRevogado:async()=>revoked,Deno:{env:{get:()=> 'test'},serve:fn=>handler=fn},Response,Request,crypto,TextEncoder,atob,Uint8Array,console});
 return {rows,files,queries,contas,papeis,rh,session:s=>session=s,revoke:()=>revoked=true,conflict:()=>conflict=true,async call(body,auth=true,token=''){const r=await handler(new Request('http://local',{method:'POST',headers:token?{'x-convite':token}:auth?{authorization:'Bearer test'}:{},body:JSON.stringify(body)}));return {status:r.status,...await r.json()};}};
}
const item=()=>({id:'c1',tipo:'consultoria',titulo:'Organização',empresa:'Consultoria teste',objetivo:'Melhorar',analise:'CONFIDENCIAL',solucao:'Plano',situacao:'analise',prioridade:'normal',setor:'empresa',prazo:'2026-10-30',responsavelRhId:'rh-1',envolvidos:[{rhId:'rh-1',nome:'forjado'},{rhId:'rh-2'}],etapas:[{id:'e1',titulo:'Estudar',responsavelRhId:'rh-2',prazo:'2026-10-15',situacao:'pendente',dependeDe:[]}]});
const membro={sub:'bia',nome:'Bia',perms:['demandas']};
test('sessão, permissão, revogação e limites de ação',async()=>{const t=setup();assert.equal((await t.call({action:'listar'},false)).status,401);t.session({sub:'ana',perms:['agenda']});assert.equal((await t.call({action:'pessoas'})).status,403);assert.equal(t.queries.length,0);t.session(membro);assert.equal((await t.call({action:'apagar'})).status,400);t.revoke();assert.equal((await t.call({action:'listar'})).status,401);});
test('RH canônico, identidade pelo vínculo, calendário e escopo por envolvidos',async()=>{const t=setup();const r=(await t.call({action:'salvar',item:item()})).item;assert.equal(r.envolvidos[0].nome,'Ana RH');assert.equal(r.podeGerir,true);assert.equal(r.meuRhId,'rh-1');assert.ok(t.queries.every(q=>!q.colunas.includes('cpf')&&!q.colunas.includes('salario')&&q.colunas!=='*'));t.session({...membro,sub:'bia-legado'});assert.equal((await t.call({action:'listar'})).itens.length,1);assert.equal((await t.call({action:'obter',id:r.id})).item.meuRhId,'rh-2');let a=await t.call({action:'agenda',mes:'2026-10'});assert.equal(a.eventos.length,2);assert.ok(!JSON.stringify(a).includes('CONFIDENCIAL'));t.session({sub:'fora',nome:'Ana RH',perms:['demandas']});assert.equal((await t.call({action:'listar'})).itens.length,0);assert.equal((await t.call({action:'agenda',mes:'2026-10'})).eventos.length,0);assert.equal((await t.call({action:'obter',id:r.id})).status,404);});
test('participante atualiza sua etapa, não administra ficha nem convites; conflito conserva versão',async()=>{const t=setup();let r=(await t.call({action:'salvar',item:item()})).item;t.session(membro);assert.equal((await t.call({action:'salvar',item:{...r,versaoAnterior:r.versao}})).status,403);assert.equal((await t.call({action:'convidar',id:r.id,versao:r.versao,nome:'X',dias:2})).status,403);const a=await t.call({action:'etapa',id:r.id,versao:r.versao,etapaId:'e1',situacao:'execucao',nota:'Iniciado',responsavelRhId:'rh-1',prazo:'2099-01-01'});assert.equal(a.status,200);assert.equal(a.item.etapas[0].prazo,'2026-10-15');assert.equal(a.item.etapas[0].responsavelRhId,'rh-2');assert.equal((await t.call({action:'registro',id:r.id,versao:r.versao,texto:'antigo'})).status,409);r=a.item;t.session({sub:'ana',perms:['demandas']});t.conflict();assert.equal((await t.call({action:'anexar',id:r.id,versao:r.versao,nome:'a.pdf',mime:'application/pdf',base64:btoa('%PDF-test')})).status,409);assert.equal(t.files.size,0);assert.equal(t.rows.get(r.id).anexos.length,0);});
test('convite usa hash, restringe RH/análise/arquivos, valida contribuição e pode ser revogado',async()=>{const t=setup();let r=(await t.call({action:'salvar',item:item()})).item;r=(await t.call({action:'anexar',id:r.id,versao:r.versao,nome:'a.pdf',mime:'application/pdf',base64:btoa('%PDF-test')})).item;const a=r.anexos[0];const c=await t.call({action:'convidar',id:r.id,versao:r.versao,nome:'Consultor',dias:14});assert.equal(c.status,200);const token=c.convite;assert.equal(token.split('.')[1].length,64);assert.ok(!JSON.stringify(t.rows.get(r.id)).includes(token.split('.')[1]));assert.ok(!JSON.stringify(c.item).includes('hash'));r=c.item;let g=await t.call({action:'obter'},false,token);assert.equal(g.status,200);assert.ok(!JSON.stringify(g).includes('CONFIDENCIAL'));assert.ok(!JSON.stringify(g).includes('rh-'));assert.equal(g.item.anexos.length,0);for(const action of ['listar','pessoas','agenda','salvar','convidar','compartilhar','revogar'])assert.equal((await t.call({action},false,token)).status,403);assert.equal((await t.call({action:'obter',id:'c2'},false,token)).status,403);assert.equal((await t.call({action:'arquivo',arquivoId:a.id},false,token)).status,404);r=(await t.call({action:'compartilhar',id:r.id,versao:r.versao,arquivoId:a.id,compartilhado:true})).item;assert.equal((await t.call({action:'arquivo',arquivoId:a.id},false,token)).status,200);g=await t.call({action:'registro',versao:r.versao,texto:'Meu avanço',tipo:'acao',titulo:'Mapa do fluxo',dataAcao:'2026-10-08',resultado:'Documento preparado',proximoPasso:'Validar',etapaId:'e1',compartilhado:false},false,token);assert.equal(g.item.registros[0].nome,'Consultor');assert.equal(g.item.registros[0].compartilhado,true);assert.equal(g.item.registros[0].resultado,'Documento preparado');assert.equal(g.item.registros[0].proximoPasso,'Validar');assert.equal(g.item.registros[0].etapaId,'e1');assert.equal((await t.call({action:'etapa',versao:g.item.versao,etapaId:'e1',situacao:'concluida'},false,token)).status,422);g=await t.call({action:'etapa',versao:g.item.versao,etapaId:'e1',situacao:'validacao',nota:'Confira'},false,token);assert.equal(g.status,200);r=(await t.call({action:'revogar',id:r.id,versao:g.item.versao,conviteId:r.convites[0].id})).item;assert.equal((await t.call({action:'obter'},false,token)).status,401);});
test('convite expirado, processo cancelado, token inválido e limites de prazo',async()=>{const t=setup();let r=(await t.call({action:'salvar',item:item()})).item;assert.equal((await t.call({action:'convidar',id:r.id,versao:r.versao,nome:'X',dias:31})).status,422);const c=await t.call({action:'convidar',id:r.id,versao:r.versao,nome:'X',dias:1});t.rows.get(r.id).convites[0].expiraEm='2000-01-01';assert.equal((await t.call({action:'obter'},false,c.convite)).status,401);assert.equal((await t.call({action:'obter'},false,'c1.bad')).status,401);assert.equal((await t.call({action:'obter'},false,'c1.'+'a'.repeat(64))).status,401);});
test('mapeamento ambíguo não concede RH; sem comparação de nomes',async()=>{const t=setup();await t.call({action:'salvar',item:item()});t.contas.push({id:'duplicado',usuario:'bia',colaborador_id:'rh-1'});t.session(membro);assert.equal((await t.call({action:'listar'})).itens.length,0);});
test('diretório e lista paginam 501 resultados; datas inválidas não persistem',async()=>{const t=setup();const r=(await t.call({action:'salvar',item:item()})).item;for(let i=1;i<501;i++)t.rows.set('p'+i,{...r,id:'p'+i});assert.equal((await t.call({action:'listar'})).itens.length,501);assert.equal((await t.call({action:'salvar',item:{...item(),id:'invalido',prazo:'2026-02-30'}})).status,422);assert.ok(!t.rows.has('invalido'));assert.equal((await t.call({action:'agenda',mes:'2026-13'})).status,422);});

test('consultores têm cadastro próprio e implantação fica no processo e autor corretos',async()=>{
 const t=setup();let r=(await t.call({action:'salvar',item:item()})).item;
 let x=await t.call({action:'consultor',id:r.id,versao:r.versao,nome:'Consultora Ana',funcao:'Qualidade',contato:'consultora@example.test',rhId:'rh-2'});assert.equal(x.status,200);r=x.item;const cid=r.consultores[0].id;assert.equal(r.envolvidos.length,2);assert.equal(r.consultores[0].rhId,undefined);
 assert.equal((await t.call({action:'convidar',id:r.id,versao:r.versao,consultorId:'outro-processo',dias:2})).status,422);
 x=await t.call({action:'convidar',id:r.id,versao:r.versao,consultorId:cid,dias:2});assert.equal(x.status,200);const token=x.convite;r=x.item;
 let g=await t.call({action:'obter'},false,token);assert.equal(g.item.consultores,undefined);assert.ok(!JSON.stringify(g).includes('consultora@example.test'));
 assert.equal((await t.call({action:'consultor',nome:'Novo'},false,token)).status,403);
 g=await t.call({action:'registro',versao:r.versao,tipo:'acao',titulo:'Padronizar conferência',dataAcao:'2026-10-08',texto:'Treinamos a equipe',implantacao:{situacao:'em_implantacao',como:'Piloto'}},false,token);assert.equal(g.status,200);const id=g.item.registros[0].id;assert.equal(g.item.registros[0].podeAtualizar,true);
 assert.equal((await t.call({action:'implantacao',versao:g.item.versao,registroId:id,implantacao:{situacao:'implantada'}},false,token)).status,422);
 g=await t.call({action:'implantacao',versao:g.item.versao,registroId:id,implantacao:{situacao:'implantada',como:'Checklist adotado pela equipe',data:'2026-10-08',resultado:'Conferência passou a ser registrada'}},false,token);assert.equal(g.status,200);assert.equal(g.item.registros[0].implantacoes.length,2);assert.equal(g.item.registros[0].implantacao.resultado,'Conferência passou a ser registrada');assert.equal(g.item.etapas[0].situacao,'pendente');
 const copia=g.item.versao;r=(await t.call({action:'obter',id:r.id})).item;
 x=await t.call({action:'convidar',id:r.id,versao:r.versao,nome:'Outro consultor',dias:2});const token2=x.convite;r=x.item;
 assert.equal((await t.call({action:'implantacao',versao:r.versao,registroId:id,implantacao:{situacao:'nao_iniciada'}},false,token2)).status,403);
 assert.equal((await t.call({action:'implantacao',versao:copia,registroId:id,implantacao:{situacao:'nao_iniciada'}},false,token)).status,409);
 t.session(membro);assert.equal((await t.call({action:'consultor',id:r.id,versao:r.versao,nome:'Invasão'})).status,403);
});

test('consultoria planeja etapas, registra início e término e mantém validação interna',async()=>{
 const t=setup();let r=(await t.call({action:'salvar',item:item()})).item;const c=await t.call({action:'convidar',id:r.id,versao:r.versao,nome:'Consultor planejamento',dias:2});r=c.item;const token=c.convite;
 const dados={titulo:'Implantar conferência',descricao:'Treinar e acompanhar',inicioPrevisto:'2026-01-01',prazo:'2026-01-10',inicioReal:'2026-01-02',fimReal:'',progresso:40,situacao:'execucao',dependeDe:[],nota:'Piloto',responsavelRhId:'rh-forjado'};
 let g=await t.call({action:'planejarEtapa',versao:r.versao,...dados},false,token);assert.equal(g.status,200);let etapa=g.item.etapas.at(-1);assert.equal(etapa.progresso,40);assert.equal(etapa.responsavelRhId,undefined);assert.equal(t.rows.get(r.id).etapas.at(-1).responsavelRhId,r.responsavelRhId);
 for(const alteracao of [{fimReal:'2025-01-01',situacao:'validacao'},{inicioReal:'2099-01-01'},{progresso:101},{situacao:'concluida',fimReal:'2026-01-03'},{situacao:'validacao',fimReal:''},{dependeDe:[etapa.id]},{dependeDe:['outra-consultoria']}])assert.equal((await t.call({action:'planejarEtapa',versao:g.item.versao,etapaId:etapa.id,...dados,...alteracao},false,token)).status,422);
 g=await t.call({action:'planejarEtapa',versao:g.item.versao,etapaId:etapa.id,...dados,situacao:'validacao',fimReal:'2026-01-08'},false,token);assert.equal(g.status,200);assert.equal(g.item.etapas.at(-1).progresso,100);assert.equal(g.item.etapas.at(-1).situacao,'validacao');
 let interno=(await t.call({action:'obter',id:r.id})).item;const fim=interno.etapas.at(-1).fimReal;
 interno=(await t.call({action:'salvar',item:{...interno,versaoAnterior:interno.versao,titulo:'Ajuste interno'}})).item;assert.equal(interno.etapas.at(-1).fimReal,fim);
 const agenda=await t.call({action:'agenda',mes:'2026-01'});assert.ok(agenda.eventos.some(e=>e.etapaId===etapa.id&&e.data==='2026-01-10'));
 const final=await t.call({action:'planejarEtapa',id:r.id,versao:interno.versao,etapaId:etapa.id,...dados,situacao:'concluida',fimReal:'2026-01-08'});assert.equal(final.status,200);assert.equal(final.item.etapas.at(-1).situacao,'concluida');
 assert.equal((await t.call({action:'planejarEtapa',versao:final.item.versao,etapaId:etapa.id,...dados},false,token)).status,403);
});

test('avaliação de qualidade é interna, mantém histórico e não altera conclusão ou progresso',async()=>{
 const t=setup();let r=(await t.call({action:'salvar',item:item()})).item;
 const c=await t.call({action:'convidar',id:r.id,versao:r.versao,nome:'Consultor',dias:2});r=c.item;
 const dados={action:'avaliarEtapa',id:r.id,versao:r.versao,etapaId:'e1',pontuacao:8,comentario:'Bom, melhorar a documentação.'};
 assert.equal((await t.call(dados,false,c.convite)).status,403);
 t.session(membro);assert.equal((await t.call(dados)).status,403);t.session({sub:'ana',nome:'Ana',perms:['demandas']});
 for(const pontuacao of [-1,11,'8',null])assert.equal((await t.call({...dados,pontuacao})).status,422);
 assert.equal((await t.call({...dados,comentario:''})).status,422);
 r=(await t.call(dados)).item;assert.equal(r.etapas[0].avaliacoes.at(-1).pontuacao,8);assert.equal(r.etapas[0].situacao,'pendente');
 assert.equal((await t.call(dados)).status,409);
 r=(await t.call({...dados,versao:r.versao,pontuacao:9.5,comentario:'Documentação validada.'})).item;
 r=(await t.call({action:'salvar',item:{...r,versaoAnterior:r.versao,etapas:r.etapas.map(e=>({...e,avaliacoes:[]}))}})).item;
 assert.equal(r.etapas[0].avaliacoes.length,2);
 const g=await t.call({action:'obter'},false,c.convite);assert.equal(g.item.etapas[0].avaliacoes.at(-1).pontuacao,9.5);
 r=(await t.call({...r.etapas[0],action:'planejarEtapa',id:r.id,versao:r.versao,etapaId:'e1',avaliacoes:[]})).item;assert.equal(r.etapas[0].avaliacoes.length,2);
});
