import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),{buildSync}=createRequire(require.resolve('vite'))('esbuild');
const source=readFileSync(new URL('../supabase/functions/painel-reunioes/index.ts',import.meta.url),'utf8').replace(/^import.*createClient.*\n/m,'const createClient=globalThis.createClient;\n').replace(/^import.*verificarJwt.*\n/m,'const {verificarJwt,crachaRevogado}=globalThis;\n');
const code=buildSync({stdin:{contents:source,loader:'ts',resolveDir:fileURLToPath(new URL('../supabase/functions/painel-reunioes/',import.meta.url))},bundle:true,write:false,format:'iife',platform:'node'}).outputFiles[0].text;
function setup(){let handler,session={sub:'ana',nome:'Ana',perms:['reunioes']},revoked=false,conflict=false;const rows=new Map(),files=new Map();let uploads=0;
 const sb={from(){let id,start=0,end=499;const q={select(){return q},eq(k,v){if(k==='id')id=v;return q},order(){return q},range(a,b){start=a;end=b;return Promise.resolve({data:[...rows].slice(start,end+1).map(([id,registro])=>({id,registro}))})},maybeSingle(){return Promise.resolve({data:rows.has(id)?{registro:rows.get(id)}:null})}};return q},async rpc(n,p){if(conflict||JSON.stringify(rows.get(p.p_id)||null)!==JSON.stringify(p.p_anterior))return {error:{code:'40001'}};rows.set(p.p_id,p.p_registro);return {}},storage:{from(){return {async upload(k,v){uploads++;files.set(k,v);return {}},async remove(ks){ks.forEach(k=>files.delete(k));return {}},async createSignedUrl(k){return {data:{signedUrl:'https://private.example/'+k}}}}}}};
 vm.runInNewContext(code,{createClient:()=>sb,verificarJwt:async()=>session,crachaRevogado:async()=>revoked,Deno:{env:{get:()=> 'test'},serve:fn=>handler=fn},Response,Request,crypto,atob,Uint8Array,console});
 return {rows,files,get uploads(){return uploads},session:s=>session=s,revoke:()=>revoked=true,conflict:()=>conflict=true,async call(body,auth=true){const r=await handler(new Request('http://local',{method:'POST',headers:auth?{authorization:'Bearer test'}:{},body:JSON.stringify(body)}));return {status:r.status,...await r.json()}}};}
const item=()=>({id:'r1',titulo:'Reunião',tipo:'reuniao',situacao:'agendado',data:'2026-10-06',inicio:'09:00',fim:'10:00',responsavel:'Ana',participantes:[],decisoes:[]});
test('servidor exige sessão e módulo para consultar ou alterar',async()=>{const t=setup();assert.equal((await t.call({action:'listar'},false)).status,401);t.session({sub:'bia',perms:['agenda']});assert.equal((await t.call({action:'listar'})).status,403);t.session({sub:'ana',perms:['reunioes']});t.revoke();assert.equal((await t.call({action:'listar'})).status,401);});
test('ciclo persistido: cadastro, edição, ata, registros e anexo privado',async()=>{const t=setup();let r=(await t.call({action:'salvar',item:item()})).item;assert.equal(r.criadoPor,'ana');assert.equal((await t.call({action:'listar'})).itens.length,1);r=(await t.call({action:'salvar',item:{...r,ata:'Ata aprovada',versaoAnterior:r.versao}})).item;assert.equal(r.ata,'Ata aprovada');r=(await t.call({action:'registro',id:r.id,versao:r.versao,texto:'Ação concluída'})).item;assert.equal(r.registros[0].nome,'Ana');r=(await t.call({action:'anexar',id:r.id,versao:r.versao,nome:'ata.pdf',mime:'application/pdf',base64:btoa('%PDF-test')})).item;assert.equal(t.files.size,1);assert.equal((await t.call({action:'arquivo',id:r.id,arquivoId:r.anexos[0].id})).status,200);assert.equal((await t.call({action:'arquivo',id:r.id,arquivoId:'outra'})).status,404);});
test('outro leitor não altera ata nem anexa; conflito não sobrescreve e limpa upload',async()=>{const t=setup(),r=(await t.call({action:'salvar',item:item()})).item;t.session({sub:'bia',perms:['reunioes']});assert.equal((await t.call({action:'listar'})).itens[0].podeEditar,false);assert.equal((await t.call({action:'registro',id:r.id,versao:r.versao,texto:'x'})).status,403);assert.equal((await t.call({action:'salvar',item:{...r,versaoAnterior:r.versao}})).status,403);t.session({sub:'ana',perms:['reunioes']});t.conflict();assert.equal((await t.call({action:'anexar',id:r.id,versao:r.versao,nome:'ata.pdf',mime:'application/pdf',base64:btoa('%PDF-test')})).status,409);assert.equal(t.files.size,0);assert.equal(t.rows.get(r.id).anexos.length,0);});
test('paginação recupera mais de 500 encontros; corpo inválido retorna 400',async()=>{const t=setup();for(let i=0;i<501;i++)t.rows.set('r'+i,{...item(),id:'r'+i,criadoPor:'ana'});assert.equal((await t.call({action:'listar'})).itens.length,501);assert.equal((await t.call(null)).status,400);});
