import {useEffect,useId,useMemo,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Plus,RefreshCw,ArrowUpRight,Target,Search,Check,Settings,ChevronRight,X,CalendarDays,CalendarCheck,Lightbulb,TrendingUp,FileText,Clock,AlertCircle,SlidersHorizontal,WalletCards} from 'lucide-react';
import {BotaoPDF} from '../components/ui.jsx';
import {chamarComercial} from '../services/comercial.js';
import {ymdLocal} from '../lib/format.js';
import {podeAbrir} from '../lib/sessao.js';
import ConsultaClientes from '../components/ConsultaClientes.jsx';
import {clienteCorresponde} from '../../supabase/functions/_shared/consulta-clientes.mjs';
import {resumoFinanceiroComercial} from '../lib/calc/financeiroComercial.js';
import ComercialDicas from '../components/ComercialDicas.jsx';
import './comercial.css';
const ABAS=[['painel','Meu painel'],['orcamentos','Orçamentos'],['vendas','Minhas vendas'],['clientes','Meus clientes'],['produtos','Produtos e soluções'],['metas','Minhas metas']];
const brl=c=>c==null?'Não disponível':(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const valor=v=>v==null?null:Math.round(v*100);
const colunasPedidos=['O.S.','Cliente','Sinal pago','Recebido','Saldo','Líquido','Cadastro','Vendedora histórica'];
const data=d=>d?d.slice(0,10).split('-').reverse().join('/'):'Não informado';
const hora=d=>/^\d{4}-\d{2}-\d{2}$/.test(d||'')?data(d):d?new Date(d).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Não disponível';
const status=o=>o.situacaoLocal?`Encerrado como ${o.situacaoLocal==='ganho'?'ganho':'perdido'} no Painel`:({aberto:'Em aberto',ganho:o.statusErp&&o.statusErp.trim().toUpperCase()!=='APROVADO'?`Convertido em O.S. · ${o.statusErp}`:'Aprovado',perdido:'Perdido / cancelado',conferir:'A conferir no Mubisys'}[o.situacao]||o.statusErp||'A conferir');
function Dialogo({titulo,children,fechar}){
 const tituloId=useId(),ref=useRef();useEffect(()=>{const anterior=document.activeElement;ref.current.showModal();return ()=>anterior?.focus();},[]);
 return <dialog ref={ref} aria-labelledby={tituloId} className="com-dialog" onCancel={e=>{e.preventDefault();fechar();}}><header><h2 id={tituloId}>{titulo}</h2><button aria-label="Fechar" className="btn-ghost" onClick={fechar}><X size={20}/></button></header><div className="com-dialog-body">{children}</div></dialog>;
}
function Lista({colunas,linhas,vazio='Nenhum registro neste recorte.'}){
 return linhas.length?<div className={`com-table-wrap ${colunas===colunasPedidos?'com-order-list':''}`}><table className="com-table"><thead><tr>{colunas.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{linhas.map((l,i)=><tr key={l.id||i}>{l.cells.map((c,j)=><td key={j} data-label={colunas===colunasPedidos?colunas[j]:undefined}>{c}</td>)}</tr>)}</tbody></table></div>:<div className="com-empty">{vazio}</div>;
}
function Grafico({linhas,abrir,titulo}){
 const max=Math.max(1,...linhas.map(l=>l.centavos));return <section className="com-card"><h2>{titulo}</h2>{!linhas.length?<p className="com-muted">Sem dados suficientes no período.</p>:<div className="com-bars">{linhas.map(l=><button key={l.mes} onClick={()=>abrir(l)} aria-label={`${l.mes}: ${brl(l.centavos)}, abrir pedidos`}><span>{l.mes.split('-').reverse().join('/')}</span><span className="com-track"><i style={{width:`${Math.max(1,l.centavos/max*100)}%`}}/></span><b>{brl(l.centavos)}</b></button>)}</div>}</section>;
}
function AcaoForm({inicial,dados,filtro,salvo,fechar}){
 const [a,setA]=useState(()=>({clienteId:inicial?.clienteId||inicial?.idCliente||'',orcamentoId:'',vendedorId:dados.escopo.vendedorId||filtro.vendedor||'',descricao:'',data:ymdLocal(new Date()),nota:'',pendencias:'',decisao:'',status:'pendente',...inicial,id:inicial?.versao?inicial.id:crypto.randomUUID()}));
 const [erro,setErro]=useState(''),[salvando,setSalvando]=useState(false);const set=(k,v)=>setA(x=>({...x,[k]:v}));
 async function enviar(e){e.preventDefault();setSalvando(true);setErro('');try{await chamarComercial('salvarAcao',{acao:a,versao:inicial?.versao??null,filtro});salvo();}catch(e){setErro(e.message);}finally{setSalvando(false);}}
 return <Dialogo titulo={inicial?.versao?'Editar próxima ação':'Combinar o próximo passo'} fechar={fechar}><form onSubmit={enviar} className="com-form">
 <p className="com-muted">Registro do Painel, vinculado ao cliente e ao orçamento do Mubisys. Nenhuma mensagem é enviada automaticamente.</p>
 <label>Cliente<select required value={a.clienteId} onChange={e=>setA(x=>({...x,clienteId:e.target.value,orcamentoId:''}))}><option value="">Selecione</option>{dados.base.clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label>
 <label>Orçamento<select value={a.orcamentoId} onChange={e=>set('orcamentoId',e.target.value)}><option value="">Contato sem orçamento</option>{dados.base.orcamentos.filter(o=>String(o.clienteId)===String(a.clienteId)).map(o=><option key={o.id} value={o.id}>#{o.numero} · {brl(valor(o.valor))}</option>)}</select></label>
 <div className="com-form-grid"><label>Responsável<select required value={a.vendedorId} onChange={e=>set('vendedorId',e.target.value)} disabled={!dados.escopo.gestor}><option value="">Selecione</option>{dados.catalogo.vendedores.map(v=><option key={v.id} value={v.id}>{v.nome}</option>)}</select></label><label>Data do retorno<input type="date" required value={a.data} onChange={e=>set('data',e.target.value)}/></label></div>
 <label>Próxima ação<input required maxLength={500} value={a.descricao} onChange={e=>set('descricao',e.target.value)} placeholder="Ex.: confirmar medidas com o cliente"/></label>
 <label>Registro do atendimento<textarea maxLength={3000} value={a.nota} onChange={e=>set('nota',e.target.value)} placeholder="O que foi conversado e combinado"/></label>
 <div className="com-form-grid"><label>Previsão de decisão<input type="date" value={a.decisao||''} onChange={e=>set('decisao',e.target.value)}/></label><label>Situação<select value={a.status} onChange={e=>set('status',e.target.value)}><option value="pendente">Pendente</option><option value="concluida">Concluída</option></select></label></div>
 <label>O que falta para fechar<textarea maxLength={1000} value={a.pendencias} onChange={e=>set('pendencias',e.target.value)} placeholder="Informações, medidas, arte ou revisão"/></label>
 {erro&&<p role="alert" className="com-alert">{erro}</p>}<footer><button type="button" className="btn-outline" onClick={fechar}>Cancelar</button><button className="btn-primary" disabled={salvando}>{salvando?'Salvando…':'Salvar próxima ação'}</button></footer>
 </form></Dialogo>;
}
function ConfigForm({dados,filtro,salvo,fechar}){
 const [c,setC]=useState(()=>({diasSemResposta:7,diasVencimento:3,diasReativacao:90,...dados.config})),[erro,setErro]=useState(''),[salvando,setSalvando]=useState(false);
 const [vinculos,setVinculos]=useState(Object.entries(c.vinculos||{}).map(([usuario,vendedor])=>({usuario,vendedor}))),[equipes,setEquipes]=useState(c.equipes||[]);
 async function enviar(e){e.preventDefault();setErro('');setSalvando(true);try{if(vinculos.some(v=>!v.usuario.trim()||!v.vendedor)||new Set(vinculos.map(v=>v.usuario.trim())).size!==vinculos.length)throw new Error('Confira os usuários: não deixe vínculo vazio nem usuário repetido.');await chamarComercial('configurar',{config:{...c,vinculos:Object.fromEntries(vinculos.map(v=>[v.usuario.trim(),v.vendedor])),equipes},anterior:Object.keys(dados.config).length?dados.config:null,filtro});salvo();}catch(e){setErro(e.message);}finally{setSalvando(false);}}
 return <Dialogo titulo="Regras da rotina comercial" fechar={fechar}><form className="com-form" onSubmit={enviar}><p className="com-muted">Parâmetros da direção. Aplicados de forma igual nos alertas de todas as vendedoras.</p>{[['diasSemResposta','Alertar proposta sem resposta após (dias)'],['diasVencimento','Alertar antes da validade (dias)'],['diasReativacao','Referência para reativação (dias)']].map(([k,l])=><label key={k}>{l}<input type="number" min="0" max="730" required value={c[k]} onChange={e=>setC({...c,[k]:Number(e.target.value)})}/></label>)}
 <fieldset><legend>Calendário comercial</legend><label><input type="checkbox" checked={c.calendario?.configurado||false} onChange={e=>setC({...c,calendario:{diasSemana:[1,2,3,4,5],feriados:[],...c.calendario,configurado:e.target.checked}})}/> Calendário conferido pela direção</label><div className="com-days">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((s,i)=><label key={s}><input type="checkbox" checked={c.calendario?.diasSemana?.includes(i)||false} onChange={e=>setC({...c,calendario:{...c.calendario,diasSemana:e.target.checked?[...(c.calendario?.diasSemana||[]),i]:(c.calendario?.diasSemana||[]).filter(x=>x!==i)}})}/>{s}</label>)}</div><label>Feriados (uma data AAAA-MM-DD por linha)<textarea value={(c.calendario?.feriados||[]).join('\n')} onChange={e=>setC({...c,calendario:{...c.calendario,feriados:e.target.value.split('\n').filter(Boolean)}})}/></label></fieldset>
 <fieldset><legend>Vínculos das vendedoras</legend><p className="com-muted">Associe o usuário de acesso ao cadastro correto do Mubisys. Vínculos já identificados por nome completo continuam funcionando.</p>{vinculos.map((v,i)=><div key={i} className="com-binding"><label>Usuário do Painel<input required value={v.usuario} onChange={e=>setVinculos(xs=>xs.map((x,j)=>j===i?{...x,usuario:e.target.value}:x))}/></label><label>Vendedora no Mubisys<select required value={v.vendedor} onChange={e=>setVinculos(xs=>xs.map((x,j)=>j===i?{...x,vendedor:e.target.value}:x))}><option value="">Selecione</option>{dados.catalogo.vendedores.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><button type="button" className="btn-outline" onClick={()=>setVinculos(xs=>xs.filter((_,j)=>j!==i))}>Remover vínculo</button></div>)}<button type="button" className="btn-outline" onClick={()=>setVinculos(xs=>[...xs,{usuario:'',vendedor:''}])}>Adicionar vínculo</button></fieldset>
 <fieldset><legend>Equipes comerciais</legend>{equipes.map((eq,i)=><fieldset key={eq.id}><label>Nome da equipe<input required value={eq.nome} onChange={e=>setEquipes(xs=>xs.map((x,j)=>j===i?{...x,nome:e.target.value}:x))}/></label>{dados.catalogo.vendedores.map(v=><label key={v.id}><input type="checkbox" checked={eq.vendedores.includes(v.id)} onChange={e=>setEquipes(xs=>xs.map((x,j)=>j===i?{...x,vendedores:e.target.checked?[...x.vendedores,v.id]:x.vendedores.filter(id=>id!==v.id)}:x))}/>{v.nome}</label>)}<button type="button" className="btn-outline" onClick={()=>setEquipes(xs=>xs.filter((_,j)=>j!==i))}>Remover equipe</button></fieldset>)}<button type="button" className="btn-outline" onClick={()=>setEquipes(xs=>[...xs,{id:crypto.randomUUID(),nome:'',vendedores:[]}])}>Adicionar equipe</button></fieldset>
 {erro&&<p role="alert" className="com-alert">{erro}</p>}<button className="btn-primary" disabled={salvando}>{salvando?'Salvando…':'Salvar regras'}</button></form></Dialogo>;
}
function MetaForm({dados,filtro,salvo,fechar}){
 const [vendedorId,setVendedor]=useState(filtro.vendedor||''),[mes,setMes]=useState(filtro.de.slice(0,7)),[valorMeta,setValor]=useState(''),[erro,setErro]=useState(''),[salvando,setSalvando]=useState(false);
 const anterior=(dados.metas||[]).find(m=>m.vendedorId===vendedorId&&m.mes===mes);
 useEffect(()=>setValor(anterior?.valor==null?'':String(anterior.valor)),[anterior,vendedorId,mes]);
 async function enviar(e){e.preventDefault();setErro('');setSalvando(true);try{await chamarComercial('salvarMeta',{meta:{vendedorId,mes,valor:valorMeta},anterior:anterior||null,filtro});salvo();}catch(e){setErro(e.message);}finally{setSalvando(false);}}
 return <Dialogo titulo="Cadastrar meta mensal" fechar={fechar}><form className="com-form" onSubmit={enviar}>
 <p>Esta meta é informada pela direção no Painel. O realizado considera o valor líquido das O.S. normais, pela data de cadastro no Mubisys.</p>
 <label>Vendedora<select required value={vendedorId} onChange={e=>setVendedor(e.target.value)}><option value="">Selecione</option>{dados.catalogo.vendedores.map(v=><option key={v.id} value={v.id}>{v.nome}</option>)}</select></label>
 <div className="com-form-grid"><label>Mês da meta<input type="month" required value={mes} onChange={e=>setMes(e.target.value)}/></label><label>Meta em reais<input type="number" required min="0" max="10000000000" step="0.01" value={valorMeta} onChange={e=>setValor(e.target.value)} placeholder="Ex.: 100000,00"/></label></div>
 <p className="com-muted">Metas individuais somam o consolidado. Não há distribuição automática da meta da empresa.</p>
 {anterior&&<p className="com-muted">Última alteração: {hora(anterior.atualizadoEm)} · {anterior.atualizadoPor}.</p>}
 {erro&&<p role="alert" className="com-alert">{erro}</p>}
 <footer><button type="button" className="btn-outline" onClick={fechar}>Cancelar</button><button className="btn-primary" disabled={salvando}>{salvando?'Salvando…':'Salvar meta'}</button></footer>
 </form></Dialogo>;
}
function MetaResumo({r,dados}){
 return <><h3>{r.meta.mensagem}</h3>{r.meta.valor!=null&&<div className="com-ticket"><span>{brl(r.valor)} realizados</span><b>Meta {brl(r.meta.valor)}</b></div>}
 {r.meta.percentual!=null&&<><progress max="100" value={Math.min(100,r.meta.percentual)} aria-label="Percentual da meta atingido"/><p><b>{r.meta.percentual.toLocaleString('pt-BR',{maximumFractionDigits:1})}% atingido</b> · faltam {brl(r.meta.falta)}</p></>}
 <p className="com-muted">{r.meta.diasUteis!=null?`${r.meta.diasUteis} dias úteis restantes${r.meta.porDia!=null?` · ${brl(r.meta.porDia)} por dia como referência de planejamento`:''}`:r.meta.valor!=null?'Configure o calendário comercial para calcular os dias úteis e a referência diária.':'A direção pode informar a meta individual na aba Minhas metas.'}</p>
 {dados.base.meta?.origem==='painel'&&<p className="com-muted">Meta cadastrada no Painel · soma das metas individuais deste mês.</p>}</>;
}
export default function Comercial({sessao}){
 const [params,setParams]=useSearchParams(),hoje=ymdLocal(new Date());
 const fimMes=new Date(Number(hoje.slice(0,4)),Number(hoje.slice(5,7)),0).getDate();
 const filtro=useMemo(()=>({de:params.get('de')||hoje.slice(0,7)+'-01',ate:params.get('ate')||hoje.slice(0,7)+'-'+fimMes,vendedor:params.get('vendedor')||'',equipe:params.get('equipe')||'',comparacao:params.get('comparacao')||'equivalente'}),[params,hoje,fimMes]);
 const [filtrosAbertos,setFiltrosAbertos]=useState(()=>typeof window!=='undefined'&&window.matchMedia('(min-width:1250px)').matches);
 useEffect(()=>{const media=window.matchMedia('(min-width:1250px)'),mudar=()=>setFiltrosAbertos(media.matches);media.addEventListener('change',mudar);return()=>media.removeEventListener('change',mudar);},[]);
 const chave=JSON.stringify(filtro),aba=ABAS.some(a=>a[0]===params.get('aba'))?params.get('aba'):'painel';
 const [carga,setCarga]=useState(null),[erro,setErro]=useState(''),[carregando,setCarregando]=useState(true),[revisao,setRevisao]=useState(0),[modal,setModal]=useState(null),[busca,setBusca]=useState(''),[situacao,setSituacao]=useState('');
 const dados=carga?.chave===chave?carga.dados:null,r=dados?.relatorio;
 const financeiro=useMemo(()=>resumoFinanceiroComercial(r?.vendas||[],dados?.financeiro,hoje),[r,dados,hoje]);
 const alterar=patch=>{const p=new URLSearchParams(params);Object.entries(patch).forEach(([k,v])=>v?p.set(k,v):p.delete(k));setParams(p);setModal(null);};
 useEffect(()=>{const ctl=new AbortController();setCarregando(true);setErro('');chamarComercial('painel',{filtro:JSON.parse(chave)},ctl.signal).then(d=>{if(!ctl.signal.aborted)setCarga({chave,dados:d});}).catch(e=>{if(!ctl.signal.aborted)setErro(e.message);}).finally(()=>{if(!ctl.signal.aborted)setCarregando(false);});return()=>ctl.abort();},[chave,revisao]);
 useEffect(()=>{setBusca('');setSituacao('');},[aba]);
 function datasPeriodo(tipo){const d=new Date(hoje+'T12:00:00');if(tipo==='anterior')d.setMonth(d.getMonth()-1,1);const ano=d.getFullYear(),mes=String(d.getMonth()+1).padStart(2,'0');return {de:tipo==='ano'?`${ano}-01-01`:`${ano}-${mes}-01`,ate:tipo==='ano'?`${ano}-12-31`:`${ano}-${mes}-${new Date(ano,d.getMonth()+1,0).getDate()}`};}
 const periodo=tipo=>alterar(datasPeriodo(tipo));
 const periodoAtivo=tipo=>{const d=datasPeriodo(tipo);return d.de===filtro.de&&d.ate===filtro.ate;};
 const abrirAcao=a=>setModal({tipo:a?.origem==='mesa'?'legado':'acao',a});
 const renovar=()=>{setModal(null);setRevisao(n=>n+1);};
 const detalhe=(titulo,itens,tipo,periodo=filtro)=>setModal({tipo:'lista',titulo,itens,conteudo:tipo,periodo});
 const filtrar=xs=>xs.filter(x=>`${x.cliente||x.nome||''} ${x.numero||''} ${x.vendedorNome||x.vendedor||''} ${x.trabalho||''} ${x.categoria||''} ${x.documento||''}`.toLocaleLowerCase().includes(busca.toLocaleLowerCase()));
 function linhasOs(xs){return xs.map(o=>{
  const sinal=o.sinalPago==null||o.sinalPago===''?null:Number(o.sinalPago);
  const f=financeiro[String(o.numero)];
  return {id:o.id,cells:[<b key="n">#{o.numero}</b>,o.cliente,<span key="s" className={`com-signal ${sinal>0?'is-paid':''}`}>{!Number.isFinite(sinal)||sinal==null?'Não informado':sinal===0?'Sem sinal':brl(valor(sinal))}</span>,f?brl(valor(f.recebido)):'A conferir',f?brl(valor(f.saldo)):'A conferir',brl(o.centavos??valor(o.valor)),data(o.data),o.vendedor||'Não informado']};
 });}
 function abrirCliente(c){setModal({tipo:'cliente',c});}
 function abrirOrc(o){setModal({tipo:'orcamento',o});}
 const clientes=r?.clientes||[];
 const calendario=['calendario-empresa','agenda','reunioes'].find(m=>podeAbrir(m,sessao));
 const retornoComercial={origemComercial:true,filtrosComercial:params.toString()};
 return <div className="comercial">
 <header className="com-header"><div><p className="com-eyebrow">SEU ESPAÇO DE VENDAS</p><h1>Comercial</h1><p className="com-muted">Bons negócios começam com um bom atendimento.</p></div><div className="com-header-actions sem-impressao"><button className="btn-outline" onClick={()=>setRevisao(n=>n+1)} disabled={carregando}><RefreshCw size={16}/><span>Atualizar</span></button><button className="btn-primary" onClick={()=>setModal({tipo:'novo'})}><Plus size={18}/>Novo orçamento</button></div></header>
 <nav className="com-shortcuts sem-impressao" aria-label="Atalhos da rotina comercial">
 {calendario&&<Link className="com-shortcut com-shortcut-calendar" state={retornoComercial} to={`/${calendario}?mes=${filtro.de.slice(0,7)}`}><CalendarDays size={18} aria-hidden="true"/><span>Calendário</span><ChevronRight size={14} aria-hidden="true"/></Link>}
 {podeAbrir('compromissos',sessao)&&<Link className="com-shortcut com-shortcut-appointments" state={retornoComercial} to="/compromissos"><CalendarCheck size={18} aria-hidden="true"/><span>Compromissos</span><ChevronRight size={14} aria-hidden="true"/></Link>}
 {podeAbrir('contas-atrasadas',sessao)&&<Link className="com-shortcut com-shortcut-payments" state={retornoComercial} to="/contas-atrasadas"><WalletCards size={18} aria-hidden="true"/><span>Pagamentos atrasados</span><ChevronRight size={14} aria-hidden="true"/></Link>}
 <button className="com-shortcut com-shortcut-tips" onClick={()=>setModal({tipo:'dicas'})}><Lightbulb size={18} aria-hidden="true"/><span>Dicas de produtos</span><ChevronRight size={14} aria-hidden="true"/></button>
 </nav>
 <nav className="com-tabs sem-impressao" aria-label="Área Comercial">{ABAS.map(([id,nome])=><button key={id} aria-current={aba===id?'page':undefined} onClick={()=>alterar({aba:id})}>{nome}</button>)}</nav>
 <details className="com-filter-panel sem-impressao" open={filtrosAbertos} onToggle={e=>setFiltrosAbertos(e.currentTarget.open)}><summary><SlidersHorizontal size={16} aria-hidden="true"/><b>Período e filtros</b><span>{data(filtro.de)} a {data(filtro.ate)}</span><ChevronRight size={15} aria-hidden="true"/></summary><section className="com-filters" aria-label="Filtros do Comercial"><div className="com-presets"><button aria-pressed={periodoAtivo('atual')} onClick={()=>periodo('atual')}>Mês atual</button><button aria-pressed={periodoAtivo('anterior')} onClick={()=>periodo('anterior')}>Mês anterior</button><button aria-pressed={periodoAtivo('ano')} onClick={()=>periodo('ano')}>Ano</button></div><label>De<input aria-label="Data inicial" type="date" value={filtro.de} onChange={e=>alterar({de:e.target.value})}/></label><label>Até<input aria-label="Data final" type="date" value={filtro.ate} onChange={e=>alterar({ate:e.target.value})}/></label>{dados?.escopo.gestor&&<><label>Vendedora<select value={filtro.vendedor} onChange={e=>alterar({vendedor:e.target.value})}><option value="">Toda a equipe</option>{dados.catalogo.vendedores.map(v=><option key={v.id} value={v.id}>{v.nome}</option>)}</select></label><label>Equipe<select value={filtro.equipe} onChange={e=>alterar({equipe:e.target.value})}><option value="">Todas</option>{(dados.config.equipes||[]).map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></label></>}<BotaoPDF titulo="Salvar esta visão e seus filtros em PDF"/></section></details>
 <div className="com-context"><span>{data(filtro.de)} a {data(filtro.ate)} · {dados?.catalogo.vendedores.find(v=>v.id===(filtro.vendedor||dados.escopo.vendedorId))?.nome||'Visão consolidada'}{filtro.equipe?` · ${dados?.config.equipes?.find(e=>e.id===filtro.equipe)?.nome||'Equipe selecionada'}`:''}</span><span>Atualizado: {hora(dados?.atualizadoEm)}</span></div>
 {erro&&<div role="alert" className="com-alert">{erro} {dados?'Últimos dados válidos mantidos abaixo.':''}<button onClick={()=>setRevisao(n=>n+1)}>Tentar novamente</button></div>}
 {carregando&&<p role="status">Conferindo suas informações…</p>}
 {dados&&<>
 {!r.completo&&<div className="com-alert"><b>Apuração parcial.</b> {r.incompletas?`${r.incompletas} O.S. sem tipo ou valor confirmado ficaram fora do realizado.`:'A cobertura deste período ainda precisa ser confirmada.'} Os números abaixo representam somente os registros verificáveis.</div>}
 {!r.orcamentosCompletos&&aba==='orcamentos'&&params.get('visaoOrc')==='periodo'&&<div className="com-alert">O histórico de orçamentos não cobre todo este período. A lista mostra os registros disponíveis; o total de propostas fica indisponível.</div>}
 {aba==='painel'&&<>
 <div className="com-kpis">{[
 ['Vendas no período',brl(r.valor),`${r.pedidos} pedidos considerados`,'sales',TrendingUp,()=>detalhe('Vendas que compõem o total',r.vendas,'vendas')],
 ['Orçamentos em aberto',brl(r.valorAbertoOperacional),`${r.abertasOperacionais.length} propostas disponíveis · inclui meses anteriores`,'quotes',FileText,()=>detalhe('Orçamentos em aberto',r.abertasOperacionais,'orcamentos',{rotina:true})],
 ['Retornos de hoje',r.hojeA.length,'Conferir atendimentos','today',Clock,()=>detalhe('Retornos de hoje',r.hojeA,'acoes',{rotina:true})],
 ['Retornos atrasados',r.atrasadas.length,r.atrasadas.length?'Precisam de atenção':'Nenhum retorno atrasado',r.atrasadas.length?'late':'clear',AlertCircle,()=>detalhe('Retornos atrasados',r.atrasadas,'acoes',{rotina:true})]
 ].map(([l,v,s,tom,Icone,fn])=><button key={l} className={`com-kpi com-kpi-${tom}`} onClick={fn}><span><Icone size={17} aria-hidden="true"/>{l}<ArrowUpRight size={14} aria-hidden="true"/></span><strong>{v}</strong><small>{s}</small></button>)}</div>
 <div className="com-workspace">
 <Prioridades r={r} dados={dados} abrirAcao={abrirAcao} nova={()=>setModal({tipo:'acao'})}/>
 <aside className="com-workspace-side" aria-label="Meta e apoio à venda"><section className="com-card com-goal"><div className="com-section-head"><h2><Target size={19}/> Meta do período</h2><button className="com-link" onClick={()=>alterar({aba:'metas'})}>Ver meta <ChevronRight size={15}/></button></div><MetaResumo r={r} dados={dados}/><div className="com-rhythm"><span>Ticket médio <b>{brl(r.ticket)}</b></span><button className="com-link" onClick={()=>alterar({aba:'vendas'})}>Ver comparativos <ArrowUpRight size={14}/></button></div></section>
 <ComercialDicas compacto onAbrir={()=>setModal({tipo:'dicas'})}/>
 </aside></div>
 </>}
 {aba==='orcamentos'&&<OrcamentosComerciais r={r} filtro={filtro} dados={dados} modo={params.get('visaoOrc')||'trabalho'} alterar={alterar} busca={busca} setBusca={setBusca} situacao={situacao} setSituacao={setSituacao} filtrar={filtrar} abrirOrc={abrirOrc}/>}
   {aba==='vendas'&&<div className="com-vendas">
   <div className="com-kpis"><div className="com-kpi"><span>Valor líquido</span><strong>{brl(r.valor)}</strong></div><div className="com-kpi"><span>Pedidos</span><strong>{r.pedidos}</strong></div><div className="com-kpi"><span>Ticket médio</span><strong>{brl(r.ticket)}</strong></div></div>
   <section className="com-card com-orders"><h2>Pedidos que compõem o resultado</h2><p className="com-muted">Sinal registrado no pedido. Recebido e saldo aparecem quando os títulos do ERP permitem conciliar a O.S.; caso contrário, ficam para conferência.</p><Lista colunas={colunasPedidos} linhas={linhasOs(r.vendas)}/></section>
   <section className="com-card com-vendas-comparison"><div className="com-section-head"><h2>Comparação com contexto</h2><select aria-label="Tipo de comparação" value={filtro.comparacao} onChange={e=>alterar({comparacao:e.target.value})}><option value="equivalente">Mesmo intervalo do mês anterior</option><option value="mesCompleto">Comparar meses completos</option><option value="anoAnterior">Mesmo mês do ano anterior</option></select></div>{r.comparativo?<><p>{data(r.comparativo.atualDe)} a {data(r.comparativo.atualAte)} versus {data(r.comparativo.de)} a {data(r.comparativo.ate)}{r.comparativo.parcial&&filtro.comparacao==='mesCompleto'?' · mês atual ainda em andamento':''}</p><p>{brl(r.comparativo.valorAtual)} versus {brl(r.comparativo.valorAnterior)}</p><p className="com-comparison"><b>{brl(r.comparativo.delta)}</b><span>{r.comparativo.percentual==null?'Sem base adequada para variação percentual':`${r.comparativo.percentual.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`}</span></p><button className="com-link" onClick={()=>detalhe('Pedidos do período comparado',r.comparativo.registros,'vendas',r.comparativo)}>Conferir período anterior</button></>:<p className="com-muted">Escolha um mês para comparar. Intervalos personalizados mantêm seus totais e registros.</p>}</section>
   <div className="com-split"><Grafico titulo="Evolução mensal" linhas={r.meses} abrir={l=>detalhe(`Pedidos de ${l.mes}`,r.vendas.filter(o=>o.data.startsWith(l.mes)),'vendas')}/><section className="com-card"><h2>Acumulado no período</h2>{r.acumulado.length>1?<svg className="com-line" viewBox="0 0 500 140" role="img" aria-label={`Vendas acumuladas: ${brl(r.valor)}`}><>{r.meta.valor!=null&&<line x1="5" x2="495" y1={130-r.meta.valor/Math.max(r.valor,r.meta.valor,1)*120} y2={130-r.meta.valor/Math.max(r.valor,r.meta.valor,1)*120} stroke="#7b6cce" strokeDasharray="5 4"/>}<polyline fill="none" stroke="currentColor" strokeWidth="3" points={r.acumulado.map((v,i)=>`${i/(r.acumulado.length-1)*490+5},${130-v.centavos/Math.max(r.valor,r.meta.valor||0,1)*120}`).join(' ')}/></></svg>:<p>Sem dados suficientes para a curva.</p>}<p className="com-muted">{data(filtro.de)} a {data(r.hoje<filtro.ate?r.hoje:filtro.ate)} · {brl(r.valor)}. {r.meta.valor==null?'Meta não definida para este recorte.':'Linha pontilhada: meta mensal cadastrada no Painel.'}</p></section></div>
   </div>}
 {aba==='clientes'&&<><ConsultaClientes clientesAutorizados={clientes} abrirCliente={abrirCliente}/><CarteiraComercial clientes={clientes} cobertura={dados.base.coberturaHistorica} modo={params.get('carteira')||'historico'} alterar={alterar} busca={busca} setBusca={setBusca} abrirCliente={abrirCliente}/></>}
 {aba==='produtos'&&<><ComercialDicas compacto onAbrir={()=>setModal({tipo:'dicas'})}/><section className="com-card"><div className="com-section-head"><h2>Produtos e soluções</h2><button className="btn-outline" onClick={()=>setModal({tipo:'checklist'})}><Check size={16}/>Checklist para orçar</button></div><p className="com-muted">Participação no líquido da venda. Desconto do cabeçalho distribuído proporcionalmente entre os itens.</p><div className="com-search sem-impressao"><Search size={17}/><input aria-label="Pesquisar produto" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Produto ou categoria"/></div><Lista colunas={['Produto','Categoria','Vendido','Participação','Quantidade por unidade','']} linhas={filtrar(r.produtos).map(p=>({id:p.id,cells:[p.nome,p.categoria,brl(p.centavos),r.valor?`${(p.centavos/r.valor*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`:'Sem base',Object.entries(p.quantidades).map(([u,n])=>`${n.toLocaleString('pt-BR')} ${u}`).join(' · ')||'Não disponível',<button className="com-link" key="a" onClick={()=>detalhe(p.nome,r.vendas.filter(o=>p.os.includes(o.id)),'vendas')}>Pedidos</button>]}))}/></section><section className="com-card"><h2>Vendas por categoria</h2><Lista colunas={['Categoria','Valor líquido','Participação','Quantidades','']} linhas={r.categorias.map(c=>({id:c.id,cells:[c.nome,brl(c.centavos),r.valor?`${(c.centavos/r.valor*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`:'Sem base',Object.entries(c.quantidades).map(([u,n])=>`${n.toLocaleString('pt-BR')} ${u}`).join(' · ')||'Não disponíveis',<button key="a" className="com-link" onClick={()=>detalhe(c.nome,r.vendas.filter(o=>c.os.includes(o.id)),'vendas')}>Pedidos</button>]}))}/></section><section className="com-card"><h2>Catálogo do Mubisys</h2><Lista colunas={['Produto','Categoria','Características disponíveis']} linhas={filtrar(dados.catalogo.produtos).map(p=>({id:p.id,cells:[p.nome,p.categoria||'Não informada',p.descricao||'Sem descrição cadastrada']}))}/></section></>}
 {aba==='metas'&&<><section className="com-card com-goal"><div className="com-section-head"><h2><Target size={22}/>Minhas metas</h2>{dados.escopo.gestor&&<button className="btn-primary" onClick={()=>setModal({tipo:'meta'})}><Plus size={16}/>Cadastrar meta</button>}</div><MetaResumo r={r} dados={dados}/><p className="com-muted">Realizado: O.S. normal, valor líquido, pela data de cadastro. Calendário: {dados.config.calendario?.configurado?'conferido pela direção':'a configurar pela direção'}.</p></section><section className="com-card"><h2>Metas cadastradas</h2><Lista colunas={['Mês','Vendedora','Meta','Atualização','']} linhas={(dados.metas||[]).filter(m=>m.mes>=filtro.de.slice(0,7)&&m.mes<=filtro.ate.slice(0,7)).map(m=>({id:m.id,cells:[m.mes.split('-').reverse().join('/'),dados.catalogo.vendedores.find(v=>v.id===m.vendedorId)?.nome||'Vendedora',brl(valor(m.valor)),<div key="u">{hora(m.atualizadoEm)}<small>{m.atualizadoPor}</small></div>,dados.escopo.gestor?<button key="e" className="com-link" onClick={()=>setModal({tipo:'meta',vendedor:m.vendedorId,mes:m.mes})}>Editar</button>:'Consulta']}))}/></section></>}

 <details className="com-card com-method"><summary>Fontes e critérios de cálculo</summary><p>{r.criterio}. Cada O.S. entra uma vez pelo ID; orçamentos aprovados e notas não são somados novamente às vendas.</p>{dados.avisos.map(a=><p key={a}>{a}</p>)}<ul>{Object.entries(dados.fontes).map(([nome,v])=><li key={nome}>{{orcamentos:'Orçamentos',ordens:'Pedidos recentes',crm_clientes:'Carteira de clientes',comercial_catalogo:'Vendedores e produtos',status:'Sincronização',historico_status:'Histórico de pedidos'}[nome]||nome}: {hora(v.atualizadoEm)}</li>)}</ul><p>Os registros de próxima ação ficam no Painel. A falta de resposta é um alerta, não uma confirmação de contato ou envio.</p>{dados.escopo.gestor&&<button className="btn-outline sem-impressao" onClick={()=>setModal({tipo:'config'})}><Settings size={16}/>Ajustar rotina e calendário</button>}</details>
 </>}
 {modal?.tipo==='acao'&&dados&&<AcaoForm inicial={modal.a} dados={dados} filtro={filtro} salvo={renovar} fechar={()=>setModal(null)}/>}
 {modal?.tipo==='meta'&&dados&&<MetaForm dados={dados} filtro={{...filtro,vendedor:modal.vendedor||filtro.vendedor,de:modal.mes?modal.mes+'-01':filtro.de}} salvo={renovar} fechar={()=>setModal(null)}/>}
 {modal?.tipo==='config'&&dados&&<ConfigForm dados={dados} filtro={filtro} salvo={renovar} fechar={()=>setModal(null)}/>}
 {modal?.tipo==='legado'&&<Dialogo titulo="Retorno da mesa de orçamentos" fechar={()=>setModal(null)}><h3>{modal.a.cliente}</h3><p>{modal.a.descricao} · {data(modal.a.data)}</p><p>Este retorno já existe na mesa. Edite, reagende ou conclua no registro original para manter um único acompanhamento.</p><Link className="btn-primary" to={`/orcamentos/mesa?${new URLSearchParams({...filtro,aba:'agenda',vendedoraNome:modal.a.vendedorNome||''}).toString()}`}>Conferir retorno na mesa</Link></Dialogo>}
 {modal?.tipo==='novo'&&<Dialogo titulo="Novo orçamento no Mubisys" fechar={()=>setModal(null)}><p>A criação e a edição continuam no Mubisys. A API disponível permite consultar orçamentos, mas não gravá-los.</p><ol><li>Abra o Mubisys com seu acesso.</li><li>Entre em Orçamentos e escolha Novo.</li><li>Após salvar, o orçamento aparecerá aqui na próxima sincronização.</li></ol><a className="btn-primary" href="https://mubisys.com/" target="_blank" rel="noopener noreferrer">Abrir Mubisys <ArrowUpRight size={16}/></a></Dialogo>}
   {modal?.tipo==='lista'&&<Dialogo titulo={modal.titulo} fechar={()=>setModal(null)}><p className="com-muted">{modal.periodo?.rotina?`Pendências atuais até ${data(r?.hoje)} · inclui meses anteriores`:`${data(modal.periodo?.de||filtro.de)} a ${data(modal.periodo?.ate||filtro.ate)}`} · vendedora e equipe do indicador.</p>{modal.conteudo==='vendas'?<Lista colunas={colunasPedidos} linhas={linhasOs(modal.itens)}/>:modal.conteudo==='orcamentos'?<Lista colunas={['Orçamento','Cliente','Valor','']} linhas={modal.itens.map(o=>({id:o.id,cells:[o.numero,o.cliente,brl(valor(o.valor)),<button key="a" className="com-link" onClick={()=>abrirOrc(o)}>Abrir</button>]}))}/>:<Lista colunas={['Cliente','Próxima ação','Data','']} linhas={modal.itens.map(a=>({id:a.id,cells:[a.cliente,a.descricao,data(a.data),<button key="a" className="com-link" onClick={()=>abrirAcao(a)}>Editar / concluir</button>]}))}/>}</Dialogo>}
 {modal?.tipo==='orcamento'&&<Dialogo titulo={`Orçamento #${modal.o.numero}`} fechar={()=>setModal(null)}><div className="com-detail"><h3>{modal.o.cliente}</h3><p>{modal.o.trabalho}</p><b>{brl(valor(modal.o.valor))}</b><p>{status(modal.o)} · {modal.o.vendedorNome}</p><p>Cadastro: {data(modal.o.dataCadastro||modal.o.dataEnvio)} · Envio: não disponível</p><p>Validade: {modal.o.validade?`${modal.o.validade} dias a partir do cadastro`:'não informada'}</p><p>Último registro: {hora(modal.o.ultimaAcao?.atualizadoEm||modal.o.acompanhamento?.ultimoContato)} · Próxima ação: {data(modal.o.proximaAcao?.data||modal.o.acompanhamento?.proximoToque)}</p><p>{modal.o.proximaAcao?.descricao}</p><p>Previsão de decisão: {data(modal.o.ultimaAcao?.decisao)} · Pendências: {modal.o.ultimaAcao?.pendencias||'Não registradas'}</p><p>{modal.o.acompanhamento?.nota}</p><p>Motivo da perda: {modal.o.motivoErp||'Não registrado no ERP'}</p><p>Bruto {brl(valor(modal.o.valorBruto))} − desconto {brl(valor(modal.o.desconto))}</p><button className="btn-primary" onClick={()=>setModal({tipo:'acao',a:{clienteId:modal.o.clienteId,orcamentoId:modal.o.id}})}>Registrar próxima ação</button><button className="btn-outline" disabled={!clientes.some(c=>c.id===modal.o.clienteId)} onClick={()=>abrirCliente(clientes.find(c=>c.id===modal.o.clienteId)||{...dados.base.clientes.find(c=>c.id===modal.o.clienteId),vendas:[],orcamentos:[],acoes:[]})}>Histórico do cliente</button><a href="https://mubisys.com/" target="_blank" rel="noopener noreferrer" className="com-link">Consultar / editar no Mubisys</a><p className="com-muted">Use o número acima na busca do ERP. A atualização depende da sincronização.</p></div></Dialogo>}
   {modal?.tipo==='cliente'&&<Dialogo titulo={modal.c.nome||'Histórico do cliente'} fechar={()=>setModal(null)}><p>{modal.c.responsavel||'Responsável não informado'} · {modal.c.telefone||'Telefone não cadastrado'}</p><p>{modal.c.email}</p><button className="btn-primary" onClick={()=>setModal({tipo:'acao',a:{clienteId:modal.c.id}})}>Programar contato</button><section className="com-client-summary"><h3>Relacionamento com a vendedora selecionada</h3><p>Primeira compra: {data(modal.c.primeiraCompra)} · Última compra: {data(modal.c.ultimaCompra)}</p><p><b>{brl(modal.c.valorHistorico)}</b> em {modal.c.pedidosHistoricos??0} pedidos identificados no histórico disponível.</p><p className="com-muted">{modal.c.cadastroCompleto===false?'Cadastro não localizado na última sincronização. Contatos ainda não disponíveis.':'A troca do responsável atual não altera a autoria das vendas anteriores.'}</p></section><h3>Pedidos no período selecionado</h3><Lista colunas={colunasPedidos} linhas={linhasOs(modal.c.vendas||[])}/><h3>Produtos e serviços adquiridos</h3><p>{(modal.c.produtos||[]).join(' · ')||'Não disponíveis no período'}</p><h3>Orçamentos disponíveis deste cliente</h3>{(modal.c.orcamentos||[]).map(o=><p key={o.id}><button className="com-link" onClick={()=>abrirOrc(o)}>#{o.numero} · {status(o)} · {brl(valor(o.valor))}</button></p>)}<h3>Atendimentos registrados</h3>{(modal.c.acoes||[]).map(a=><article key={a.id} className="com-history"><b>{a.descricao}</b><p>{a.nota}</p><small>{data(a.data)} · {a.status} · {a.atualizadoPor} · {hora(a.atualizadoEm)}</small><button className="com-link" onClick={()=>abrirAcao(a)}>Editar / reagendar</button></article>)}{!(modal.c.acoes||[]).length&&<p>Sem atendimentos registrados no Painel.</p>}<h3>Contatos</h3>{(modal.c.contatos||[]).map(c=><p key={c.id}>{c.nome} · {c.celular||c.email}{c.celular&&<a className="com-link" href={`https://wa.me/${String(c.celular).replace(/\D/g,'')}?text=${encodeURIComponent('Olá! Aqui é da Impresilk. Podemos conversar sobre seu projeto?')}`} target="_blank" rel="noopener noreferrer">Preparar conversa no WhatsApp</a>}</p>)}</Dialogo>}
 {modal?.tipo==='dicas'&&<Dialogo titulo="Dicas de produtos" fechar={()=>setModal(null)}><ComercialDicas/></Dialogo>}
 {modal?.tipo==='checklist'&&<Dialogo titulo="O que confirmar antes de orçar" fechar={()=>setModal(null)}><p>Roteiro para a conversa; não altera o orçamento.</p><Checklist/></Dialogo>}
 </div>;
}
function Prioridades({r,dados,abrirAcao,nova}){
 const [grupo,setGrupo]=useState('todas'),[limite,setLimite]=useState(5);
 const grupos=[['todas','Todas',()=>true],['atrasadas','Atrasados',a=>a.tipo==='Retorno atrasado'],['hoje','Hoje',a=>a.tipo==='Retorno de hoje'],['propostas','Propostas',a=>!a.tipo.startsWith('Retorno')]];
 const selecionado=grupos.find(g=>g[0]===grupo),itens=r.prioridades.filter(selecionado[2]).sort((a,b)=>{const ordem=x=>x.tipo==='Retorno atrasado'?0:x.tipo==='Retorno de hoje'?1:2;return ordem(a)-ordem(b)||String(a.data||'9999').localeCompare(String(b.data||'9999'));});
 return <section className="com-card com-priorities"><div className="com-section-head"><div><p className="com-eyebrow">SUA ROTINA</p><h2>Quem precisa de atenção?</h2><p className="com-muted">Pendências atuais, incluindo meses anteriores. O período filtra os resultados de vendas.</p></div><button className="btn-outline sem-impressao" onClick={nova}><Plus size={16}/> Próxima ação</button></div>
 <div className="com-priority-filters sem-impressao" role="group" aria-label="Filtrar prioridades">{grupos.map(([id,nome,teste])=><button key={id} aria-pressed={grupo===id} onClick={()=>{setGrupo(id);setLimite(5);}}>{nome}<span>{r.prioridades.filter(teste).length}</span></button>)}</div>
 <div className="com-priority-list">{itens.map((a,i)=>{const orc=dados.base.orcamentos.find(o=>o.id===a.orcamentoId);return <article key={a.id} className={`com-priority-item ${a.tipo==='Retorno atrasado'?'is-late':''} ${i>=limite?'is-collapsed':''}`}><div className="com-priority-top"><span className={`com-status ${a.tipo==='Retorno atrasado'?'danger':a.tipo==='Retorno de hoje'?'today':'attention'}`}>{a.tipo}</span><b>{brl(valor(a.valor??orc?.valor))}</b></div><h3>{a.cliente||'Cliente'}</h3><p className="com-priority-action">{a.descricao}</p><div className="com-priority-bottom"><div><span>{orc?`Orçamento #${orc.numero} · `:''}{a.data?data(a.data):'Combinar data'}</span><span>{a.vendedorNome||dados.catalogo.vendedores.find(v=>v.id===a.vendedorId)?.nome||'Responsável a conferir'}</span></div><button className="com-link sem-impressao" onClick={()=>abrirAcao(a)} aria-label={`Preparar ação para ${a.cliente||'cliente'}`}>Preparar ação <ArrowUpRight size={14}/></button></div><small>Último registro: {hora(a.ultimaInteracao||a.atualizadoEm)}</small></article>;})}</div>
 {!itens.length&&<div className="com-empty"><Check size={22} aria-hidden="true"/><b>{grupo==='atrasadas'?'Nenhum retorno atrasado disponível.':'Nenhuma prioridade neste filtro.'}</b><p>Use Próxima ação para registrar um novo atendimento.</p></div>}
 {itens.length>limite&&<button className="btn-outline com-show-more sem-impressao" onClick={()=>setLimite(n=>n+5)}>Mostrar mais {Math.min(5,itens.length-limite)} · {itens.length-limite} restantes</button>}
 </section>;
}
function Checklist(){const [tipo,setTipo]=useState('visual');const comum=['Medidas e quantidade, com unidade','Material e acabamento','Uso interno ou externo','Arte: pronta ou criação','Local, transporte e prazo desejado'];const extras={visual:['Instalação e acesso ao local','Estrutura de fixação','Iluminação e ponto elétrico'],impresso:['Formato, faces e cores','Tiragem e prova de aprovação'],servico:['Escopo e condições do local','Equipe e janela de execução']};return <div className="com-form"><label>Tipo de solução<select value={tipo} onChange={e=>setTipo(e.target.value)}><option value="visual">Comunicação visual / instalação</option><option value="impresso">Material impresso</option><option value="servico">Serviço</option></select></label>{[...comum,...extras[tipo]].map(x=><label key={x}><input type="checkbox"/>{x}</label>)}</div>;}

function CarteiraComercial({clientes,cobertura,modo,alterar,busca,setBusca,abrirCliente}){
 const visoes=[['historico','Já compraram',c=>c.temCompraHistorica],['atual','Carteira atual',c=>c.naCarteira],['negociacao','Com propostas abertas',c=>c.orcamentos.some(o=>o.situacao==='aberto')],['todos','Todos autorizados',()=>true]];
 const selecionada=visoes.find(v=>v[0]===modo)||visoes[0];
 const lista=clientes.filter(selecionada[2]).filter(c=>clienteCorresponde(c,busca)).sort((a,b)=>String(b.ultimaCompra||'').localeCompare(String(a.ultimaCompra||''))||a.nome.localeCompare(b.nome,'pt-BR'));
 const [limite,setLimite]=useState(30);useEffect(()=>setLimite(30),[modo,busca,clientes]);
 return <section className="com-card"><div className="com-section-head"><div><p className="com-eyebrow">RELACIONAMENTOS QUE CONTINUAM</p><h2>Meus clientes</h2><p className="com-muted">Quem já comprou com a vendedora selecionada continua aqui, mesmo sem compra neste mês. O período filtra apenas o valor vendido.</p></div></div>
 <div className="com-priority-filters sem-impressao" role="group" aria-label="Origem dos clientes">{visoes.map(([id,nome,teste])=><button key={id} aria-pressed={selecionada[0]===id} onClick={()=>alterar({carteira:id})}>{nome}<span>{clientes.filter(teste).length}</span></button>)}</div>
 {cobertura&&!cobertura.completo&&<p className="com-coverage"><AlertCircle size={16}/><span>Histórico em conferência. {cobertura.ordensIncompletas?`${cobertura.ordensIncompletas} pedidos sem identificação suficiente ficaram fora da carteira histórica. `:''}A lista apresenta somente os vínculos confirmados na base disponível.</span></p>}
 <div className="com-search sem-impressao"><Search size={17}/><input aria-label="Filtrar minha carteira por nome ou documento" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Filtrar minha carteira por nome ou documento"/><span className="com-muted">{lista.length} clientes</span></div>
 <Lista vazio="Nenhum cliente neste filtro. Confira Carteira atual ou Todos autorizados." colunas={['Cliente','Responsável atual','Última compra','Compras no período','Em aberto','']} linhas={lista.slice(0,limite).map(c=>({id:c.id,cells:[<div key="c"><b>{c.nome}</b><small>{c.documento||'Documento não informado'}</small><small>{c.temCompraHistorica?'Já comprou com esta vendedora':c.naCarteira?'Carteira atual':'Proposta vinculada'}{c.cadastroCompleto===false?' · Cadastro a conferir':''}</small></div>,c.responsavel||'Não informado',<div key="u">{data(c.ultimaCompra)}<small>{c.perfil}</small><small>Próximo contato: {data(c.proximoContato)}</small></div>,brl(c.centavos),c.orcamentos.filter(o=>o.situacao==='aberto').length,<button className="com-link" key="a" onClick={()=>abrirCliente(c)}>Histórico e contato</button>]}))}/>
 {lista.length>limite&&<button className="btn-outline com-show-more sem-impressao" onClick={()=>setLimite(n=>n+30)}>Mostrar mais {Math.min(30,lista.length-limite)} clientes</button>}
 </section>;
}
function OrcamentosComerciais({r,filtro,dados,modo,alterar,busca,setBusca,situacao,setSituacao,filtrar,abrirOrc}){
 const porPeriodo=modo==='periodo';
 const fonte=porPeriodo?r.propostas:r.propostasDisponiveis.filter(o=>['aberto','conferir'].includes(o.situacao)&&(!o.dataCadastro||o.dataCadastro.slice(0,10)<=r.hoje));
 const lista=filtrar(fonte).filter(o=>!situacao||o.situacao===situacao).sort((a,b)=>String(a.proximaAcao?.data||a.acompanhamento?.proximoToque||'9999').localeCompare(String(b.proximaAcao?.data||b.acompanhamento?.proximoToque||'9999'))||String(a.dataCadastro||'').localeCompare(String(b.dataCadastro||'')));
 const [limite,setLimite]=useState(30);useEffect(()=>setLimite(30),[modo,busca,situacao,r]);
 const link=aba=>`/orcamentos/mesa?${new URLSearchParams({...filtro,aba,vendedoraNome:dados.catalogo.vendedores.find(v=>v.id===(filtro.vendedor||dados.escopo.vendedorId))?.nome||''}).toString()}`;
 return <section className="com-card"><div className="com-section-head"><div><p className="com-eyebrow">DO ORÇAMENTO AO PRÓXIMO PASSO</p><h2>Negociações para acompanhar</h2><p className="com-muted">{porPeriodo?'Orçamentos cadastrados no período selecionado.':'Propostas em aberto de todos os meses disponíveis, sem perder os retornos combinados.'}</p></div><div className="com-header-actions sem-impressao"><Link className="btn-outline" to={link('mesa')}>Mesa de orçamentos</Link><Link className="btn-outline" to={link('crm')}>Funil do Mubisys <ArrowUpRight size={14}/></Link></div></div>
 <div className="com-priority-filters sem-impressao" role="group" aria-label="Visão dos orçamentos"><button aria-pressed={!porPeriodo} onClick={()=>{alterar({visaoOrc:'trabalho'});setSituacao('');}}>Em acompanhamento</button><button aria-pressed={porPeriodo} onClick={()=>{alterar({visaoOrc:'periodo'});setSituacao('');}}>Criados no período</button></div>
 <div className="com-quote-summary"><span><b>{r.abertasOperacionais.length}</b> propostas abertas disponíveis</span><span><b>{brl(r.valorAbertoOperacional)}</b> em oportunidades · não é venda realizada</span><span><b>{r.atrasadas.length}</b> retornos atrasados</span></div>
 <div className="com-search sem-impressao"><Search size={17}/><input aria-label="Pesquisar orçamento" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Cliente, número, responsável ou trabalho"/><select aria-label="Situação do orçamento" value={situacao} onChange={e=>setSituacao(e.target.value)}><option value="">Todas as situações desta visão</option><option value="aberto">Em aberto</option>{porPeriodo&&<><option value="ganho">Aprovados</option><option value="perdido">Perdidos / cancelados</option></>}<option value="conferir">A conferir no Mubisys</option></select></div>
 <Lista colunas={['Orçamento / trabalho','Cliente','Responsável','Cadastro','Valor líquido','Situação / próxima ação','']} linhas={lista.slice(0,limite).map(o=>({id:o.id,cells:[<div key="n"><b>#{o.numero}</b><small>{o.trabalho||'Trabalho não informado'}</small></div>,o.cliente,o.vendedorNome,data(o.dataCadastro||o.dataEnvio),brl(valor(o.valor)),<div key="s"><span className={`com-status ${o.situacao==='conferir'?'attention':''}`}>{status(o)}</span><small>{o.proximaAcao?.descricao||o.acompanhamento?.nota||'Combine o próximo passo'}</small><small>Contato: {data(o.proximaAcao?.data||o.acompanhamento?.proximoToque)}</small></div>,<button key="a" className="com-link" onClick={()=>abrirOrc(o)}>Abrir e acompanhar</button>]}))}/>
 {lista.length>limite&&<button className="btn-outline com-show-more sem-impressao" onClick={()=>setLimite(n=>n+30)}>Mostrar mais {Math.min(30,lista.length-limite)} orçamentos</button>}
 <p className="com-muted com-source-note">{lista.length} registros nesta visão. Etapas reais do CRM ficam no Funil do Mubisys; situação do orçamento e etapa do funil são informações distintas. Status desconhecido fica a conferir e não entra como venda aprovada.</p>
 </section>;
}
