import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import ParticipantesReuniao from '../components/ParticipantesReuniao.jsx';
import {SETORES_REUNIAO} from '../../supabase/functions/_shared/reunioes.mjs';
import {baixarPdfPresenca} from '../lib/pdfPresenca.js';
import {podeAbrir} from '../lib/sessao.js';
import {Plus,ArrowLeft,CalendarDays,MapPin,UsersRound,FileText,Paperclip,CheckCircle2} from 'lucide-react';
import JanelaFormulario from '../components/JanelaFormulario.jsx';
import {listarReunioes,salvarReuniao,registrarReuniao,anexarReuniao,abrirArquivoReuniao} from '../services/reunioes.js';
import './reunioes.css';
const hoje=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
const data=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'Sem prazo';
const instante=v=>new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'});
const rotulos={reuniao:'Reunião',treinamento:'Treinamento',agendado:'Agendado',realizado:'Realizado',cancelado:'Cancelado'};
const vazio=nome=>({id:crypto.randomUUID(),titulo:'',setor:'empresa',tipo:'reuniao',situacao:'agendado',data:hoje(),inicio:'09:00',fim:'10:00',local:'',responsavel:nome||'',pauta:'',ata:'',participantes:[],decisoes:[],versaoAnterior:null});
function Campo({titulo,children,amplo=false}){return <label className={amplo?'reu-amplo':''}><span>{titulo}</span>{children}</label>;}
function Editor({item,aoFechar,aoSalvar}){
 const [f,setF]=useState(()=>structuredClone(item)),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState('');
 const campo=k=>({value:f[k],onChange:e=>setF({...f,[k]:e.target.value}),...(['data','inicio','fim'].includes(k)?{onInput:e=>setF({...f,[k]:e.currentTarget.value})}:{})});
 const linha=(grupo,id,k,v)=>setF({...f,[grupo]:f[grupo].map(x=>x.id===id?{...x,[k]:v}:x)});
 async function salvar(e){e.preventDefault();setOcupado(true);setErro('');try{await aoSalvar(f);}catch(e){setErro(e.message);}finally{setOcupado(false);}}
 return <JanelaFormulario titulo={f.versaoAnterior?'Editar encontro':'Novo encontro'} ocupado={ocupado} aoFechar={aoFechar} classe="reu-editor"><form onSubmit={salvar}><fieldset disabled={ocupado}>
 <div className="reu-form"><Campo titulo="Título *" amplo><input required maxLength={180} {...campo('titulo')}/></Campo>
 <Campo titulo="Setor do encontro"><select {...campo('setor')}>{Object.entries(SETORES_REUNIAO).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></Campo><Campo titulo="Tipo"><select {...campo('tipo')}><option value="reuniao">Reunião</option><option value="treinamento">Treinamento</option></select></Campo>
 <Campo titulo="Situação"><select {...campo('situacao')}>{['agendado','realizado','cancelado'].map(x=><option key={x} value={x}>{rotulos[x]}</option>)}</select></Campo>
 <Campo titulo="Data *"><input type="date" required {...campo('data')}/></Campo><div className="reu-horas"><Campo titulo="Início *"><input type="time" required {...campo('inicio')}/></Campo><Campo titulo="Fim *"><input type="time" required {...campo('fim')}/></Campo></div>
 <Campo titulo="Responsável *"><input required maxLength={180} {...campo('responsavel')}/></Campo><Campo titulo="Local ou link da chamada"><input maxLength={250} {...campo('local')}/></Campo>
 <Campo titulo="Pauta e objetivo" amplo><textarea rows={3} maxLength={20000} {...campo('pauta')}/></Campo></div>
 <ParticipantesReuniao participantes={f.participantes} aoMudar={participantes=>setF({...f,participantes})}/>
 <p className="reu-calendario-info"><CalendarDays size={17}/>Ao salvar, o encontro aparece no calendário da empresa. Alterações de data e cancelamentos são refletidos automaticamente.</p>
 <section className="reu-editor-secao"><Campo titulo="Ata · o que foi discutido e definido"><textarea rows={6} maxLength={100000} {...campo('ata')}/></Campo></section>
 <section className="reu-editor-secao"><h3>Decisões e próximos passos</h3>{f.decisoes.map((d,i)=><div className="reu-decisao-form" key={d.id}><Campo titulo={`Encaminhamento ${i+1}`} amplo><input required maxLength={2000} value={d.texto} onChange={e=>linha('decisoes',d.id,'texto',e.target.value)}/></Campo><Campo titulo="Quem vai fazer"><input maxLength={180} value={d.responsavel} onChange={e=>linha('decisoes',d.id,'responsavel',e.target.value)}/></Campo><Campo titulo="Até quando"><input type="date" value={d.prazo} onInput={e=>linha('decisoes',d.id,'prazo',e.currentTarget.value)} onChange={e=>linha('decisoes',d.id,'prazo',e.target.value)}/></Campo><label className="reu-check"><input type="checkbox" checked={d.concluida} onChange={e=>linha('decisoes',d.id,'concluida',e.target.checked)}/>Concluído</label><button type="button" onClick={()=>setF({...f,decisoes:f.decisoes.filter(x=>x.id!==d.id)})}>Remover encaminhamento</button></div>)}<button type="button" className="btn-outline" disabled={f.decisoes.length>=100} onClick={()=>setF({...f,decisoes:[...f.decisoes,{id:crypto.randomUUID(),texto:'',responsavel:'',prazo:'',concluida:false}]})}>+ Encaminhamento</button></section>
 <p className="reu-ajuda">Os registros ficam disponíveis a quem tem acesso a Reuniões. Somente quem criou o encontro ou a direção pode editá-lo. Os arquivos são anexados depois de salvar.</p>
 {erro&&<p role="alert" className="reu-erro">{erro}</p>}<footer className="reu-acoes"><button type="button" className="btn-outline" onClick={aoFechar}>Cancelar</button><button className="btn-primary" type="submit">{ocupado?'Salvando…':'Salvar encontro'}</button></footer></fieldset></form></JanelaFormulario>;
}
export default function Reunioes({sessao}){
 const [params,setParams]=useSearchParams(),[setor,setSetor]=useState('');
 const [itens,setItens]=useState([]),[carregando,setCarregando]=useState(true),[erro,setErro]=useState(''),[busca,setBusca]=useState(''),[tipo,setTipo]=useState(''),[vista,setVista]=useState('proximos'),[id,setId]=useState(()=>params.get('encontro')),[editor,setEditor]=useState(null),[ocupado,setOcupado]=useState(false),[texto,setTexto]=useState(''),[aviso,setAviso]=useState('');
 async function carregar(){setCarregando(true);setErro('');try{setItens(await listarReunioes());}catch(e){setErro(e.message);}finally{setCarregando(false);}}
 useEffect(()=>{carregar();},[]);
 useEffect(()=>{setId(params.get('encontro'));},[params]);
 const abrir=id=>{setId(id);setParams(prev=>{const p=new URLSearchParams(prev);if(id)p.set('encontro',id);else p.delete('encontro');return p;});};
 const atual=itens.find(x=>x.id===id),pendentes=itens.filter(x=>x.situacao==='agendado'&&x.data<hoje()).length;
 const mostrados=itens.filter(x=>(!tipo||x.tipo===tipo)&&(!setor||(x.setor||'outros')===setor)&&(!busca||[x.titulo,x.responsavel,x.local,x.pauta,...x.participantes.map(p=>p.nome)].join(' ').toLocaleLowerCase().includes(busca.toLocaleLowerCase()))&&(vista==='todos'||(vista==='proximos'?x.situacao==='agendado':x.situacao!=='agendado'))).sort((a,b)=>vista==='historico'?b.data.localeCompare(a.data)||b.inicio.localeCompare(a.inicio):a.data.localeCompare(b.data)||a.inicio.localeCompare(b.inicio));
 function atualizar(r){setItens(xs=>[r,...xs.filter(x=>x.id!==r.id)]);}
 async function salvar(f){const r=await salvarReuniao(f);atualizar(r);setEditor(null);abrir(r.id);setAviso(r.situacao==='cancelado'?'Encontro cancelado e retirado do calendário. O histórico continua disponível.':'Encontro salvo e disponível no calendário da empresa.');}
 async function executar(fn,mensagem){setOcupado(true);setErro('');setAviso('');try{await fn();if(mensagem)setAviso(mensagem);}catch(e){setErro(e.message);}finally{setOcupado(false);}}
 function editar(){setEditor({...atual,setor:atual.setor||'outros',versaoAnterior:atual.versao});}
 return <div className="reunioes"><header className="reu-cab"><div><h1>Reuniões e treinamentos</h1><p>Reúna cada setor. Vincule as pessoas. Registre os combinados.</p></div><button className="btn-primary" onClick={()=>setEditor({...vazio(sessao?.nome),setor:setor||'empresa'})}><Plus size={17}/>Novo encontro</button></header>
 <div aria-live="polite">{aviso&&<p className="reu-sucesso">{aviso}</p>}</div>{erro&&<div role="alert" className="reu-erro">{erro} <button disabled={ocupado} onClick={carregar}>Atualizar dados</button></div>}
 {carregando?<p role="status">Carregando encontros…</p>:atual?<>
 <div className="reu-acoes"><button className="btn-outline" onClick={()=>{abrir(null);setErro('');setAviso('');}}><ArrowLeft size={16}/>Todos os encontros</button>{atual.podeEditar&&<button className="btn-primary" disabled={ocupado} onClick={editar}>Editar encontro e ata</button>}</div>
 <article className="reu-painel"><div className="reu-etiquetas"><span className={'reu-setor-'+(atual.setor||'outros')}>{SETORES_REUNIAO[atual.setor]||'Outros setores'}</span><span>{rotulos[atual.tipo]}</span><span className={'reu-'+atual.situacao}>{rotulos[atual.situacao]}</span></div><h2>{atual.titulo}</h2><div className="reu-meta"><span><CalendarDays size={16}/>{data(atual.data)} · {atual.inicio}–{atual.fim}</span><span><MapPin size={16}/>{atual.local||'Local a combinar'}</span><span><UsersRound size={16}/>{atual.responsavel}</span></div>
 <div className="reu-documentos"><div><h3>Lista de presença pronta para assinar</h3><p>Baixe o PDF A4 com nomes, setores e espaço para cada assinatura.</p></div><div className="reu-acoes"><button className="btn-primary" disabled={!atual.participantes.some(p=>p.presenca==='presente')} onClick={()=>executar(()=>baixarPdfPresenca(atual,'presentes'))}><FileText size={16}/>PDF dos presentes</button><button className="btn-outline" disabled={!atual.participantes.length} onClick={()=>executar(()=>baixarPdfPresenca(atual,'assinaturas'))}>Lista para assinaturas</button>{podeAbrir('calendario-empresa',sessao)&&<Link className="btn-outline" to={'/calendario-empresa?mes='+atual.data.slice(0,7)}><CalendarDays size={16}/>Ver no calendário</Link>}</div><small>{atual.participantes.some(p=>p.presenca==='presente')?'O PDF dos presentes inclui somente a presença registrada.':'Marque a presença em “Editar encontro e ata” para emitir o PDF dos presentes.'} A lista para assinaturas relaciona todos os convidados.</small></div><div className="reu-detalhes"><section><h3>Pauta e objetivo</h3><p className="reu-texto">{atual.pauta||'Pauta ainda não registrada.'}</p></section><section><h3>Participantes · {atual.participantes.filter(p=>p.presenca==='presente').length}/{atual.participantes.length} presentes</h3>{atual.participantes.length?<ul className="reu-participantes">{atual.participantes.map(p=><li key={p.id}><span><strong>{p.nome}</strong><small>{p.rhId?[p.area,p.cargo,'Vinculado ao RH'].filter(Boolean).join(' · '):'Externo / sem vínculo RH'}</small></span><span className="reu-etiqueta">{p.presenca==='pendente'?'A confirmar':p.presenca}</span></li>)}</ul>:<p>Participantes ainda não definidos.</p>}</section></div>
 <section className="reu-secao"><h3><FileText size={18}/>Ata do encontro</h3><p className="reu-texto">{atual.ata||'Após o encontro, registre aqui os assuntos discutidos e as decisões.'}</p></section>
 <section className="reu-secao"><h3><CheckCircle2 size={18}/>Encaminhamentos · {atual.decisoes.filter(d=>d.concluida).length}/{atual.decisoes.length} concluídos</h3>{atual.decisoes.length?<ul className="reu-decisoes">{atual.decisoes.map(d=><li key={d.id}><strong>{d.concluida?'✓ ':''}{d.texto}</strong><span>{d.responsavel||'Responsável a definir'} · {data(d.prazo)} · {d.concluida?'Concluído':d.prazo&&d.prazo<hoje()?'Prazo vencido':'Em aberto'}</span></li>)}</ul>:<p>Nenhum encaminhamento registrado.</p>}</section>
 <section className="reu-secao"><h3><Paperclip size={18}/>Arquivos e materiais · {atual.anexos.length}/20</h3><p className="reu-ajuda">PDF, imagens, Word, Excel ou PowerPoint. Até 5 MB por arquivo.</p><ul className="reu-arquivos">{atual.anexos.map(a=><li key={a.id}><button disabled={ocupado} onClick={()=>executar(async()=>{const url=await abrirArquivoReuniao(atual.id,a.id);const link=document.createElement('a');link.href=url;link.rel='noopener noreferrer';link.download=a.nome;document.body.append(link);link.click();link.remove();})}>{a.nome}</button><small>{Math.ceil(a.tamanho/1024)} KB · {a.nomeAutor} · {instante(a.em)}</small></li>)}</ul>{atual.podeEditar&&<label className="reu-upload">Adicionar arquivo<input type="file" aria-label="Adicionar arquivo" disabled={ocupado||atual.anexos.length>=20} accept=".pdf,.png,.jpg,.jpeg,.webp,.docx,.xlsx,.pptx" onChange={e=>{const f=e.target.files[0];e.target.value='';if(f)executar(async()=>atualizar(await anexarReuniao(atual,f)),'Arquivo anexado.');}}/></label>}</section>
 <section className="reu-secao"><h3>Registros e acompanhamento</h3>{atual.registros.map(r=><div className="reu-registro" key={r.id}><p className="reu-texto">{r.texto}</p><small>{r.nome} · {instante(r.em)}</small></div>)}{atual.podeEditar&&<form onSubmit={e=>{e.preventDefault();executar(async()=>{atualizar(await registrarReuniao(atual,texto));setTexto('');},'Registro acrescentado.');}}><Campo titulo="Novo registro"><textarea rows={3} maxLength={5000} value={texto} required onChange={e=>setTexto(e.target.value)} disabled={ocupado}/></Campo><button className="btn-outline" disabled={ocupado||!texto.trim()}>Salvar registro</button></form>}</section>
 <footer className="reu-secao reu-ajuda">Atualizado por {atual.atualizadoPorNome} em {instante(atual.atualizadoEm)}<details><summary>Histórico de alterações ({atual.historico.length})</summary><ul>{[...atual.historico].reverse().map((h,i)=><li key={i}>{instante(h.em)} · {h.nome} · {h.acao}</li>)}</ul></details></footer></article></>:<>
 <div className="reu-setores" role="group" aria-label="Reuniões por setor"><button className={!setor?'selecionado':''} aria-pressed={!setor} onClick={()=>setSetor('')}><span>Todos os setores</span><strong>{itens.length}</strong></button>{Object.entries(SETORES_REUNIAO).map(([k,n])=><button key={k} className={'reu-setor-'+k+(setor===k?' selecionado':'')} aria-pressed={setor===k} onClick={()=>setSetor(k)}><span>{n}</span><strong>{itens.filter(x=>(x.setor||'outros')===k).length}</strong></button>)}</div>
 <div className="reu-resumo"><span><strong>{itens.filter(x=>x.situacao==='agendado').length}</strong> agendados</span><span><strong>{itens.filter(x=>x.situacao==='realizado').length}</strong> realizados</span><span><strong>{itens.filter(x=>x.situacao!=='cancelado').reduce((n,x)=>n+x.decisoes.filter(d=>!d.concluida).length,0)}</strong> encaminhamentos em aberto</span></div>
 {pendentes>0&&<p className="reu-alerta">{pendentes} encontro(s) com data passada aguardam atualização da situação e da ata.</p>}
 <div className="reu-filtros"><div role="group" aria-label="Exibição dos encontros">{[['proximos','Próximos encontros'],['historico','Histórico'],['todos','Todos']].map(([k,n])=><button aria-pressed={vista===k} className={vista===k?'btn-primary':'btn-outline'} key={k} onClick={()=>setVista(k)}>{n}</button>)}</div><input aria-label="Buscar encontros" placeholder="Buscar assunto, pessoa ou local…" value={busca} onChange={e=>setBusca(e.target.value)}/><select aria-label="Filtrar tipo" value={tipo} onChange={e=>setTipo(e.target.value)}><option value="">Reuniões e treinamentos</option><option value="reuniao">Reuniões</option><option value="treinamento">Treinamentos</option></select><button className="btn-outline" onClick={carregar}>Atualizar</button></div>
 <p className="reu-ajuda">{mostrados.length} encontro(s) neste filtro</p><div className="reu-lista">{mostrados.map(r=><button key={r.id} className="reu-card" onClick={()=>{abrir(r.id);setAviso('');}}><div className="reu-data"><strong>{r.data.slice(8)}</strong><span>{new Date(r.data+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'})}</span></div><div className="reu-card-corpo"><div className="reu-etiquetas"><span>{SETORES_REUNIAO[r.setor]||'Outros setores'}</span><span>{rotulos[r.tipo]}</span><span>{rotulos[r.situacao]}</span></div><h2>{r.titulo}</h2><p>{data(r.data)} · {r.inicio}–{r.fim} · {r.local||'Local a combinar'}</p><p>{r.responsavel} · {r.participantes.length} participantes · {r.anexos.length} arquivos</p></div><span className="reu-abrir">Abrir ficha →</span></button>)}</div>{!mostrados.length&&<div className="reu-painel"><h2>Nenhum encontro neste filtro</h2><p>Escolha um setor e crie o encontro. Pessoas do RH, calendário, ata e lista de assinaturas ficam reunidos na mesma ficha.</p></div>}
 </>}{editor&&<Editor item={editor} aoFechar={()=>setEditor(null)} aoSalvar={salvar}/>}</div>;
}
