import {useState} from 'react';
import {NIVEIS_CONSULTORIA} from '../../../supabase/functions/_shared/processos.mjs';
import {Campo} from './EditorProcesso.jsx';
export default function AcessoConsultoria({item,ocupado,executar,link,limparLink,externo=false}){
 const [nivel,setNivel]=useState('colaborador'),[cadastro,setCadastro]=useState(null),[consultorId,setConsultor]=useState(''),[dias,setDias]=useState(14),[aceite,setAceite]=useState(false),[aviso,setAviso]=useState('');
 const consultores=item.consultores||[],mudar=(k,v)=>setCadastro(c=>({...c,[k]:v}));
 return <section className="processo-painel"><div className="processo-linha"><div><h2>Consultores e acesso</h2><p className="processo-ajuda">Equipe interna: cadastro do RH. Consultores externos: cadastro exclusivo desta consultoria.</p></div><button className="btn-outline" disabled={ocupado||!!cadastro} onClick={()=>setCadastro({nome:'',funcao:'',contato:''})}>+ Cadastrar consultor</button></div>
 {cadastro&&<form className="processo-form" onSubmit={e=>{e.preventDefault();executar('consultor',cadastro).then(ok=>{if(ok)setCadastro(null);});}}><Campo nome="Nome do consultor"><input className="input" required maxLength={180} disabled={ocupado} value={cadastro.nome} onChange={e=>mudar('nome',e.target.value)}/></Campo><div className="processo-campos"><Campo nome="Função na consultoria"><input className="input" maxLength={180} disabled={ocupado} value={cadastro.funcao} onChange={e=>mudar('funcao',e.target.value)}/></Campo><Campo nome="Contato do consultor"><input className="input" maxLength={240} disabled={ocupado} value={cadastro.contato} onChange={e=>mudar('contato',e.target.value)} placeholder="E-mail ou telefone (opcional)"/></Campo></div><div className="processo-linha"><button className="btn-primary" disabled={ocupado}>Salvar consultor</button><button type="button" className="btn-outline" disabled={ocupado} onClick={()=>setCadastro(null)}>Cancelar cadastro</button></div></form>}
 <ul className="processo-sinais">{consultores.map(c=><li key={c.id}><div><strong>{c.nome}</strong><p>{c.funcao}{c.contato?' · '+c.contato:''}</p></div><button className="btn-outline" disabled={ocupado||!!cadastro} onClick={()=>setCadastro({...c,consultorId:c.id})}>Editar consultor</button></li>)}</ul>{!consultores.length&&<p className="processo-vazio">Cadastre o primeiro consultor. Esse cadastro não cria uma pessoa no RH nem libera outros sistemas.</p>}
 <div className="processo-niveis"><div><strong>Administrador da consultoria</strong><p>Cadastra a equipe, organiza o trabalho e emite acessos de colaborador ou leitura. A Impresilk concede este nível.</p></div><div><strong>Colaborador</strong><p>Registra ações, planeja e atualiza etapas e anexa materiais. Não administra acessos nem avaliações.</p></div><div><strong>Somente leitura</strong><p>Consulta o trabalho e os arquivos liberados. Não altera dados.</p></div></div><h3 className="mt-4">Gerar acesso exclusivo</h3><p className="processo-ajuda">Escolha o consultor, defina a validade e envie o link. O nível escolhido define o que essa pessoa poderá fazer somente nesta consultoria.</p>
 <form className="processo-form" onSubmit={e=>{e.preventDefault();executar('convidar',{consultorId,dias,nivel}).then(ok=>{if(ok)setAceite(false);});}}><div className="processo-campos"><Campo nome="Consultor cadastrado"><select className="input" value={consultorId} required disabled={ocupado} onChange={e=>setConsultor(e.target.value)}><option value="">Selecione o consultor</option>{consultores.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></Campo><Campo nome="Nível de acesso"><select className="input" value={nivel} disabled={ocupado} onChange={e=>setNivel(e.target.value)}>{Object.entries(NIVEIS_CONSULTORIA).filter(([k])=>!externo||k!=='administrador').map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></Campo><Campo nome="Validade em dias"><input type="number" className="input" min={1} max={30} required disabled={ocupado} value={dias} onChange={e=>setDias(e.target.value)}/></Campo></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={aceite} required disabled={ocupado} onChange={e=>setAceite(e.target.checked)}/>Revisei o nível de acesso e o conteúdo compartilhado, incluindo avaliações e comentários.</label><button className="btn-primary" disabled={ocupado||!aceite||!consultorId}>Gerar link para o consultor</button></form>
 {link&&<div className="processo-proxima"><p>Copie o link agora e envie somente ao consultor selecionado.</p><input className="input" aria-label="Link de colaboração criado" readOnly value={link} onFocus={e=>e.target.select()}/><button className="btn-outline" onClick={async()=>{try{await navigator.clipboard.writeText(link);setAviso('Link copiado.');}catch{setAviso('Selecione e copie o endereço acima.');}}}>Copiar link</button>{aviso&&<p role="status">{aviso}</p>}</div>}
 {externo&&<p className="processo-ajuda">Seus convites também encerram quando seu acesso expirar ou for revogado. Só a Impresilk pode conceder administração. Você vê e revoga os acessos que emitiu.</p>}<p className="processo-ajuda">O link é pessoal, mas pode ser repassado por quem o receber. Ele identifica o convite, não comprova a identidade. Expira em até 30 dias e pode ser revogado. Links anteriores permanecem identificados pelo nome usado na criação.</p>
 <details className="mt-3"><summary className="cursor-pointer font-semibold">Acessos emitidos ({item.convites.length})</summary><ul className="processo-sinais">{item.convites.map(c=><li key={c.id}><div><strong>{c.nome}</strong><p>{NIVEIS_CONSULTORIA[c.nivel||'colaborador']} · {c.revogadoEm?'Revogado':Date.parse(c.expiraEm)<=Date.now()?'Expirado':'Válido até '+new Date(c.expiraEm).toLocaleString('pt-BR')}{c.rhId?' · vínculo interno do RH':''}</p></div>{!c.revogadoEm&&Date.parse(c.expiraEm)>Date.now()&&<button className="btn-outline" disabled={ocupado} onClick={()=>executar('revogar',{conviteId:c.id}).then(ok=>{if(ok)limparLink();})}>Revogar acesso</button>}</li>)}</ul></details>
 </section>;
}
