import {useState} from 'react';
import {TIPOS_REGISTRO} from '../../../supabase/functions/_shared/processos.mjs';
import ImplantacaoProcesso,{CamposImplantacao} from './ImplantacaoProcesso.jsx';
import {Campo,Opcoes} from './EditorProcesso.jsx';
const dia=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
const data=v=>v?.split('-').reverse().join('/');
export default function AcoesProcesso({item,externo,ocupado,executar,irArquivos}){
 const [novo,setNovo]=useState(false),[tipo,setTipo]=useState('acao'),[titulo,setTitulo]=useState(''),[dataAcao,setData]=useState(dia),[texto,setTexto]=useState(''),[resultado,setResultado]=useState(''),[proximoPasso,setProximo]=useState(''),[etapaId,setEtapa]=useState(''),[compartilhado,setCompartilhado]=useState(false),[filtro,setFiltro]=useState('todos'),[implantacao,setImplantacao]=useState({situacao:'nao_iniciada',como:'',data:''});
 const lista=[...(item.registros||[])].reverse().filter(r=>filtro==='todos'||(r.tipo||'atualizacao')===filtro);
 async function salvar(e){e.preventDefault();const ok=await executar('registro',{tipo,titulo,dataAcao,texto,resultado,proximoPasso,etapaId,compartilhado,implantacao});if(ok){setNovo(false);setTitulo('');setTexto('');setResultado('');setProximo('');setEtapa('');setImplantacao({situacao:'nao_iniciada',como:'',data:''});}}
 return <section className="processo-painel" aria-label="Ações e registros"><div className="processo-linha"><div><h2>Ações e registros</h2><p className="processo-ajuda">O que foi feito, o resultado e o que vem depois. Cada registro fica identificado.</p></div><button className="btn-primary" disabled={ocupado||novo} onClick={()=>setNovo(true)}>+ Registrar ação</button></div>
 {novo&&<form onSubmit={salvar} className="processo-form"><div className="processo-campos"><Campo nome="Tipo de registro"><select className="input" value={tipo} disabled={ocupado} onChange={e=>setTipo(e.target.value)}><Opcoes mapa={TIPOS_REGISTRO}/></select></Campo><Campo nome="Data da ação"><input className="input" type="date" required={tipo==='acao'} value={dataAcao} disabled={ocupado} onChange={e=>setData(e.target.value)}/></Campo></div><Campo nome="Título da ação"><input className="input" value={titulo} required={tipo==='acao'} maxLength={180} disabled={ocupado} onChange={e=>setTitulo(e.target.value)} placeholder="Ex.: Mapeamento do processo de compras"/></Campo><Campo nome="O que foi feito ou está acontecendo"><textarea className="input" value={texto} required maxLength={5000} disabled={ocupado} onChange={e=>setTexto(e.target.value)}/></Campo><div className="processo-campos"><Campo nome="Resultado / evidência"><textarea className="input" value={resultado} maxLength={5000} disabled={ocupado} onChange={e=>setResultado(e.target.value)} placeholder="O que mudou ou foi entregue?"/></Campo><Campo nome="Próximo passo combinado"><textarea className="input" value={proximoPasso} maxLength={2000} disabled={ocupado} onChange={e=>setProximo(e.target.value)} placeholder="O que faremos a seguir?"/></Campo></div><Campo nome="Vincular a uma etapa"><select className="input" value={etapaId} disabled={ocupado} onChange={e=>setEtapa(e.target.value)}><option value="">Registro geral da consultoria</option>{item.etapas.map(e=><option key={e.id} value={e.id}>{e.titulo}</option>)}</select></Campo>{tipo==='acao'&&<CamposImplantacao valor={implantacao} mudar={setImplantacao} ocupado={ocupado}/>}<p className="processo-ajuda">Este registro não muda prazos nem conclui etapas. Materiais podem ser anexados em Arquivos após salvar.</p>{!externo&&item.tipo==='consultoria'&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={compartilhado} disabled={ocupado} onChange={e=>setCompartilhado(e.target.checked)}/>Visível para a consultoria</label>}<div className="processo-linha"><button className="btn-primary" disabled={ocupado}>{ocupado?'Salvando…':'Salvar registro'}</button><button type="button" className="btn-outline" disabled={ocupado} onClick={()=>setNovo(false)}>Cancelar registro</button></div></form>}
 <div className="processo-linha"><label className="text-sm">Mostrar <select aria-label="Filtrar registros" className="input" value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="todos">Todos os registros</option><Opcoes mapa={TIPOS_REGISTRO}/></select></label><button className="btn-outline" disabled={ocupado} onClick={irArquivos}>Anexar materiais</button></div>
 {!lista.length&&<p className="processo-vazio">Nenhum registro neste filtro. Comece pelo diagnóstico ou pela primeira ação realizada.</p>}
 <ol className="processo-registros">{lista.map(r=><li key={r.id}><details><summary><span className="processo-chip">{TIPOS_REGISTRO[r.tipo]||'Andamento'}</span><strong>{r.titulo||r.texto.slice(0,100)}</strong><small>{data(r.dataAcao)||new Date(r.em).toLocaleDateString('pt-BR')} · {r.nome}</small></summary><div className="processo-detalhes"><p>{r.texto}</p>{r.resultado&&<div><h3>Resultado</h3><p>{r.resultado}</p></div>}{r.proximoPasso&&<div><h3>Próximo passo</h3><p>{r.proximoPasso}</p></div>}{r.etapaId&&<p className="processo-ajuda">Etapa: {item.etapas.find(e=>e.id===r.etapaId)?.titulo||'Etapa não disponível'}</p>}{r.tipo==='acao'&&<ImplantacaoProcesso registro={r} ocupado={ocupado} executar={executar}/>}<p className="processo-ajuda">Salvo em {new Date(r.em).toLocaleString('pt-BR')}{!externo?' · '+(r.compartilhado?'Compartilhado':'Interno'):''}</p></div></details></li>)}</ol></section>;
}
