import {useState} from 'react';
import {SITUACOES,SETORES,PRIORIDADES,ESTADOS_ETAPA} from '../../../supabase/functions/_shared/processos.mjs';
export function Campo({nome,children}){return <label className="block text-sm font-medium text-slate-700"><span className="block mb-1">{nome}</span>{children}</label>;}
export function Opcoes({mapa}){return Object.entries(mapa).map(([id,nome])=><option key={id} value={id}>{nome}</option>);}
export default function EditorProcesso({item,tipo,pessoas,aoSalvar,aoCancelar,ocupado}){
 const [f,setF]=useState(()=>item?{...item,versaoAnterior:item.versao}:{id:crypto.randomUUID(),tipo,titulo:'',objetivo:'',analise:'',solucao:'',empresa:'',especialidade:'',setor:'empresa',situacao:'nova',prioridade:'normal',prazo:'',responsavelRhId:'',envolvidos:[],etapas:[],versaoAnterior:null});
 const [busca,setBusca]=useState('');
 const mudar=(k,v)=>setF(x=>({...x,[k]:v}));
 const etapa=(id,k,v)=>setF(x=>({...x,etapas:x.etapas.map(e=>e.id===id?{...e,[k]:v}:e)}));
 const catalogo=[...pessoas,...f.envolvidos.filter(p=>!pessoas.some(x=>x.id===p.rhId)).map(p=>({...p,id:p.rhId,area:(p.area||'')+' · vínculo anterior'}))];
 function selecionar(p){setF(x=>{const tem=x.envolvidos.some(e=>e.rhId===p.id);return {...x,envolvidos:tem?x.envolvidos.filter(e=>e.rhId!==p.id):[...x.envolvidos,{rhId:p.id,nome:p.nome}],responsavelRhId:tem&&x.responsavelRhId===p.id?'':x.responsavelRhId};});}
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();aoSalvar(f);}}>
  <div className="flex justify-between gap-3 items-center"><h2 className="text-xl font-semibold">{item?'Editar':'Nova'} {tipo==='consultoria'?'consultoria':'demanda'}</h2><button type="button" className="btn-outline" disabled={ocupado} onClick={aoCancelar}>Voltar</button></div>
  <fieldset disabled={ocupado} className="space-y-4">
   <Campo nome="Título"><input className="input w-full" value={f.titulo} maxLength={180} required onChange={e=>mudar('titulo',e.target.value)}/></Campo>
   {tipo==='consultoria'&&<div className="grid md:grid-cols-2 gap-3"><Campo nome="Consultoria / empresa ou profissional"><input className="input w-full" value={f.empresa} maxLength={180} required onChange={e=>mudar('empresa',e.target.value)}/></Campo><Campo nome="Especialidade"><input className="input w-full" value={f.especialidade} maxLength={180} placeholder="Ex.: gestão financeira" onChange={e=>mudar('especialidade',e.target.value)}/></Campo></div>}
   <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{[['setor','Setor',SETORES],['situacao','Situação',SITUACOES],['prioridade','Prioridade',PRIORIDADES]].map(([k,n,mapa])=><Campo key={k} nome={n}><select className="input w-full" value={f[k]} onChange={e=>mudar(k,e.target.value)}><Opcoes mapa={mapa}/></select></Campo>)}<Campo nome="Prazo geral"><input type="date" className="input w-full" value={f.prazo} onChange={e=>mudar('prazo',e.target.value)}/></Campo></div>
   <Campo nome="Objetivo e resultado esperado"><textarea className="input w-full min-h-20" value={f.objetivo} maxLength={10000} required onChange={e=>mudar('objetivo',e.target.value)}/></Campo>
   <details className="rounded-xl border p-3"><summary className="cursor-pointer font-medium">Análise interna e solução</summary><div className="grid md:grid-cols-2 gap-3 mt-3"><Campo nome="Estudo do problema · somente equipe interna"><textarea className="input w-full min-h-28" value={f.analise} maxLength={20000} onChange={e=>mudar('analise',e.target.value)}/></Campo><Campo nome="Solução / decisões · visível no link da consultoria"><textarea className="input w-full min-h-28" value={f.solucao} maxLength={20000} onChange={e=>mudar('solucao',e.target.value)}/></Campo></div></details>
   <section className="rounded-xl border p-4 space-y-3"><h3 className="font-semibold">Pessoas envolvidas · RH</h3><p className="text-sm text-slate-500">O vínculo acompanha o ID da pessoa no RH. Selecione os envolvidos e um responsável pelo processo.</p>
   <input className="input w-full" aria-label="Buscar pessoa do RH" placeholder="Buscar nome ou setor…" value={busca} onChange={e=>setBusca(e.target.value)}/>
   <div className="max-h-48 overflow-auto grid sm:grid-cols-2 gap-2">{catalogo.filter(p=>(p.nome+' '+p.area).toLocaleLowerCase().includes(busca.toLocaleLowerCase())).map(p=><label key={p.id} className="flex items-center gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" checked={f.envolvidos.some(x=>x.rhId===p.id)} onChange={()=>selecionar(p)}/><span>{p.nome}<small className="block text-slate-500">{p.area} · ID {p.id}</small></span></label>)}</div>
   {!catalogo.length&&<p role="alert">Nenhuma pessoa disponível. Confira os cadastros do RH.</p>}
   <Campo nome="Responsável pelo processo"><select className="input w-full" required value={f.responsavelRhId} onChange={e=>mudar('responsavelRhId',e.target.value)}><option value="">Selecione entre os envolvidos</option>{f.envolvidos.map(p=><option key={p.rhId} value={p.rhId}>{p.nome}</option>)}</select></Campo></section>
   <section className="space-y-3"><div className="flex justify-between items-center gap-2"><h3 className="font-semibold">Etapas e prazos</h3><button type="button" className="btn-outline" disabled={!f.envolvidos.length||f.etapas.length>=100} onClick={()=>mudar('etapas',[...f.etapas,{id:crypto.randomUUID(),titulo:'',descricao:'',responsavelRhId:f.responsavelRhId||f.envolvidos[0]?.rhId||'',prazo:'',situacao:'pendente',dependeDe:[],nota:''}])}>+ Adicionar etapa</button></div><p className="text-sm text-slate-500">Cada prazo aparece no calendário. Nas consultorias, os títulos, descrições, responsáveis, prazos e andamento das etapas ficam visíveis aos convidados.</p>
   {f.etapas.map((e,i)=><details key={e.id} open className="rounded-xl border p-3"><summary className="font-medium cursor-pointer">{i+1}. {e.titulo||'Nova etapa'}</summary><div className="space-y-3 mt-3"><Campo nome="Nome da etapa"><input className="input w-full" required maxLength={180} value={e.titulo} onChange={v=>etapa(e.id,'titulo',v.target.value)}/></Campo><div className="grid md:grid-cols-3 gap-3"><Campo nome="Responsável da etapa"><select className="input w-full" required value={e.responsavelRhId} onChange={v=>etapa(e.id,'responsavelRhId',v.target.value)}><option value="">Selecione</option>{f.envolvidos.map(p=><option key={p.rhId} value={p.rhId}>{p.nome}</option>)}</select></Campo><Campo nome="Prazo da etapa"><input type="date" className="input w-full" value={e.prazo} onChange={v=>etapa(e.id,'prazo',v.target.value)}/></Campo><Campo nome="Situação da etapa"><select className="input w-full" value={e.situacao} onChange={v=>etapa(e.id,'situacao',v.target.value)}><Opcoes mapa={ESTADOS_ETAPA}/></select></Campo></div><Campo nome="O que precisa ser feito"><textarea className="input w-full" maxLength={5000} value={e.descricao} onChange={v=>etapa(e.id,'descricao',v.target.value)}/></Campo><Campo nome="Andamento / motivo de bloqueio"><textarea className="input w-full" maxLength={5000} value={e.nota} onChange={v=>etapa(e.id,'nota',v.target.value)}/></Campo>
   {f.etapas.length>1&&<fieldset><legend className="text-sm font-medium">Só iniciar após concluir</legend><div className="flex flex-wrap gap-3 mt-1">{f.etapas.filter(x=>x.id!==e.id).map(x=><label key={x.id} className="text-sm flex gap-2"><input type="checkbox" checked={e.dependeDe.includes(x.id)} onChange={v=>etapa(e.id,'dependeDe',v.target.checked?[...e.dependeDe,x.id]:e.dependeDe.filter(id=>id!==x.id))}/>{x.titulo||'Etapa sem título'}</label>)}</div></fieldset>}
   <button type="button" className="btn-ghost text-red-700" onClick={()=>mudar('etapas',f.etapas.filter(x=>x.id!==e.id).map(x=>({...x,dependeDe:x.dependeDe.filter(id=>id!==e.id)})))}>Retirar esta etapa da ficha</button></div></details>)}
   </section>
   <div className="flex gap-2"><button className="btn-primary" type="submit">{ocupado?'Salvando…':'Salvar ficha e prazos'}</button><button className="btn-outline" type="button" onClick={aoCancelar}>Cancelar edição</button></div>
  </fieldset>
 </form>;
}
