import {useState} from 'react';
import {SITUACOES,SETORES,PRIORIDADES} from '../../../supabase/functions/_shared/processos.mjs';
import {Campo} from './EditorProcesso.jsx';
import {chamarProcesso,anexarProcesso} from '../../services/processos.js';
import AcessoConsultoria from './AcessoConsultoria.jsx';
import AcoesProcesso from './AcoesProcesso.jsx';
import PlanoEtapas from './PlanoEtapas.jsx';
import ResumoProcesso from './ResumoProcesso.jsx';
import './processos.css';
const data=v=>v?v.slice(0,10).split('-').reverse().join('/'):'Sem prazo';
const quando=v=>new Date(v).toLocaleString('pt-BR');
export default function FichaProcesso({item,aoAtualizar,aoVoltar,aoEditar,convite=''}){
 const externo=!!convite,[ocupado,setOcupado]=useState(false),[erro,setErro]=useState(''),[aviso,setAviso]=useState(''),[aba,setAba]=useState(externo?'acoes':'resumo'),[link,setLink]=useState('');
 const concluidas=item.etapas.filter(e=>e.situacao==='concluida').length;
 async function executar(action,dados={}){setOcupado(true);setErro('');setAviso('');try{const r=await chamarProcesso(action,{...dados,id:item.id,versao:item.versao},convite);if(r.item)aoAtualizar(r.item);if(r.convite){const base=new URL(import.meta.env.BASE_URL,window.location.origin);setLink(new URL('colaborar',base).href+'#convite='+r.convite);}setAviso('Atualização salva.');return true;}catch(e){setErro(e.message);return false;}finally{setOcupado(false);}}
 async function upload(arquivo){if(!arquivo)return;setOcupado(true);setErro('');try{const r=await anexarProcesso(item,arquivo,convite);aoAtualizar(r.item);setAviso('Arquivo anexado.');}catch(e){setErro(e.message);}finally{setOcupado(false);}}
 async function abrir(a){setOcupado(true);setErro('');try{const {url}=await chamarProcesso('arquivo',{id:item.id,arquivoId:a.id},convite);const el=document.createElement('a');el.href=url;el.rel='noreferrer noopener';el.target='_blank';el.click();}catch(e){setErro(e.message);}finally{setOcupado(false);}}
 return <div className="processo-ficha space-y-3">
 <div className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-2">{aoVoltar&&<button className="btn-outline" onClick={aoVoltar} disabled={ocupado}>← Voltar à lista</button>}<button className="btn-outline" disabled={ocupado} onClick={()=>executar('obter')}>Atualizar ficha</button></div>{item.podeGerir&&aoEditar&&<button className="btn-primary" disabled={ocupado} onClick={aoEditar}>Editar ficha e etapas</button>}</div>
 {erro&&<div role="alert" className="rounded-xl bg-red-50 border border-red-200 p-3 text-red-800">{erro}</div>}{aviso&&<p role="status" className="text-sm text-emerald-700">{aviso}</p>}
 <header className="rounded-xl border bg-white p-3 space-y-2"><div className="text-xs uppercase tracking-wide text-indigo-700 font-bold">{item.tipo==='consultoria'?'Consultoria':'Demanda'}{item.empresa?' · '+item.empresa:''}</div><h2 className="text-xl font-semibold break-words">{item.titulo}</h2><div className="flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-indigo-50 text-indigo-800 px-3 py-1">{SITUACOES[item.situacao]}</span>{item.setor&&<span className="rounded-full bg-slate-100 px-3 py-1">{SETORES[item.setor]}</span>}{item.prioridade&&<span className="rounded-full bg-slate-100 px-3 py-1">Prioridade {PRIORIDADES[item.prioridade].toLowerCase()}</span>}<span className="rounded-full bg-slate-100 px-3 py-1">Prazo: {data(item.prazo)}</span></div><details><summary className="cursor-pointer text-sm font-medium">Objetivo do trabalho</summary><p className="whitespace-pre-wrap text-sm mt-2">{item.objetivo}</p></details>{item.especialidade&&<p className="text-sm text-slate-500">Especialidade: {item.especialidade}</p>}<div><p className="text-sm mb-1">{concluidas} de {item.etapas.length} etapas concluídas</p><div role="progressbar" aria-label="Progresso das etapas" aria-valuenow={concluidas} aria-valuemin={0} aria-valuemax={item.etapas.length||1} className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600 transition-all" style={{width:`${100*concluidas/(item.etapas.length||1)}%`}}/></div></div></header>
 <nav className="processo-abas" aria-label="Seções da consultoria">{[['resumo','Resumo'],['acoes','Ações · '+item.registros.length],['etapas','Etapas · '+item.etapas.length],['arquivos','Arquivos · '+item.anexos.length],...(item.podeGerir&&item.tipo==='consultoria'?[['acesso','Consultores e acesso']]:[])].map(([id,n])=><button key={id} type="button" aria-pressed={aba===id} disabled={ocupado} className={aba===id?'selecionada':''} onClick={()=>{setAba(id);setAviso('');}}>{n}</button>)}</nav>
 {aba==='resumo'&&<ResumoProcesso item={item} ir={setAba}/>}
 <div hidden={aba!=='acoes'}><AcoesProcesso item={item} externo={externo} ocupado={ocupado} executar={executar} irArquivos={()=>setAba('arquivos')}/></div>

 {aba==='resumo'&&!externo&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Pessoas envolvidas ({item.envolvidos.length})</summary><ul className="mt-3 grid sm:grid-cols-2 gap-2">{item.envolvidos.map(p=><li key={p.rhId} className="text-sm">{p.nome}{p.rhId===item.responsavelRhId?' · Responsável':''}<small className="block text-slate-500">{p.area} · ID RH: {p.rhId}</small></li>)}</ul></details>}
 {aba==='resumo'&&(!externo&&item.analise||item.solucao)&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Estudo e decisões</summary><div className="mt-3 space-y-3">{!externo&&item.analise&&<div><h3 className="font-medium">Análise interna</h3><p className="whitespace-pre-wrap text-sm">{item.analise}</p></div>}{item.solucao&&<div><h3 className="font-medium">Solução e decisões</h3><p className="whitespace-pre-wrap text-sm">{item.solucao}</p></div>}</div></details>}
 <div hidden={aba!=='etapas'}><PlanoEtapas item={item} externo={externo} ocupado={ocupado} executar={executar}/></div>
 {aba==='arquivos'&&<section className="rounded-2xl border bg-white p-4 space-y-3"><h2 className="font-semibold text-lg">Arquivos ({item.anexos.length})</h2><p className="text-xs text-slate-500">PDF, JPG, PNG, WEBP, DOCX, XLSX ou PPTX. Até 5 MB por arquivo e 20 arquivos por processo.</p><Campo nome="Anexar arquivo"><input type="file" className="block w-full text-sm" accept=".pdf,.jpg,.jpeg,.png,.webp,.docx,.xlsx,.pptx" disabled={ocupado||item.anexos.length>=20} onChange={e=>{const f=e.target.files?.[0];e.target.value='';upload(f);}}/></Campo>{!externo&&<p className="text-xs text-slate-500">Novos anexos internos só aparecem no link após o gestor liberar.</p>}<ul className="space-y-3">{item.anexos.map(a=><li key={a.id} className="border-t pt-2"><button className="text-indigo-700 underline break-all text-left" disabled={ocupado} onClick={()=>abrir(a)}>{a.nome}</button><p className="text-xs text-slate-500">{a.nomeAutor} · {quando(a.em)}</p>{item.podeGerir&&item.tipo==='consultoria'&&<label className="flex gap-2 text-sm mt-1"><input type="checkbox" checked={a.compartilhado===true} disabled={ocupado} onChange={e=>executar('compartilhar',{arquivoId:a.id,compartilhado:e.target.checked})}/>Visível no link da consultoria</label>}</li>)}</ul></section>}
 {aba==='acesso'&&item.podeGerir&&item.tipo==='consultoria'&&<AcessoConsultoria item={item} ocupado={ocupado} executar={executar} link={link} limparLink={()=>setLink('')}/>}
 {aba==='resumo'&&!externo&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Histórico do processo</summary><ol className="mt-3 max-h-64 overflow-auto space-y-2">{[...item.historico].reverse().map(h=><li className="text-sm" key={h.id}>{h.acao}<small className="block text-slate-500">{h.nome} · {quando(h.em)}</small></li>)}</ol></details>}
 </div>;
}
