import {useState} from 'react';
import {SITUACOES,ESTADOS_ETAPA,SETORES,PRIORIDADES} from '../../../supabase/functions/_shared/processos.mjs';
import {Campo,Opcoes} from './EditorProcesso.jsx';
import {chamarProcesso,anexarProcesso} from '../../services/processos.js';
const data=v=>v?v.slice(0,10).split('-').reverse().join('/'):'Sem prazo';
const quando=v=>new Date(v).toLocaleString('pt-BR');
function Etapa({e,item,externo,ocupado,executar}){
 const [editando,setEditando]=useState(false),[situacao,setSituacao]=useState(e.situacao),[nota,setNota]=useState(e.nota||'');
 const pode=(!['cancelada','concluida'].includes(item.situacao))&&(externo?e.situacao!=='concluida':item.podeGerir||item.meuRhId===e.responsavelRhId);
 return <article id={'etapa-'+e.id} className="rounded-xl border p-4 space-y-2"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{e.titulo}</h3><span className="text-sm rounded-full bg-slate-100 px-2 py-1">{ESTADOS_ETAPA[e.situacao]}</span></div><p className="text-sm text-slate-500">{e.responsavel||item.envolvidos?.find(p=>p.rhId===e.responsavelRhId)?.nome} · {data(e.prazo)}</p>{e.descricao&&<p className="whitespace-pre-wrap text-sm">{e.descricao}</p>}{e.dependeDe.length>0&&<p className="text-xs text-slate-500">Depende de: {e.dependeDe.map(id=>item.etapas.find(x=>x.id===id)?.titulo).join(', ')}</p>}{e.nota&&<p className="rounded-lg bg-slate-50 p-2 text-sm whitespace-pre-wrap">{e.nota}</p>}
 {pode&&!editando&&<button className="btn-outline" disabled={ocupado} onClick={()=>{setSituacao(e.situacao);setNota(e.nota||'');setEditando(true);}}>Registrar andamento</button>}
 {editando&&pode&&<form className="space-y-2" onSubmit={ev=>{ev.preventDefault();executar('etapa',{etapaId:e.id,situacao,nota}).then(ok=>{if(ok)setEditando(false);});}}><Campo nome="Novo andamento"><select className="input w-full" value={situacao} disabled={ocupado} onChange={v=>setSituacao(v.target.value)}><Opcoes mapa={Object.fromEntries(Object.entries(ESTADOS_ETAPA).filter(([k])=>!externo||k!=='concluida'))}/></select></Campo><Campo nome="Atualização ou motivo do bloqueio"><textarea className="input w-full" value={nota} maxLength={5000} disabled={ocupado} required={situacao==='bloqueada'} onChange={v=>setNota(v.target.value)}/></Campo>{externo&&<p className="text-xs text-slate-500">Use “Em validação” ao terminar. A equipe interna confirma a conclusão.</p>}<div className="flex gap-2"><button className="btn-primary" disabled={ocupado}>Salvar andamento</button><button className="btn-outline" type="button" disabled={ocupado} onClick={()=>setEditando(false)}>Cancelar</button></div></form>}
 </article>;
}
export default function FichaProcesso({item,aoAtualizar,aoVoltar,aoEditar,convite=''}){
 const externo=!!convite,[ocupado,setOcupado]=useState(false),[erro,setErro]=useState(''),[aviso,setAviso]=useState(''),[texto,setTexto]=useState(''),[compartilhado,setCompartilhado]=useState(false),[nome,setNome]=useState(''),[rhId,setRhId]=useState(''),[dias,setDias]=useState(14),[aceite,setAceite]=useState(false),[link,setLink]=useState('');
 const concluidas=item.etapas.filter(e=>e.situacao==='concluida').length;
 async function executar(action,dados={}){setOcupado(true);setErro('');setAviso('');try{const r=await chamarProcesso(action,{id:item.id,versao:item.versao,...dados},convite);if(r.item)aoAtualizar(r.item);if(r.convite){const base=new URL(import.meta.env.BASE_URL,window.location.origin);setLink(new URL('colaborar',base).href+'#convite='+r.convite);}setAviso('Atualização salva.');return true;}catch(e){setErro(e.message);return false;}finally{setOcupado(false);}}
 async function upload(arquivo){if(!arquivo)return;setOcupado(true);setErro('');try{const r=await anexarProcesso(item,arquivo,convite);aoAtualizar(r.item);setAviso('Arquivo anexado.');}catch(e){setErro(e.message);}finally{setOcupado(false);}}
 async function abrir(a){setOcupado(true);setErro('');try{const {url}=await chamarProcesso('arquivo',{id:item.id,arquivoId:a.id},convite);const el=document.createElement('a');el.href=url;el.rel='noreferrer noopener';el.target='_blank';el.click();}catch(e){setErro(e.message);}finally{setOcupado(false);}}
 return <div className="space-y-4">
 <div className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-2">{aoVoltar&&<button className="btn-outline" onClick={aoVoltar} disabled={ocupado}>← Voltar à lista</button>}<button className="btn-outline" disabled={ocupado} onClick={()=>executar('obter')}>Atualizar ficha</button></div>{item.podeGerir&&aoEditar&&<button className="btn-primary" disabled={ocupado} onClick={aoEditar}>Editar ficha e etapas</button>}</div>
 {erro&&<div role="alert" className="rounded-xl bg-red-50 border border-red-200 p-3 text-red-800">{erro}</div>}{aviso&&<p role="status" className="text-sm text-emerald-700">{aviso}</p>}
 <header className="rounded-2xl border bg-white p-5 space-y-3"><div className="text-xs uppercase tracking-wide text-indigo-700 font-bold">{item.tipo==='consultoria'?'Consultoria':'Demanda'}{item.empresa?' · '+item.empresa:''}</div><h2 className="text-2xl font-semibold break-words">{item.titulo}</h2><div className="flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-indigo-50 text-indigo-800 px-3 py-1">{SITUACOES[item.situacao]}</span>{item.setor&&<span className="rounded-full bg-slate-100 px-3 py-1">{SETORES[item.setor]}</span>}{item.prioridade&&<span className="rounded-full bg-slate-100 px-3 py-1">Prioridade {PRIORIDADES[item.prioridade].toLowerCase()}</span>}<span className="rounded-full bg-slate-100 px-3 py-1">Prazo: {data(item.prazo)}</span></div><p className="whitespace-pre-wrap">{item.objetivo}</p>{item.especialidade&&<p className="text-sm text-slate-500">Especialidade: {item.especialidade}</p>}<div><p className="text-sm mb-1">{concluidas} de {item.etapas.length} etapas concluídas</p><div role="progressbar" aria-label="Progresso das etapas" aria-valuenow={concluidas} aria-valuemin={0} aria-valuemax={item.etapas.length||1} className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600 transition-all" style={{width:`${100*concluidas/(item.etapas.length||1)}%`}}/></div></div></header>
 {!externo&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Pessoas envolvidas ({item.envolvidos.length})</summary><ul className="mt-3 grid sm:grid-cols-2 gap-2">{item.envolvidos.map(p=><li key={p.rhId} className="text-sm">{p.nome}{p.rhId===item.responsavelRhId?' · Responsável':''}<small className="block text-slate-500">{p.area} · ID RH: {p.rhId}</small></li>)}</ul></details>}
 {(!externo&&item.analise||item.solucao)&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Estudo e decisões</summary><div className="mt-3 space-y-3">{!externo&&item.analise&&<div><h3 className="font-medium">Análise interna</h3><p className="whitespace-pre-wrap text-sm">{item.analise}</p></div>}{item.solucao&&<div><h3 className="font-medium">Solução e decisões</h3><p className="whitespace-pre-wrap text-sm">{item.solucao}</p></div>}</div></details>}
 <section className="rounded-2xl border bg-white p-4 space-y-3"><h2 className="font-semibold text-lg">Plano de trabalho</h2>{!item.etapas.length&&<p className="text-sm text-slate-500">O responsável ainda está planejando as etapas.</p>}<div className="grid lg:grid-cols-2 gap-3">{item.etapas.map(e=><Etapa key={e.id} e={e} item={item} externo={externo} ocupado={ocupado} executar={executar}/>)}</div></section>
 <div className="grid lg:grid-cols-2 gap-4"><section className="rounded-2xl border bg-white p-4 space-y-3"><h2 className="font-semibold text-lg">Registros e contribuições</h2><form className="space-y-2" onSubmit={e=>{e.preventDefault();executar('registro',{texto,compartilhado}).then(ok=>{if(ok)setTexto('');});}}><Campo nome="Acrescentar atualização"><textarea className="input w-full min-h-24" required maxLength={5000} value={texto} disabled={ocupado} onChange={e=>setTexto(e.target.value)} placeholder="O que avançou? O que precisa de uma decisão?"/></Campo>{!externo&&item.tipo==='consultoria'&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={compartilhado} disabled={ocupado} onChange={e=>setCompartilhado(e.target.checked)}/>Compartilhar este registro com os convidados</label>}<button className="btn-primary" disabled={ocupado}>Adicionar registro</button></form><ol className="space-y-3 max-h-96 overflow-auto">{[...item.registros].reverse().map(r=><li className="border-t pt-3" key={r.id}><p className="text-sm whitespace-pre-wrap">{r.texto}</p><p className="text-xs text-slate-500 mt-1">{r.nome} · {quando(r.em)}{!externo?' · '+(r.compartilhado?'Compartilhado':'Interno'):''}</p></li>)}</ol></section>
 <section className="rounded-2xl border bg-white p-4 space-y-3"><h2 className="font-semibold text-lg">Arquivos ({item.anexos.length})</h2><p className="text-xs text-slate-500">PDF, JPG, PNG, WEBP, DOCX, XLSX ou PPTX. Até 5 MB por arquivo e 20 arquivos por processo.</p><Campo nome="Anexar arquivo"><input type="file" className="block w-full text-sm" accept=".pdf,.jpg,.jpeg,.png,.webp,.docx,.xlsx,.pptx" disabled={ocupado||item.anexos.length>=20} onChange={e=>{const f=e.target.files?.[0];e.target.value='';upload(f);}}/></Campo>{!externo&&<p className="text-xs text-slate-500">Novos anexos internos só aparecem no link após o gestor liberar.</p>}<ul className="space-y-3">{item.anexos.map(a=><li key={a.id} className="border-t pt-2"><button className="text-indigo-700 underline break-all text-left" disabled={ocupado} onClick={()=>abrir(a)}>{a.nome}</button><p className="text-xs text-slate-500">{a.nomeAutor} · {quando(a.em)}</p>{item.podeGerir&&item.tipo==='consultoria'&&<label className="flex gap-2 text-sm mt-1"><input type="checkbox" checked={a.compartilhado===true} disabled={ocupado} onChange={e=>executar('compartilhar',{arquivoId:a.id,compartilhado:e.target.checked})}/>Visível no link da consultoria</label>}</li>)}</ul></section></div>
 {item.podeGerir&&item.tipo==='consultoria'&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Links de colaboração</summary><div className="mt-3 space-y-3"><p className="text-sm text-slate-600">Crie um convite para cada pessoa. Quem tiver o link poderá consultar esta consultoria, acrescentar registros e arquivos e informar o andamento das etapas. O nome identifica o convite; o link não comprova a identidade de quem o usa. Você pode revogar o acesso a qualquer momento.</p><form className="space-y-3" onSubmit={e=>{e.preventDefault();executar('convidar',{nome,rhId,dias}).then(ok=>{if(ok){setNome('');setAceite(false);}});}}><div className="grid md:grid-cols-3 gap-3"><Campo nome="Pessoa do RH ou externo"><select className="input w-full" value={rhId} disabled={ocupado} onChange={e=>setRhId(e.target.value)}><option value="">Consultor externo</option>{item.envolvidos.map(p=><option key={p.rhId} value={p.rhId}>{p.nome}</option>)}</select></Campo>{!rhId&&<Campo nome="Nome do consultor"><input className="input w-full" value={nome} maxLength={180} required disabled={ocupado} onChange={e=>setNome(e.target.value)}/></Campo>}<Campo nome="Validade em dias"><input type="number" min={1} max={30} className="input w-full" value={dias} required disabled={ocupado} onChange={e=>setDias(e.target.value)}/></Campo></div><label className="flex gap-2 text-sm"><input type="checkbox" required checked={aceite} disabled={ocupado} onChange={e=>setAceite(e.target.checked)}/>Revisei objetivo, solução e etapas que serão visíveis neste link.</label><button className="btn-primary" disabled={ocupado||!aceite}>Criar link individual</button></form>
 {link&&<div className="bg-indigo-50 rounded-xl p-3 space-y-2"><p className="text-sm">Copie este link agora. O endereço completo não fica disponível para recuperação.</p><input className="input w-full" aria-label="Link de colaboração criado" readOnly value={link} onFocus={e=>e.target.select()}/><button className="btn-outline" onClick={async()=>{try{await navigator.clipboard.writeText(link);setAviso('Link copiado. Envie apenas ao convidado.');}catch{setErro('Selecione e copie o link acima.');}}}>Copiar link</button></div>}
 <ul className="space-y-2">{item.convites.map(c=><li className="flex flex-wrap justify-between gap-2 border-t pt-2 text-sm" key={c.id}><span>{c.nome} · {c.revogadoEm?'Revogado':Date.parse(c.expiraEm)<=Date.now()?'Expirado':'Válido até '+quando(c.expiraEm)}{c.rhId?' · ID RH: '+c.rhId:' · Convidado externo'}</span>{!c.revogadoEm&&Date.parse(c.expiraEm)>Date.now()&&<button className="btn-outline" disabled={ocupado} onClick={()=>executar('revogar',{conviteId:c.id}).then(ok=>{if(ok)setLink('');})}>Revogar</button>}</li>)}</ul></div></details>}
 {!externo&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Histórico do processo</summary><ol className="mt-3 max-h-64 overflow-auto space-y-2">{[...item.historico].reverse().map(h=><li className="text-sm" key={h.id}>{h.acao}<small className="block text-slate-500">{h.nome} · {quando(h.em)}</small></li>)}</ol></details>}
 </div>;
}
