import {useState} from 'react';
import {IMPLANTACOES} from '../../../supabase/functions/_shared/processos.mjs';
import {Campo,Opcoes} from './EditorProcesso.jsx';
export function CamposImplantacao({valor,mudar,ocupado}){
 return <fieldset className="processo-form"><legend className="font-semibold px-1">Implantação na empresa</legend><div className="processo-campos"><Campo nome="Situação da implantação"><select className="input" disabled={ocupado} value={valor.situacao} onChange={e=>mudar({...valor,situacao:e.target.value})}><Opcoes mapa={IMPLANTACOES}/></select></Campo><Campo nome="Data da implantação"><input className="input" type="date" required={valor.situacao==='implantada'} disabled={ocupado} value={valor.data} onChange={e=>mudar({...valor,data:e.target.value})}/></Campo></div><Campo nome="Como foi implantado / o que falta"><textarea className="input" required={valor.situacao==='implantada'} disabled={ocupado} maxLength={5000} value={valor.como} onChange={e=>mudar({...valor,como:e.target.value})}/></Campo><Campo nome="Resultado observado após a implantação"><textarea className="input" disabled={ocupado} maxLength={5000} value={valor.resultado||''} onChange={e=>mudar({...valor,resultado:e.target.value})}/></Campo><p className="processo-ajuda">Implantação informada no registro. A validação e a conclusão da etapa continuam com a equipe interna.</p></fieldset>;
}
export default function ImplantacaoProcesso({registro,ocupado,executar}){
 const [editando,setEditando]=useState(false),[valor,setValor]=useState(registro.implantacao||{situacao:'nao_iniciada',data:'',como:''});
 const i=registro.implantacao;
 return <div><h3>Implantação: {i?IMPLANTACOES[i.situacao]:'Não informada'}</h3>{i?.data&&<p className="text-sm">{i.data.split('-').reverse().join('/')}</p>}{i?.como&&<p className="text-sm whitespace-pre-wrap">{i.como}</p>}{i?.resultado&&<p className="text-sm whitespace-pre-wrap"><strong>Resultado observado: </strong>{i.resultado}</p>}{registro.podeAtualizar&&!editando&&<button className="btn-outline mt-2" disabled={ocupado} onClick={()=>{setValor(registro.implantacao||{situacao:'nao_iniciada',data:'',como:''});setEditando(true);}}>Atualizar implantação</button>}{editando&&<form onSubmit={e=>{e.preventDefault();executar('implantacao',{registroId:registro.id,implantacao:valor}).then(ok=>{if(ok)setEditando(false);});}}><CamposImplantacao valor={valor} mudar={setValor} ocupado={ocupado}/><div className="processo-linha"><button className="btn-primary" disabled={ocupado}>Salvar implantação</button><button type="button" className="btn-outline" disabled={ocupado} onClick={()=>setEditando(false)}>Cancelar implantação</button></div></form>}{!!registro.implantacoes?.length&&<details className="text-sm mt-2"><summary className="cursor-pointer">Histórico da implantação ({registro.implantacoes.length})</summary>{[...registro.implantacoes].reverse().map((x,i)=><p key={i} className="border-t py-2 whitespace-pre-wrap">{IMPLANTACOES[x.situacao]} · {x.nome} · {new Date(x.em).toLocaleString('pt-BR')}<br/>{x.como}{x.resultado&&<><br/>Resultado: {x.resultado}</>}</p>)}</details>}</div>;
}
