import {qualidade} from './AvaliacaoEtapa.jsx';
import {painelEtapas} from '../../lib/calc/painelEtapas.js';
const data=v=>v?v.split('-').reverse().join('/'):'Não informado';
export default function PainelEtapas({item}){
 const hoje=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date()),p=painelEtapas(item.etapas,hoje);
 return <section className="processo-painel"><h2>Implantação e tempo</h2><div className="processo-metricas">{[[p.progresso+'%','Progresso informado'],[p.prontas+'/'+p.total,'Etapas prontas'],[p.concluidas,'Validadas pela equipe'],[p.atrasadas,'Em aberto com atraso']].map(([v,n])=><div className="processo-metrica" key={n}><strong>{v}</strong><span>{n}</span></div>)}</div><p className="processo-ajuda">Progresso: média simples das etapas, com o mesmo peso. Prontas incluem as que aguardam conferência. {p.mediaDias===null?'Ainda não há etapas prontas com início e término para medir duração.':`Duração média: ${p.mediaDias.toLocaleString('pt-BR')} dias corridos (${p.medidas} etapa(s) com datas reais, contando início e término).`}</p>
 <div className={'processo-qualidade processo-qualidade-resumo '+(p.mediaQualidade===null?'':qualidade(p.mediaQualidade).classe)}><strong>{p.mediaQualidade===null?'Qualidade ainda não avaliada':`${p.mediaQualidade.toLocaleString('pt-BR')}/10 · ${qualidade(p.mediaQualidade).texto}`}</strong><span>{p.avaliadas} de {p.total} etapas avaliadas · {p.precisamMelhorar} precisa(m) melhorar</span><small>Média das últimas notas, com o mesmo peso. Etapas sem avaliação não entram na média.</small></div>
 <details className="mt-3" open><summary className="cursor-pointer font-semibold">Linha do tempo · previsto × realizado</summary><p className="processo-ajuda">{data(p.inicio)} a {data(p.fim)} · <span className="text-indigo-700">Roxo: previsto</span> · <span className="text-teal-700">Verde: realizado</span>. Sem início previsto, o roxo marca apenas o prazo.</p><div className="processo-tempo">{p.linhas.map(e=><div key={e.id} className="processo-tempo-linha"><div><strong>{e.titulo}</strong><small>{e.progresso}% · {e.pronta?'Pronta':'Em aberto'}{e.dias!==null?` · ${e.dias} dia(s)`:''}{e.atraso>0?` · ${e.atraso} dia(s) de atraso`:''}</small></div><div><div className="processo-trilho" title={`Previsto: ${data(e.inicioPrevisto)} a ${data(e.prazo)}`}>{e.previsto&&<span style={{left:e.previsto.left+'%',width:e.previsto.width+'%'}}/>}</div><div className="processo-trilho realizado" title={`Realizado: ${data(e.inicioReal)} a ${e.fimReal?data(e.fimReal):'em andamento'}`}>{e.inicioReal&&e.real&&<span style={{left:e.real.left+'%',width:e.real.width+'%'}}/>}</div><small>Prazo {data(e.prazo)} · início {data(e.inicioReal)} · término {data(e.fimReal)}</small></div></div>)}</div>{!p.total&&<p className="processo-vazio">Cadastre as etapas para visualizar o plano e acompanhar os resultados.</p>}</details></section>;
}
