import {useState} from 'react';
import {ESTADOS_ETAPA} from '../../../supabase/functions/_shared/processos.mjs';
import {Campo,Opcoes} from './EditorProcesso.jsx';
import AvaliacaoEtapa from './AvaliacaoEtapa.jsx';
import PainelEtapas from './PainelEtapas.jsx';
const data=v=>v?v.split('-').reverse().join('/'):'Não informado';
const nova=()=>({titulo:'',descricao:'',inicioPrevisto:'',prazo:'',inicioReal:'',fimReal:'',situacao:'pendente',progresso:0,dependeDe:[],nota:''});
export default function PlanoEtapas({item,externo,ocupado,executar}){
 const [editor,setEditor]=useState(null),mudar=(k,v)=>setEditor(x=>({...x,[k]:v}));
 const gerir=externo||item.podeGerir,aberto=!['cancelada','concluida'].includes(item.situacao);
 const estados={...ESTADOS_ETAPA,validacao:'Pronta para conferência',concluida:'Concluída e validada'};
 return <div className="space-y-3"><PainelEtapas item={item}/><section className="processo-painel"><div className="processo-linha"><div><h2>Plano de implantação</h2><p className="processo-ajuda">A consultoria cadastra as etapas e registra datas reais e progresso. A equipe interna valida a entrega.</p></div>{gerir&&aberto&&<button className="btn-primary" disabled={ocupado||!!editor} onClick={()=>setEditor(nova())}>+ Cadastrar etapa</button>}</div>
 {editor&&<form className="processo-form" onSubmit={e=>{e.preventDefault();executar('planejarEtapa',editor).then(ok=>{if(ok)setEditor(null);});}}><Campo nome="Nome da etapa"><input className="input" required maxLength={180} value={editor.titulo} disabled={ocupado||!gerir} onChange={e=>mudar('titulo',e.target.value)}/></Campo><Campo nome="O que será implantado"><textarea className="input" maxLength={5000} value={editor.descricao} disabled={ocupado||!gerir} onChange={e=>mudar('descricao',e.target.value)}/></Campo><div className="processo-campos"><Campo nome="Início previsto"><input className="input" type="date" value={editor.inicioPrevisto} disabled={ocupado||!gerir} onChange={e=>mudar('inicioPrevisto',e.target.value)}/></Campo><Campo nome="Prazo previsto"><input className="input" type="date" required value={editor.prazo} disabled={ocupado||!gerir} onChange={e=>mudar('prazo',e.target.value)}/></Campo><Campo nome="Início real"><input className="input" type="date" value={editor.inicioReal} disabled={ocupado} onChange={e=>mudar('inicioReal',e.target.value)}/></Campo><Campo nome="Término real"><input className="input" type="date" value={editor.fimReal} disabled={ocupado} onChange={e=>mudar('fimReal',e.target.value)}/></Campo><Campo nome="Situação da etapa"><select className="input" value={editor.situacao} disabled={ocupado} onChange={e=>setEditor(x=>({...x,situacao:e.target.value,progresso:['validacao','concluida'].includes(e.target.value)?100:e.target.value==='pendente'?0:x.progresso===100?0:x.progresso}))}><Opcoes mapa={Object.fromEntries(Object.entries(estados).filter(([k])=>!externo||k!=='concluida'))}/></select></Campo><Campo nome="Progresso informado (%)"><input className="input" type="number" min={0} max={100} step={1} required value={editor.progresso} disabled={ocupado||['pendente','validacao','concluida'].includes(editor.situacao)} onChange={e=>mudar('progresso',Number(e.target.value))}/></Campo></div><Campo nome="Andamento / motivo do bloqueio"><textarea className="input" value={editor.nota} required={editor.situacao==='bloqueada'} maxLength={5000} disabled={ocupado} onChange={e=>mudar('nota',e.target.value)}/></Campo>
 <details><summary className="cursor-pointer font-medium">Dependências · só iniciar depois de concluir</summary><div className="grid sm:grid-cols-2 gap-2 mt-2">{item.etapas.filter(e=>e.id!==editor.etapaId).map(e=><label key={e.id} className="flex gap-2"><input type="checkbox" disabled={ocupado||!gerir} checked={editor.dependeDe.includes(e.id)} onChange={v=>mudar('dependeDe',v.target.checked?[...editor.dependeDe,e.id]:editor.dependeDe.filter(x=>x!==e.id))}/>{e.titulo}</label>)}</div></details><p className="processo-ajuda">O prazo previsto vai para o calendário. Datas reais registram o que aconteceu. Etapa pronta exige início e término; a conclusão é validada internamente.</p><div className="processo-linha"><button className="btn-primary" disabled={ocupado}>Salvar etapa</button><button className="btn-outline" type="button" disabled={ocupado} onClick={()=>setEditor(null)}>Cancelar etapa</button></div></form>}
 <div className="grid md:grid-cols-2 gap-3">{item.etapas.map(e=><article className="rounded-xl border p-3 space-y-2" key={e.id}><div className="processo-linha"><h3>{e.titulo}</h3><span className={"processo-chip estado-"+e.situacao}>{estados[e.situacao]}</span></div><p className="text-sm">{e.responsavel||item.envolvidos?.find(p=>p.rhId===e.responsavelRhId)?.nome} · Prazo {data(e.prazo)}</p><p className="processo-ajuda">Início {data(e.inicioReal)} · Término {data(e.fimReal)} · {['validacao','concluida'].includes(e.situacao)?100:e.progresso||0}%</p><details><summary className="cursor-pointer text-sm">Descrição e andamento</summary><p className="text-sm whitespace-pre-wrap mt-2">{e.descricao||'Sem descrição.'}</p>{e.nota&&<p className="text-sm whitespace-pre-wrap mt-2">{e.nota}</p>}{e.planejadaPor&&<p className="processo-ajuda">Planejada por {e.planejadaPor}</p>}{e.dependeDe.length>0&&<p className="processo-ajuda">Depende de: {e.dependeDe.map(id=>item.etapas.find(x=>x.id===id)?.titulo).join(', ')}</p>}</details>{(gerir||item.meuRhId===e.responsavelRhId)&&aberto&&(!externo||e.situacao!=='concluida')&&<button className="btn-outline" disabled={ocupado||!!editor} onClick={()=>setEditor({...nova(),...e,etapaId:e.id,progresso:['validacao','concluida'].includes(e.situacao)?100:e.progresso||0})}>Atualizar etapa e datas</button>}<AvaliacaoEtapa etapa={e} podeAvaliar={!externo&&item.podeGerir} ocupado={ocupado} executar={executar}/></article>)}</div>
 </section></div>;
}
