import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {acaoMubisys} from '../services/crm.js';
import {podeAbrir,getSessao} from '../lib/sessao.js';
import {ymdLocal} from '../lib/format.js';
import './acoes-mubisys.css';
const ROTULOS={mover:'Mudar fase',anotar:'Registrar anotação',tarefa:'Agendar tarefa',criar:'Criar oportunidade'};
const ESTADOS={concluido:'Confirmado',recusado:'Não realizado',enviando:'Aguardando confirmação',incerto:'Conferir no Mubisys'};

export function HistoricoMubisys({revisao=0}){
 const [aberto,setAberto]=useState(false),[itens,setItens]=useState([]),[erro,setErro]=useState(''),[carregando,setCarregando]=useState(false),[n,setN]=useState(0),[alvo,setAlvo]=useState(null),[justificativa,setJustificativa]=useState(''),[conferencia,setConferencia]=useState(''),[salvando,setSalvando]=useState(false);
 const s=getSessao(),direcao=s?.master||s?.permissoes?.includes('*');
 useEffect(()=>{if(!aberto)return;let vivo=true;setCarregando(true);setErro('');acaoMubisys('historico').then(r=>{if(vivo)setItens(r.operacoes);}).catch(e=>{if(vivo)setErro(e.message);}).finally(()=>{if(vivo)setCarregando(false);});return()=>{vivo=false;};},[aberto,n,revisao]);
 async function resolver(e){e.preventDefault();if(salvando)return;setSalvando(true);setErro('');try{await acaoMubisys('resolver',{operacaoId:alvo.id,justificativa,conferencia});setAlvo(null);setN(x=>x+1);}catch(e){setErro(e.message);}finally{setSalvando(false);}}
 return <section className="mubi-historico"><button type="button" className="btn-outline" aria-expanded={aberto} onClick={()=>setAberto(x=>!x)}>Histórico de ações no Mubisys</button>{aberto&&<div className="mubi-painel"><div className="mubi-cab"><h3>Últimos 50 envios</h3><button type="button" className="btn-ghost" disabled={carregando} onClick={()=>setN(x=>x+1)}>{carregando?'Consultando…':'Atualizar histórico'}</button></div>{erro&&<p role="alert" className="c360-notice">{erro}</p>}{!carregando&&!itens.length&&<p>Nenhum envio registrado pelo painel.</p>}{itens.map(o=><article key={o.id} className="mubi-registro"><strong>{ROTULOS[o.action]||'Ação'} · {o.titulo}</strong><p>{ESTADOS[o.estado]||o.estado} · {new Date(o.criadoEm).toLocaleString('pt-BR')}</p>{o.resultado?.mensagem&&<p>{o.resultado.mensagem}</p>}{['incerto','enviando'].includes(o.estado)&&<><p>Confira o registro no Mubisys antes de tentar novamente. O painel não repete este envio.</p>{direcao&&<button type="button" className="btn-outline" onClick={()=>{setAlvo(o);setConferencia('');setJustificativa('');}}>Registrar conferência</button>}</>}</article>)}{alvo&&<form className="mubi-form" onSubmit={resolver}><h4>Conferência: {alvo.titulo}</h4><p>Abra o Mubisys e verifique se esta ação existe. Sua confirmação libera novos envios; não executa a ação outra vez.</p><label>Resultado<select className="input" required value={conferencia} onChange={e=>setConferencia(e.target.value)}><option value="">Selecione após conferir</option><option value="aplicado">A ação foi realizada no Mubisys</option><option value="naoAplicado">Conferi: a ação não foi realizada</option></select></label><label>O que você conferiu<textarea className="input" required minLength={20} maxLength={1000} value={justificativa} onChange={e=>setJustificativa(e.target.value)}/></label><button className="btn-primary" disabled={salvando}>{salvando?'Registrando…':'Salvar conferência'}</button><button type="button" className="btn-ghost" onClick={()=>setAlvo(null)}>Cancelar</button></form>}</div>}</section>;
}

export default function AcoesMubisys({cardId,clienteId,cliente,soTarefa=false,aoConcluir}){
 const [aberto,setAberto]=useState(false),[action,setAction]=useState(clienteId&&!cardId?'criar':soTarefa?'tarefa':'anotar'),[opcoes,setOpcoes]=useState(null),[card,setCard]=useState(null),[erro,setErro]=useState(''),[carregando,setCarregando]=useState(false),[salvando,setSalvando]=useState(false),[operacao,setOperacao]=useState(null),[incerto,setIncerto]=useState(false),[tentativa,setTentativa]=useState(0),[hist,setHist]=useState(0);
 const envio=useRef(false),id=useRef(null);
 const [f,setF]=useState({grupoId:'',faseId:'',responsavelId:'',grupoTarefaId:'',titulo:'',descricao:'',texto:'',valor:'0',data:ymdLocal(new Date()),hora:'09:00',dataFim:ymdLocal(new Date()),horaFim:'09:30',tipo:'Telefone'});
 const campo=(nome,v)=>setF(x=>({...x,[nome]:v}));
 useEffect(()=>{if(!aberto)return;let vivo=true;setCarregando(true);setErro('');Promise.all([acaoMubisys('opcoes'),cardId?acaoMubisys('detalhe',{cardId}):Promise.resolve(null)]).then(([o,d])=>{if(!vivo)return;setOpcoes(o);setCard(d?.card||null);setF(x=>({...x,grupoId:String(d?.card?.grupo?.id||o.grupos?.[0]?.id||''),faseId:String(d?.card?.fase?.id||o.grupos?.[0]?.fases?.[0]?.id||''),responsavelId:o.meuUsuarioId||'',grupoTarefaId:o.gruposTarefa?.[0]?.id||''}));}).catch(e=>{if(vivo)setErro(e.message);}).finally(()=>{if(vivo)setCarregando(false);});return()=>{vivo=false;};},[aberto,cardId,tentativa]);
 const grupos=opcoes?.grupos||[],fases=grupos.find(g=>String(g.id)===f.grupoId)?.fases||[];
 const travado=salvando||incerto||!!operacao;
 const tarefaIndisponivel=action==='tarefa'&&opcoes&&!opcoes.gruposTarefa.length;
 async function enviar(e){e.preventDefault();if(envio.current||travado)return;envio.current=true;setSalvando(true);setErro('');id.current||=crypto.randomUUID();
  try{const r=await acaoMubisys(action,{...f,valor:Number(f.valor),cardId,clienteId,grupoAnterior:card?.grupo?.id,faseAnterior:card?.fase?.id,operacaoId:id.current});setOperacao(r.operacao);setHist(n=>n+1);if(r.operacao?.estado==='concluido'){aoConcluir?.();if(cardId)acaoMubisys('detalhe',{cardId}).then(r=>setCard(r.card)).catch(()=>{});}}
  catch(e){setErro(e.message);if(e.enviado!==false&&(!e.status||e.status>=500)){setIncerto(true);setHist(n=>n+1);}else{id.current=null;}}
  finally{setSalvando(false);envio.current=false;}
 }
 function novaAcao(){id.current=null;setOperacao(null);setIncerto(false);setErro('');setTentativa(x=>x+1);setF(x=>({...x,texto:'',titulo:'',descricao:''}));}
 return <section className="mubi-acoes"><button type="button" className="btn-outline" aria-expanded={aberto} onClick={()=>setAberto(x=>!x)}>{clienteId&&!cardId?'Nova oportunidade no Mubisys':soTarefa?'Agendar no Mubisys':'Ações no Mubisys'}</button>{aberto&&<div className="mubi-painel"><div className="mubi-cab"><div><span className="c360-eyebrow">Mubisys · ações comerciais</span><h3>{card?.titulo||cliente||'Oportunidade'}</h3>{card&&<p>Fase conferida agora: <strong>{card.fase?.nome}</strong></p>}</div><button className="btn-ghost" type="button" onClick={()=>setAberto(false)} aria-label="Recolher ações">Recolher</button></div>
 {carregando&&<p role="status">Conferindo oportunidade e opções no Mubisys…</p>}{erro&&<p role="alert" className="c360-notice">{erro}</p>}{!carregando&&!opcoes&&<button type="button" className="btn-outline" onClick={()=>setTentativa(n=>n+1)}>Tentar carregar novamente</button>}
 {opcoes&&!carregando&&<>{cardId&&!soTarefa&&<div className="mubi-escolhas">{['anotar','mover',...(podeAbrir('compromissos')?['tarefa']:[])].map(a=><button type="button" className="chip-btn" disabled={travado} aria-pressed={action===a} key={a} onClick={()=>setAction(a)}>{ROTULOS[a]}</button>)}</div>}
 {tarefaIndisponivel&&<p role="status" className="c360-notice">{opcoes.avisoTarefas||'Nenhum grupo de tarefas foi disponibilizado pelo Mubisys. Cadastre um grupo no ERP para enviar tarefas.'} Você pode continuar agendando acompanhamentos no painel.</p>}
 <form className="mubi-form" onSubmit={enviar}><fieldset disabled={travado||tarefaIndisponivel}><legend>{ROTULOS[action]}</legend>
 {['mover','criar'].includes(action)&&<div className="mubi-cols"><label>Funil<select className="input" required value={f.grupoId} onChange={e=>{campo('grupoId',e.target.value);campo('faseId',String(grupos.find(g=>String(g.id)===e.target.value)?.fases?.[0]?.id||''));}}><option value="">Selecione</option>{grupos.map(g=><option key={g.id} value={g.id}>{g.nome}</option>)}</select></label><label>Fase de destino<select className="input" required value={f.faseId} onChange={e=>campo('faseId',e.target.value)}><option value="">Selecione</option>{fases.map(g=><option key={g.id} value={g.id}>{g.nome}</option>)}</select></label></div>}
 {action==='anotar'&&<label>Anotação<textarea className="input" rows={3} required maxLength={4000} value={f.texto} onChange={e=>campo('texto',e.target.value)} placeholder="O que foi conversado e qual será o próximo passo"/></label>}
 {['tarefa','criar'].includes(action)&&<><label>Título<input className="input" required maxLength={200} value={f.titulo} onChange={e=>campo('titulo',e.target.value)}/></label><label>Descrição<textarea className="input" required={action==='criar'} maxLength={4000} value={f.descricao} onChange={e=>campo('descricao',e.target.value)}/></label></>}
 {action==='criar'&&<div className="mubi-cols"><label>Responsável<select className="input" required value={f.responsavelId} onChange={e=>campo('responsavelId',e.target.value)}><option value="">Selecione</option>{opcoes.usuarios.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select></label><label>Valor da oportunidade (R$)<input className="input" required type="number" min="0" max="1000000000" step="0.01" value={f.valor} onChange={e=>campo('valor',e.target.value)}/></label></div>}
 {action==='tarefa'&&<><div className="mubi-cols"><label>Grupo de tarefas<select className="input" required value={f.grupoTarefaId} onChange={e=>campo('grupoTarefaId',e.target.value)}><option value="">Selecione</option>{opcoes.gruposTarefa.map(g=><option key={g.id} value={g.id}>{g.nome}</option>)}</select></label><label>Tipo<select className="input" value={f.tipo} onChange={e=>campo('tipo',e.target.value)}>{['Telefone','Mensagem','Email','Outros'].map(t=><option key={t}>{t}</option>)}</select></label></div><div className="mubi-cols">{[['data','Início','date'],['hora','Hora inicial','time'],['dataFim','Término','date'],['horaFim','Hora final','time']].map(([k,l,t])=><label key={k}>{l}<input className="input" type={t} required value={f[k]} onChange={e=>campo(k,e.target.value)}/></label>)}</div><p>A tarefa será criada no Mubisys e aparecerá na sua agenda do painel após a confirmação. O tipo escolhido não envia mensagens. Conclusão e remarcação na agenda valem somente no painel.</p></>}
 <button className="btn-primary" disabled={carregando||travado}>{salvando?'Enviando uma única vez…':`${ROTULOS[action]} no Mubisys`}</button></fieldset></form></>}
 {operacao&&<div role="status" className="mubi-resultado"><strong>{ESTADOS[operacao.estado]||'Conferir envio'}</strong><p>{operacao.resultado?.mensagem||(['incerto','enviando'].includes(operacao.estado)?'Consulte o histórico e confira no Mubisys antes de tentar novamente.':'Consulte o histórico para ver o resultado deste envio.')}</p>{action==='tarefa'&&operacao.estado==='concluido'&&<Link className="btn-outline" to="/compromissos">Ver compromisso na agenda</Link>}{['concluido','recusado'].includes(operacao.estado)&&<button type="button" className="btn-outline" onClick={novaAcao}>Preparar outra ação</button>}</div>}
 {incerto&&<p role="status" className="c360-notice">A conexão não confirmou o resultado. Confira o histórico abaixo. Não envie novamente esta ação.</p>}<HistoricoMubisys revisao={hist}/></div>}</section>;
}

export function AgendaMubisys({aoConcluir}){
 const [aberto,setAberto]=useState(false),[cards,setCards]=useState(null),[erro,setErro]=useState(''),[id,setId]=useState('');
 useEffect(()=>{if(!aberto)return;let vivo=true;setErro('');acaoMubisys('opcoes').then(r=>{if(vivo)setCards(r.cards);}).catch(e=>{if(vivo)setErro(e.message);});return()=>{vivo=false;};},[aberto]);
 return <section className="mubi-painel"><div className="mubi-cab"><div><h2 className="text-lg font-bold">Agenda conectada ao comercial</h2><p>Agende uma tarefa em uma oportunidade do Mubisys e acompanhe o retorno aqui.</p></div><button type="button" className="btn-outline" aria-expanded={aberto} onClick={()=>setAberto(x=>!x)}>Tarefa no Mubisys</button></div>{aberto&&<>{erro&&<p role="alert" className="c360-notice">{erro}</p>}{!cards&&!erro&&<p role="status">Consultando oportunidades…</p>}{cards&&<label className="mubi-form">Oportunidade ativa<select className="input" value={id} onChange={e=>setId(e.target.value)}><option value="">Selecione a oportunidade</option>{cards.map(c=><option key={c.id} value={c.id}>{c.cliente} · {c.titulo}</option>)}</select></label>}{cards&&!cards.length&&<p>Nenhuma oportunidade atribuída a você na última carga.</p>}{id&&<AcoesMubisys key={id} cardId={id} soTarefa aoConcluir={aoConcluir}/>}<HistoricoMubisys/></>}</section>;
}
