import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {acaoMubisys} from '../services/crm.js';
import {lerCompromissos,salvarCompromisso} from '../services/compromissos.js';
import {getSessao,podeAbrir} from '../lib/sessao.js';
import {ymdLocal} from '../lib/format.js';
import {contatosFinanceiros,titulosPorDocumento,proximaConferencia} from '../lib/calc/contatoCobranca.js';
import './acoes-mubisys.css';
const ESTADO={semDocumento:'Título sem CPF/CNPJ válido.',naoLocalizado:'Documento não encontrado no cadastro.',ambiguo:'Mais de um cadastro usa este documento. Confira no Mubisys antes de escolher o contato.',tituloNaoLocalizado:'Título não está na última carga.',indisponivel:'Cadastro indisponível nesta consulta.'};
export default function AcompanhamentoCobranca({cliente:c}){
 const [contatos,setContatos]=useState(null),[buscando,setBuscando]=useState(false),[erro,setErro]=useState(''),[agendaErro,setAgendaErro]=useState(''),[id,setId]=useState(''),[existente,setExistente]=useState(null),[agendaPronta,setAgendaPronta]=useState(false),[carregar,setCarregar]=useState(0),[salvando,setSalvando]=useState(false),[salvo,setSalvo]=useState(false);
 const [data,setData]=useState(proximaConferencia(c.desfecho?.promessa,ymdLocal(new Date()))),[hora,setHora]=useState('09:00'),[obs,setObs]=useState('');const trava=useRef(false);
 const agenda=podeAbrir('compromissos'),usuario=getSessao()?.usuario||'';
 useEffect(()=>{if(!agenda)return;let vivo=true;setAgendaPronta(false);setAgendaErro('');Promise.all([crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify([usuario,c.chave]))),lerCompromissos()]).then(([hash,mapa])=>{if(!vivo)return;const chave='cob-'+[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');setId(chave);setExistente(mapa[chave]||null);if(mapa[chave]){setData(mapa[chave].data||ymdLocal(new Date()));setHora(mapa[chave].hora||'09:00');setObs(mapa[chave].obs||'');}setAgendaPronta(true);}).catch(e=>{if(vivo)setAgendaErro(e.message);});return()=>{vivo=false;};},[agenda,usuario,c.chave,carregar]);
 async function buscar(){if(buscando)return;setBuscando(true);setErro('');try{const ts=titulosPorDocumento(c.titulos);if(!ts.length){setContatos([{estado:'semDocumento'}]);return;}if(ts.length>8){setErro('Há muitos documentos neste agrupamento. Confira os títulos individualmente antes de escolher um contato.');return;}const rs=await Promise.all(ts.map(t=>acaoMubisys('contatoCobranca',{tituloId:t.id}).then(r=>({...r,tituloId:t.id}))));setContatos(rs);}catch(e){setErro(e.message);}finally{setBuscando(false);}}
 async function salvar(e){e.preventDefault();if(trava.current||!agendaPronta)return;trava.current=true;setSalvando(true);setAgendaErro('');setSalvo(false);try{const mapa=await salvarCompromisso(id,{titulo:`Conferir cobrança — ${c.cliente}`,tipo:'cobranca',cliente:c.cliente,data,hora,obs,feito:false,cobrancaOrigem:c.chave,cobrancaTitulos:c.titulos.map(t=>String(t.id))});setExistente(mapa[id]);setSalvo(true);}catch(e){setAgendaErro(e.message);}finally{trava.current=false;setSalvando(false);}}
 return <section className="mubi-painel"><div className="mubi-cab"><div><h3>Contato e próximo acompanhamento</h3><p>Confira o recebimento antes de cobrar novamente. Uma promessa não confirma pagamento.</p></div><button type="button" className="btn-outline" disabled={buscando} onClick={buscar}>{buscando?'Consultando cadastro…':'Buscar contato financeiro'}</button></div>{erro&&<p role="alert" className="c360-notice">{erro}</p>}{contatos?.map((r,i)=><div key={r.tituloId||i}>{r.estado!=='encontrado'?<p className="c360-notice">{ESTADO[r.estado]||'Contato indisponível.'}</p>:<><h4 className="font-semibold mt-3">{r.cliente.nome} · título #{r.tituloId}</h4><div className="cob-contato">{contatosFinanceiros(r.cliente).map(t=><div key={t.id}><strong>{t.nome||'Contato'}{t.financeiro?' · Financeiro':' · Geral'}</strong><span>{t.celular}</span><span>{t.email}</span></div>)}</div>{!contatosFinanceiros(r.cliente).length&&<p>Cadastro sem telefone ou e-mail disponível.</p>}<p>Cadastro de {new Date(r.atualizadoEm).toLocaleString('pt-BR')}. Nenhuma mensagem é enviada pelo painel.</p></>}</div>)}
 {agenda?<><form className="mubi-form" onSubmit={salvar}><h4 className="font-semibold">{existente?'Atualizar acompanhamento na agenda':'Agendar acompanhamento na agenda'}</h4>{existente&&<p>Já existe um acompanhamento para este cliente na sua agenda{existente.feito?' (concluído; salvar irá reabri-lo)':''}. Salvar atualiza esse registro.</p>}{c.desfecho?.promessa&&!existente&&<p>Data sugerida: dia seguinte à promessa, para conferir se o pagamento entrou.</p>}<fieldset disabled={salvando||!agendaPronta}><div className="mubi-cols"><label>Data<input className="input" type="date" required value={data} onChange={e=>setData(e.target.value)}/></label><label>Horário<input className="input" type="time" required value={hora} onChange={e=>setHora(e.target.value)}/></label></div><label>Próximo passo<textarea className="input" rows={2} maxLength={4000} value={obs} onChange={e=>setObs(e.target.value)} placeholder="Ex.: conferir entrada do pagamento e depois retornar ao financeiro"/></label><button className="btn-primary">{salvando?'Salvando…':existente?'Atualizar acompanhamento':'Salvar acompanhamento'}</button></fieldset></form>{agendaErro&&<p role="alert" className="c360-notice">{agendaErro} {!agendaPronta&&<button type="button" className="btn-ghost" onClick={()=>setCarregar(n=>n+1)}>Recarregar agenda</button>}</p>}{salvo&&<p role="status">Acompanhamento salvo na sua agenda. <Link className="btn-outline" to="/compromissos">Ver Compromissos</Link></p>}</>:<p>O agendamento exige acesso ao módulo Compromissos.</p>}</section>;
}
