import {useEffect,useRef,useState} from 'react';
import {useLocation} from 'react-router-dom';
import {podeAbrir} from '../lib/sessao.js';
import {lerPermutas,mexerNaPermuta} from '../services/permutas.js';
import {lerCampanhas,mexerNaCampanha} from '../services/campanhas.js';
import {lerAtalhos,salvarAtalho,removerAtalho} from '../services/marketing.js';

export const ConfiguracaoPermutas=()=> <ConfiguracaoPeriodo modulo="permutas"/>;
export const ConfiguracaoCampanhas=()=> <ConfiguracaoPeriodo modulo="campanhas"/>;
function ConfiguracaoPeriodo({modulo}){
 const campanha=modulo==='campanhas', rotulo=campanha?'Campanha':'Permuta', parametro=campanha?'campanha':'permuta', ler=campanha?lerCampanhas:lerPermutas, mexer=campanha?mexerNaCampanha:mexerNaPermuta;
 const autorizado=podeAbrir(modulo);const local=useLocation();const [mapa,setMapa]=useState(null),[id,setId]=useState(()=>new URLSearchParams(local.search).get(parametro)||''),[erro,setErro]=useState(''),[ok,setOk]=useState(''),[ocupado,setOcupado]=useState(false),[tentativa,setTentativa]=useState(0),[datas,setDatas]=useState({desde:'',ate:''});const trava=useRef(false);
 useEffect(()=>{if(!autorizado)return;let vivo=true;setErro('');ler().then(m=>{if(vivo)setMapa(m);}).catch(e=>{if(vivo)setErro(e.message);});return()=>{vivo=false;};},[autorizado,tentativa,ler]);
 useEffect(()=>{const alvo=new URLSearchParams(local.search).get(parametro);if(alvo)setId(alvo);},[local.search,parametro]);
 useEffect(()=>{setDatas({desde:mapa?.[id]?.desde||'',ate:mapa?.[id]?.ate||'',...(campanha?{meta:mapa?.[id]?.meta||0}:{})});},[id,mapa,campanha]);
 async function salvar(e){e.preventDefault();if(trava.current)return;if(campanha&&(datas.meta===''||!Number.isFinite(Number(datas.meta))||Number(datas.meta)<0)){setErro('Informe uma meta igual ou maior que zero.');return;}if(datas.desde&&datas.ate&&datas.ate<datas.desde){setErro('A data final precisa ser igual ou posterior à inicial.');return;}trava.current=true;setOcupado(true);setErro('');setOk('');try{const m=await mexer(id,{campos:{...datas,...(campanha?{meta:Number(datas.meta)}:{})}});setMapa(m);setOk('Ajustes salvos. A busca de O.S. usará essas datas.');}catch(e){setErro(e.message);}finally{trava.current=false;setOcupado(false);}}
 if(!autorizado)return <p className="config-aviso">É necessário acesso ao módulo {campanha?'Campanhas':'Permutas'} para editar estes ajustes.</p>;
 return <div className="config-editor">{erro&&<p role="alert" className="c360-notice">{erro} {!mapa&&<button type="button" className="btn-ghost" onClick={()=>setTentativa(n=>n+1)}>Tentar novamente</button>}</p>}{!mapa&&!erro&&<p role="status">Carregando {campanha?'campanhas':'permutas'}…</p>}{mapa&&<><label>{rotulo}<select aria-label={rotulo} className="input" disabled={ocupado} value={id} onChange={e=>setId(e.target.value)}><option value="">Selecione</option>{Object.entries(mapa).sort((a,b)=>String(a[1].nome).localeCompare(String(b[1].nome))).map(([k,p])=><option key={k} value={k}>{p.nome}{campanha&&p.ano?` (${p.ano})`:''}{p.encerrada?' · encerrada':''}</option>)}</select></label>{!Object.keys(mapa).length&&<p className="config-aviso">Nenhum registro cadastrado.</p>}{id&&mapa[id]&&<form className="config-editor" onSubmit={salvar}><fieldset disabled={ocupado} className="grid gap-4 sm:grid-cols-2"><label>Início do período<input className="input" type="date" value={datas.desde} onChange={e=>setDatas(d=>({...d,desde:e.target.value}))}/></label><label>Fim do período<input className="input" type="date" value={datas.ate} onChange={e=>setDatas(d=>({...d,ate:e.target.value}))}/></label>{campanha&&<label>Meta do evento (R$)<input className="input" type="number" min="0" step="0.01" required value={datas.meta??0} onChange={e=>setDatas(d=>({...d,meta:e.target.value}))}/></label>}</fieldset><p className="config-aviso">Datas vazias consideram todo o histórico disponível. Mudar o período altera a busca de O.S.; as O.S. já aceitas e os lançamentos continuam no registro.</p><button className="btn-primary justify-self-start" disabled={ocupado}>{ocupado?'Salvando…':campanha?'Salvar ajustes':'Salvar período'}</button></form>}</>}{ok&&<p role="status">{ok}</p>}</div>;
}

export function ConfiguracaoMarketing(){
 const autorizado=podeAbrir('marketing');const [mapa,setMapa]=useState(null),[nome,setNome]=useState(''),[url,setUrl]=useState(''),[erro,setErro]=useState(''),[ok,setOk]=useState(''),[ocupado,setOcupado]=useState(false),[tentativa,setTentativa]=useState(0);const trava=useRef(false),idNovo=useRef(null);
 useEffect(()=>{if(!autorizado)return;let vivo=true;setErro('');lerAtalhos().then(m=>{if(vivo)setMapa(m);}).catch(e=>{if(vivo)setErro(e.message);});return()=>{vivo=false;};},[autorizado,tentativa]);
 async function salvar(e){e.preventDefault();if(trava.current)return;let endereco;try{endereco=new URL(/^https?:\/\//i.test(url.trim())?url.trim():'https://'+url.trim());if(!['http:','https:'].includes(endereco.protocol)||!endereco.hostname.includes('.'))throw new Error();}catch{setErro('Informe um endereço válido, começando com https://.');return;}
 trava.current=true;setOcupado(true);setErro('');setOk('');idNovo.current||='ml-'+crypto.randomUUID();try{const id=idNovo.current;await salvarAtalho(id,{nome:nome.trim(),url:endereco.href});setMapa(m=>({...m,[id]:{nome:nome.trim(),url:endereco.href}}));idNovo.current=null;setNome('');setUrl('');setOk('Atalho salvo e disponível em Marketing.');}catch(e){setErro(e.message);}finally{trava.current=false;setOcupado(false);}}
 async function remover(id){if(trava.current||!window.confirm('Remover este atalho do Marketing?'))return;trava.current=true;setOcupado(true);setErro('');setOk('');try{await removerAtalho(id);setMapa(m=>{const n={...m};delete n[id];return n;});setOk('Atalho removido.');}catch(e){setErro(e.message);}finally{trava.current=false;setOcupado(false);}}
 if(!autorizado)return <p className="config-aviso">É necessário acesso ao módulo Marketing para editar estes ajustes.</p>;
 return <div className="config-editor">{erro&&<p role="alert" className="c360-notice">{erro} {!mapa&&<button type="button" className="btn-ghost" onClick={()=>setTentativa(n=>n+1)}>Tentar novamente</button>}</p>}{!mapa&&!erro&&<p role="status">Carregando atalhos…</p>}{mapa&&<><div className="config-editor-lista">{Object.entries(mapa).filter(([,a])=>a.nome&&a.url&&!a.tipo).map(([id,a])=><div key={id}><a href={/^https?:\/\//i.test(a.url)?a.url:undefined} target="_blank" rel="noopener noreferrer">{a.nome}</a><button type="button" className="btn-ghost" disabled={ocupado} onClick={()=>remover(id)} aria-label={`Remover atalho ${a.nome}`}>Remover</button></div>)}</div><form onSubmit={salvar} className="config-editor"><fieldset disabled={ocupado} className="grid gap-4 sm:grid-cols-2"><label>Nome do atalho<input className="input" required maxLength={200} value={nome} onChange={e=>setNome(e.target.value)} placeholder="Ex.: Fotos de obras"/></label><label>Endereço do Drive<input className="input" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://drive.google.com/…"/></label></fieldset><button className="btn-primary justify-self-start" disabled={ocupado}>{ocupado?'Salvando…':'Adicionar atalho'}</button></form></>}{ok&&<p role="status">{ok}</p>}</div>;
}
