import {useMemo,useState} from 'react';
import {moeda,dataCurta} from '../lib/format.js';
import './cliente360.css';
export default function FunilMubisys({crm,erro,carregando,aoAtualizar,aoCliente}){
 const [grupo,setGrupo]=useState(''),[fase,setFase]=useState(''),[busca,setBusca]=useState(''),[responsavel,setResponsavel]=useState(''),[limite,setLimite]=useState(20);
 const grupoAtual=grupo||crm?.grupos?.[0]?.id||'';
 const base=useMemo(()=>(crm?.cards||[]).filter(c=>c.grupoId===grupoAtual),[crm,grupoAtual]);
 const rs=[...new Set(base.map(c=>c.responsavel).filter(Boolean))].sort();
 const normal=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const filtrados=base.filter(c=>(!responsavel||c.responsavel===responsavel)&&normal(`${c.cliente} ${c.titulo} ${c.origem}`).includes(normal(busca)));
 const lista=filtrados.filter(c=>!fase||c.faseId===fase).sort((a,b)=>String(a.ultimaInteracao||a.criadoEm).localeCompare(String(b.ultimaInteracao||b.criadoEm)));
 return <section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Funil do Mubisys</h2><p className="text-sm text-slate-500">Oportunidades ativas, nas fases reais da equipe. Valores separados das propostas.</p></div><button className="btn-outline" disabled={carregando} onClick={aoAtualizar}>{carregando?'Consultando…':'Atualizar visualização'}</button></div>
 {erro&&<p role="alert" className="c360-notice">{erro}{crm?' A última consulta continua visível.':''}</p>}
 {crm&&<><p className="text-xs text-slate-500">Última carga: {new Date(crm.atualizadoEm).toLocaleString('pt-BR')} · integração de leitura · atualização programada a cada 2 horas{Date.now()-Date.parse(crm.atualizadoEm)>3*3600000?' · carga atrasada':''}</p><div className="crm-toolbar"><label className="label">Funil<select className="input" value={grupoAtual} onChange={e=>{setGrupo(e.target.value);setFase('');setResponsavel('');setLimite(20);}}>{crm.grupos.map(g=><option key={g.id} value={g.id}>{g.nome}</option>)}</select></label><label className="label">Responsável<select className="input" value={responsavel} onChange={e=>{setResponsavel(e.target.value);setLimite(20);}}><option value="">Todos</option>{rs.map(r=><option key={r}>{r}</option>)}</select></label><label className="label">Buscar<input className="input" placeholder="Cliente, oportunidade ou origem" value={busca} onChange={e=>{setBusca(e.target.value);setLimite(20);}}/></label></div>
 <div className="crm-fases" aria-label="Fases do Mubisys"><button aria-pressed={!fase} onClick={()=>{setFase('');setLimite(20);}}><span>Todas as fases</span><b>{filtrados.length}</b></button>{crm.grupos.find(g=>g.id===grupoAtual)?.fases.map(f=><button key={f.id} aria-pressed={fase===f.id} onClick={()=>{setFase(f.id);setLimite(20);}}><span>{f.nome}</span><b>{filtrados.filter(c=>c.faseId===f.id).length}</b></button>)}</div>
 <p className="text-sm text-slate-500">{lista.length} oportunidades · mais antigas por última interação primeiro. Sem probabilidades estimadas.</p><div className="crm-resultados">{lista.slice(0,limite).map(c=><article className="crm-card" key={c.id}><span className="chip-btn">{c.fase}</span><h3>{c.titulo}</h3><p>{c.cliente||'Cliente não identificado'}</p><p>{c.responsavel||'Responsável não localizado'}{c.origem&&` · ${c.origem}`}</p><p>{c.ultimaInteracao?`Última interação: ${dataCurta(c.ultimaInteracao)}`:'Sem data de interação informada'}</p><footer><b>{c.valor===null?'Valor não informado':moeda(c.valor)}</b>{c.clienteId&&<button className="btn-outline" onClick={()=>aoCliente({id:`crm-${c.id}`,clienteId:c.clienteId,cliente:c.cliente})}>Cliente 360</button>}</footer></article>)}</div>{!lista.length&&<p className="text-sm text-slate-500">Nenhuma oportunidade ativa neste filtro.</p>}{lista.length>limite&&<button className="btn-outline" onClick={()=>setLimite(n=>n+20)}>Ver mais oportunidades</button>}</>}
 {!crm&&!erro&&<p role="status">Consultando oportunidades…</p>}
 </section>;
}
