import {useEffect,useState} from 'react';
import {listarPessoasReunioes} from '../services/reunioes.js';
const presencas={pendente:'A confirmar',presente:'Presente',ausente:'Ausente',justificada:'Ausência justificada'};
export default function ParticipantesReuniao({participantes,aoMudar}){
 const [pessoas,setPessoas]=useState([]),[carregando,setCarregando]=useState(true),[erro,setErro]=useState(''),[busca,setBusca]=useState(''),[area,setArea]=useState('');
 async function carregar(){setCarregando(true);setErro('');try{setPessoas(await listarPessoasReunioes());}catch(e){setErro(e.message);}finally{setCarregando(false);}}
 useEffect(()=>{let vivo=true;listarPessoasReunioes().then(p=>{if(vivo)setPessoas(p);}).catch(e=>{if(vivo)setErro(e.message);}).finally(()=>{if(vivo)setCarregando(false);});return()=>{vivo=false;};},[]);
 const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const areas=[...new Set(pessoas.map(p=>p.area))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
 const visiveis=pessoas.filter(p=>(!area||p.area===area)&&norm([p.nome,p.cargo,p.area].join(' ')).includes(norm(busca)));
 const ids=new Set(participantes.filter(p=>p.rhId).map(p=>p.rhId));
 function adicionar(lista){const novas=lista.filter(p=>!ids.has(p.id));if(participantes.length+novas.length>150){setErro('O encontro permite até 150 participantes. Selecione um grupo menor.');return;}aoMudar([...participantes,...novas.map(p=>({id:crypto.randomUUID(),rhId:p.id,nome:p.nome,area:p.area,cargo:p.cargo,presenca:'pendente'}))]);}
 function vincular(id,rhId){const rh=pessoas.find(p=>p.id===rhId);if(rh)aoMudar(participantes.map(p=>p.id===id?{...p,rhId:rh.id,nome:rh.nome,area:rh.area,cargo:rh.cargo}:p));}
 return <section className="reu-editor-secao"><h3>Pessoas do RH e presença</h3><p className="reu-ajuda">Selecione pelo nome ou setor. Cada pessoa fica vinculada ao seu ID do RH; a presença é confirmada separadamente.</p>
 <div className="reu-rh-busca"><input aria-label="Buscar pessoas no RH" placeholder="Buscar pessoa, cargo ou setor…" value={busca} onChange={e=>setBusca(e.target.value)}/><select aria-label="Setor das pessoas no RH" value={area} onChange={e=>setArea(e.target.value)}><option value="">Toda a empresa</option>{areas.map(a=><option key={a}>{a}</option>)}</select><button type="button" className="btn-outline" disabled={carregando||!!erro||!visiveis.some(p=>!ids.has(p.id))} onClick={()=>adicionar(visiveis)}>Adicionar {area?'setor':'pessoas filtradas'}</button></div>
 {carregando?<p role="status">Buscando pessoas no RH…</p>:erro?<p role="alert" className="reu-erro">{erro} <button type="button" onClick={carregar}>Tentar novamente</button></p>:<div className="reu-rh-lista">{visiveis.map(p=><label className="reu-rh-opcao" key={p.id}><input type="checkbox" checked={ids.has(p.id)} onChange={e=>e.target.checked?adicionar([p]):aoMudar(participantes.filter(x=>x.rhId!==p.id))}/><span><strong>{p.nome}</strong><small>{p.area}{p.cargo?' · '+p.cargo:''}</small></span></label>)}{!visiveis.length&&<p className="reu-ajuda">Nenhuma pessoa neste filtro.</p>}</div>}
 <div className="reu-selecionados"><h4>{participantes.length} participante(s) · {participantes.filter(p=>p.presenca==='presente').length} presente(s)</h4>{participantes.map((p,i)=><div className="reu-pessoa" key={p.id}><div>{p.rhId?<><strong>{p.nome}</strong><small>{p.area} · Vinculado ao RH</small></>:<><input aria-label={`Participante ${i+1}`} placeholder="Nome do convidado" required maxLength={180} value={p.nome} onChange={e=>aoMudar(participantes.map(x=>x.id===p.id?{...x,nome:e.target.value}:x))}/><select aria-label={`Vincular ${p.nome||'participante '+(i+1)} ao RH`} value="" onChange={e=>vincular(p.id,e.target.value)}><option value="">Externo / sem vínculo · vincular ao RH</option>{pessoas.filter(x=>!ids.has(x.id)).map(x=><option key={x.id} value={x.id}>{x.nome} · {x.area}</option>)}</select></>}</div><select aria-label={`Presença de ${p.nome||i+1}`} value={p.presenca} onChange={e=>aoMudar(participantes.map(x=>x.id===p.id?{...x,presenca:e.target.value}:x))}>{Object.entries(presencas).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select><button type="button" className="btn-ghost" aria-label={`Remover participante ${i+1}`} onClick={()=>aoMudar(participantes.filter(x=>x.id!==p.id))}>Remover</button></div>)}</div>
 <button type="button" className="btn-outline" disabled={participantes.length>=150} onClick={()=>aoMudar([...participantes,{id:crypto.randomUUID(),rhId:null,nome:'',presenca:'pendente'}])}>+ Convidado externo</button></section>;
}
